*

!package.json
!bun.lock

!apps/
apps/*
!apps/verifier/
apps/verifier/*
!apps/verifier/Cargo.toml
!apps/verifier/Cargo.lock
!apps/verifier/rust-toolchain.toml
!apps/verifier/build.rs
!apps/verifier/src/
!apps/verifier/compiler-worker/
apps/verifier/compiler-worker/node_modules/
!apps/verifier/docker/
apps/verifier/docker/*
!apps/verifier/docker/entrypoint.sh

!packages/
packages/*
!packages/*/
packages/*/*
!packages/*/package.json
!packages/ui/**
packages/ui/node_modules/
!packages/verifier-ui/**
packages/verifier-ui/node_modules/
packages/verifier-ui/dist/
