all: precommit

build: build-ui
    cargo build --release --locked

build-dev:
    cargo build --locked

build-ci: build

fmt:
    cargo fmt --package verifier

fmt-check:
    cargo fmt --package verifier --check

check-deps:
    cargo shear --deny-warnings

clippy:
    cargo clippy --workspace --all-targets --all-features --locked -- -D warnings

check-deny:
    cargo deny check

test: install-compiler-worker
    cd compiler-worker && npm test
    cargo test --locked

test-entrypoint:
    cargo test --locked --test entrypoint_e2e

check-ci: fmt-check check-deps clippy check-deny

check: check-ci test

precommit: fmt build check

run: build-ui
    cargo run --locked

clean:
    cargo clean
    rm -rf ../../packages/verifier-ui/dist

install: install-ui install-compiler-worker

install-ui:
    cd ../.. && bun ci

install-compiler-worker:
    cd compiler-worker && npm ci
    cd compiler-worker && npm run apply-patches

build-ui: install-ui
    cd ../../packages/verifier-ui && bun run build

generate-registry:
    cd compiler-worker && npm run generate-registry
