[package]
name = "ton-language-server-core"
version = { workspace = true }
publish = false
authors = { workspace = true }
edition = { workspace = true }
rust-version = { workspace = true }
homepage = { workspace = true }
documentation = { workspace = true }
repository = { workspace = true }
license = { workspace = true }

[dependencies]
anyhow = { workspace = true }
tlb-syntax = { workspace = true }
ton-syntax = { workspace = true }
tracing = { workspace = true }
tree-sitter = { workspace = true }

[dev-dependencies]
expect-test = { workspace = true }

[[test]]
name = "tlb_definition"
path = "tests/languages/tlb/definition.rs"

[[test]]
name = "tlb_incremental_edit"
path = "tests/languages/tlb/incremental_edit.rs"

[lints]
workspace = true

[lib]
doctest = false
