export const EXIT_CODE_DESCRIPTIONS = {
  0: {
    name: "Success",
    description: "Standard successful execution exit code.",
    phase: "Compute and action phases",
  },
  1: {
    name: "Alt Success",
    description: "Alternative successful execution exit code.",
    phase: "Compute phase",
  },
  2: { name: "Stack Underflow", description: "Stack underflow.", phase: "Compute phase" },
  3: { name: "Stack Overflow", description: "Stack overflow.", phase: "Compute phase" },
  4: { name: "Integer Overflow", description: "Integer overflow.", phase: "Compute phase" },
  5: { name: "Range Check Error", description: "Range check error.", phase: "Compute phase" },
  6: { name: "Invalid Opcode", description: "Invalid TVM opcode.", phase: "Compute phase" },
  7: { name: "Type Check Error", description: "Type check error.", phase: "Compute phase" },
  8: { name: "Cell Overflow", description: "Cell overflow.", phase: "Compute phase" },
  9: { name: "Cell Underflow", description: "Cell underflow.", phase: "Compute phase" },
  10: { name: "Dictionary Error", description: "Dictionary error.", phase: "Compute phase" },
  11: { name: "Unknown Error", description: "Unknown error.", phase: "Compute phase" },
  12: { name: "Fatal Error", description: "Fatal error.", phase: "Compute phase" },
  13: { name: "Out of Gas", description: "Out of gas error.", phase: "Compute phase" },
  32: {
    name: "Invalid Action List",
    description: "Action list is invalid.",
    phase: "Action phase",
  },
  33: {
    name: "Action List Too Long",
    description: "Action list is too long.",
    phase: "Action phase",
  },
  34: {
    name: "Invalid Action",
    description: "Action is invalid or not supported.",
    phase: "Action phase",
  },
  35: {
    name: "Invalid Source Address",
    description: "Invalid source address.",
    phase: "Action phase",
  },
  36: {
    name: "Invalid Destination Address",
    description: "Invalid destination address.",
    phase: "Action phase",
  },
  37: { name: "Not Enough Toncoin", description: "Not enough Toncoin.", phase: "Action phase" },
  38: {
    name: "Not Enough Extra Currencies",
    description: "Not enough extra currencies.",
    phase: "Action phase",
  },
  39: {
    name: "Message Too Large",
    description: "Outbound message too large.",
    phase: "Action phase",
  },
  128: { name: "Null Reference", description: "Null reference exception.", phase: "Compute phase" },
  129: {
    name: "Invalid Serialization",
    description: "Invalid serialization prefix.",
    phase: "Compute phase",
  },
  130: { name: "No Receiver", description: "No receiver for opcode.", phase: "Compute phase" },
  132: { name: "Access Denied", description: "Access denied.", phase: "Compute phase" },
  134: { name: "Invalid Argument", description: "Invalid argument.", phase: "Compute phase" },
  135: { name: "Code Not Found", description: "Code not found.", phase: "Compute phase" },
} as const
