import {TOKEN_PLACEHOLDER_IMAGE as EXPLORER_TOKEN_PLACEHOLDER_IMAGE} from "../explorer/components/imageFallbacks"

export const QUICK_AMOUNTS = ["1", "5", "20", "100"]
export const TOKEN_PLACEHOLDER_IMAGE = EXPLORER_TOKEN_PLACEHOLDER_IMAGE
export const NFT_PLACEHOLDER_IMAGE = EXPLORER_TOKEN_PLACEHOLDER_IMAGE
