rules:
  unpinned-uses:
    config:
      policies:
        actions/cache/restore: ref-pin
        actions/cache/save: ref-pin
        actions/checkout: ref-pin
        actions/download-artifact: ref-pin
        actions/github-script: ref-pin
        actions/labeler: ref-pin
        actions/setup-node: ref-pin
        actions/upload-artifact: ref-pin
        i582/setup-acton: ref-pin
        zizmorcore/zizmor-action: ref-pin
  dangerous-triggers:
    ignore:
      - labeler.yml:3:1
