rules:
  dangerous-triggers:
    ignore:
      - labeler.yml:3:1
  excessive-permissions:
    ignore:
      - release.yml
  template-injection:
    ignore:
      - release.yml
  secrets-outside-env:
    ignore:
      - build.yml # secrets.ACTON_PUBLIC
      - release-objs.yml # secrets.ACTON_PUBLIC
      - publish-mirror.yml # secrets.ACTON_PUBLIC
