import argparse
import json
import sys
from pathlib import Path
from typing import Any, NamedTuple

HEADER_LINES = [
    "# THIS FILE IS AUTOGENERATED. DO NOT EDIT IT MANUALLY.",
    "#",
    "# Tracked revision data for native TON archives in `objs/`.",
    "# `build.rs` watches this file with `cargo:rerun-if-changed`, so bump the",
    "# revision and refresh the SHA-256 values whenever `libemulator.a` or",
    "# `libtolk.a` is refreshed.",
    "#",
    "# THIS FILE IS AUTOGENERATED. DO NOT EDIT IT MANUALLY.",
    "",
]

ManifestTarget = dict[str, str]
ArtifactsManifest = dict[str, ManifestTarget]


class TargetLock(NamedTuple):
    ton_commit: str
    rust_target: str
    sha256_libemulator: str
    sha256_libtolk: str


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description="Generate an artifacts manifest TOML from target lock JSON files.")
    parser.add_argument(
        "--input-path",
        required=True,
        metavar="PATH",
        help="Path to a target lock JSON file or a directory with target lock JSON files.",
    )
    parser.add_argument(
        "--output-path",
        metavar="PATH",
        help="Path to write the generated TOML manifest; defaults to stdout.",
    )
    parser.add_argument(
        "--artifact-set-revision",
        metavar="integer",
        type=int,
        default=1,
        help="Artifact set revision to write into the manifest. Default: %(default)s.",
    )

    return parser


def parse_string_field(value: dict[str, Any], field_name: str, json_path: Path) -> str:
    field_value = value.get(field_name)
    if not isinstance(field_value, str) or not field_value:
        raise ValueError(f"expected {field_name} to be a non-empty string in {json_path}")

    return field_value


def parse_target_lock(value: Any, json_path: Path) -> TargetLock:
    if not isinstance(value, dict):
        raise ValueError(f"expected top-level JSON object in {json_path}")

    ton_commit = parse_string_field(value, "ton_commit", json_path)
    rust_target = parse_string_field(value, "rust_target", json_path)
    sha256_libemulator = parse_string_field(value, "sha256_libemulator", json_path)
    sha256_libtolk = parse_string_field(value, "sha256_libtolk", json_path)

    return TargetLock(
        ton_commit=ton_commit,
        rust_target=rust_target,
        sha256_libemulator=sha256_libemulator,
        sha256_libtolk=sha256_libtolk,
    )


def parse_target_lock_file(json_path: Path) -> TargetLock:
    content = json_path.read_text(encoding="utf-8")

    try:
        parsed_content = json.loads(content)
    except json.JSONDecodeError as exc:
        raise ValueError(f"failed to parse JSON file {json_path}: {exc}") from exc

    return parse_target_lock(parsed_content, json_path)


def parse_target_locks(input_path: Path) -> list[TargetLock]:
    resolved_input_path = input_path.resolve()

    if not resolved_input_path.exists():
        raise ValueError(f"input path does not exist: {input_path}")

    if resolved_input_path.is_dir():
        json_paths = sorted(
            path for path in resolved_input_path.iterdir() if path.is_file() and path.suffix.lower() == ".json"
        )
        if not json_paths:
            raise ValueError(f"input directory contains no .json files: {input_path}")

        return [parse_target_lock_file(json_path) for json_path in json_paths]

    if resolved_input_path.is_file() and resolved_input_path.suffix.lower() == ".json":
        return [parse_target_lock_file(resolved_input_path)]

    raise ValueError(f"input path must point to a .json file or a directory: {input_path}")


def build_artifacts_manifest(target_locks: list[TargetLock]) -> ArtifactsManifest:
    if not target_locks:
        raise ValueError("at least one target lock is required to build the manifest")

    targets: ArtifactsManifest = {}

    for target_lock in target_locks:
        rust_target = target_lock.rust_target

        if rust_target in targets:
            raise ValueError(f"duplicate rust_target in input: {rust_target}")

        targets[rust_target] = {
            "libemulator": target_lock.sha256_libemulator,
            "libtolk": target_lock.sha256_libtolk,
        }

    return targets


def render_artifacts_manifest_toml(
    targets: ArtifactsManifest,
    artifact_set_revision: int,
) -> str:
    lines = [*HEADER_LINES, f"artifact_set_revision = {artifact_set_revision}"]

    for rust_target in sorted(targets):
        manifest_target = targets[rust_target]
        target_lines = [
            "",
            f"[target.{rust_target}.sha256]",
        ]

        for artifact_name, artifact_sha256 in sorted(manifest_target.items()):
            target_lines.append(f'{artifact_name} = "{artifact_sha256}"')

        lines.extend(target_lines)

    lines.append("")
    return "\n".join(lines)


def main() -> None:
    parser = build_parser()
    args = parser.parse_args()

    try:
        target_locks = parse_target_locks(Path(args.input_path))
        artifacts_manifest = build_artifacts_manifest(target_locks)
    except ValueError as error:
        parser.error(str(error))

    toml = render_artifacts_manifest_toml(artifacts_manifest, args.artifact_set_revision)

    if args.output_path is None:
        sys.stdout.write(toml)
        return

    Path(args.output_path).write_text(toml, encoding="utf-8")


if __name__ == "__main__":
    main()
