[package]
name = "faucet-antifraud"
version = { workspace = true }
publish = false
authors = { workspace = true }
edition = { workspace = true }
rust-version = { workspace = true }
repository = { workspace = true }
license = { workspace = true }

[dependencies]
faucet-config = { workspace = true }

[lib]
doctest = false
