[files]
extend-exclude = [
  "dist-workspace.toml",
  "docs/**",
  "block.tlb",
  "crates/tasm/spec/**",
  "crates/tolkc/assets/**",
  "src/ffi/testdata/**",
  "tests/**/snapshots/**",
  "src/commands/new/templates/*/app/**",
  "src/commands/new/templates/*/wrappers-ts/**",
  "src/commands/new/templates/*/package-lock.json",
]

[default]
extend-ignore-re = [
  "\\bADDD\\b",
  "\\bTrUe\\b",
  "\\balse\\b",
  "\\b(?:test-)?ba-stdlib-[A-Za-z0-9-]+\\b",
  "[dD]arcula"
]
