[files]
extend-exclude = [
  "dist-workspace.toml",
  "docs/.next/**",
  "docs/.source/**",
  "docs/bun.lock",
  "docs/grammars/**",
  "docs/node_modules/**",
  "docs/out/**",
  "docs/public/resources/**",
  "docs/src/lib/og/**",
  "block.tlb",
  "crates/tasm-core/spec/**",
  "crates/tolk-compiler/assets/**",
  "src/ffi/testdata/**",
  "tests/**/snapshots/**",
  "src/commands/new/templates/*/app/**",
  "src/commands/new/templates/*/wrappers-ts/**",
  "src/commands/new/templates/*/package-lock.json",
  "crates/acton-abi-catalog/data/data-abis.json",
  "*.csv",
]

[default]
extend-ignore-re = [
  "\\b[a-zA-Z0-9_+/\\-]{48,}\\b", # user-friendly addresses
  "\\bADDD\\b",
  "\\bTrUe\\b",
  "\\balse\\b",
  "\\b(?:test-)?ba-stdlib-[A-Za-z0-9-]+\\b",
  "[dD]arcula",
  "Ba"
]
