[package]
name = "Acton"
description = "All-in-one toolkit for TON Blockchain smartcontract development"
version = "0.1.0"
license = "MIT"

[contracts.counter]
name = "Counter"
src = "counter.tolk"
depends = []

[contracts.jetton-minter]
name = "Minter"
src = ".jetton/contracts/jetton-minter-contract.tolk"
depends = ["jetton-wallet"]

[contracts.jetton-wallet]
name = "Wallet"
src = ".jetton/contracts/jetton-wallet-contract.tolk"
depends = []

[test]
include = ["tests/acton-stdlib/**", ".jetton/**"]

[test.mutation]

[networks.localnet]
v2-url = "http://localhost:3010/api/v2"
v3-url = "http://localhost:3010/api/v3"

[mappings]
acton = ".acton"
local-acton = "lib"
