[package]
name = "Acton"
description = "All-in-one toolkit for TON Blockchain smartcontract development"
version = "0.3.1"
license = "MIT"

[test]
include = ["tests/acton-stdlib/**"]
fail-on-diff = false

[test.mutation]

[lint]
exclude = ["lib/**"]

[localnet]
port = 3010
accounts = []

[networks.localnet]
api = { v2 = "http://localhost:3010/api/v2", v3 = "http://localhost:3010/api/v3" }

[import-mappings]
acton = ".acton"
local-acton = "lib"
