[package]
name = "Acton"
description = "All-in-one toolkit for TON Blockchain smartcontract development"
version = "0.0.16"
license = "MIT"

[contracts.counter]
name = "Counter"
src = "counter.tolk"
depends = []

[contracts.jetton-minter]
name = "Minter"
src = ".jetton/contracts/jetton-minter-contract.tolk"
depends = ["jetton-wallet"]

[contracts.jetton-wallet]
name = "Wallet"
src = ".jetton/contracts/jetton-wallet-contract.tolk"
depends = []

[test]
include = [
    "tests/acton-stdlib/**",
    ".jetton/**",
]
fail-on-diff = false

[test.mutation]

[litenode]
port = 3010
accounts = ["local-wallet"]

[mappings]
acton = ".acton"
contracts = "contracts"
gen = "gen"
local-acton = "lib"
tests = "tests"
wrappers = "tests/wrappers"

[networks.localnet.api]
v2 = "http://localhost:3010/api/v2"
v3 = "http://localhost:3010/api/v3"
