name: Build and Check

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
  workflow_dispatch:

concurrency:
  group: build-${{ github.ref }}
  cancel-in-progress: true

permissions: { }
jobs:
  build-linux:
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - name: Fetch Sources
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: Build Rust Binaries
        uses: ./.github/actions/build-rust

  check-linux:
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - name: Fetch Sources
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: Cache Cargo
        uses: Swatinem/rust-cache@c19371144df3bb44fab255c43d04cbc2ab54d1c4 # v2.9.1
        with:
          key: ${{ runner.os }}-${{ runner.arch }}
          save-if: ${{ github.ref == 'refs/heads/master' }}

      - name: Install Rust
        run: rustup toolchain install

      - name: Installing additional Rust components
        uses: taiki-e/install-action@a2352fc6ce487f030a3aa709482d57823eadfb37 # v2.75.16
        with:
          tool: just@1.49.0,cargo-shear@1.11.2,cargo-deny@0.19.4
          fallback: none

      - name: Run tests
        run: just test

      - name: Run check
        run: just check-ci
