/* Automatically @generated by tree-sitter v0.25.5 */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 69
#define LARGE_STATE_COUNT 8
#define SYMBOL_COUNT 35
#define ALIAS_COUNT 0
#define TOKEN_COUNT 19
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 8
#define MAX_ALIAS_SEQUENCE_LENGTH 3
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 14
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  sym_identifier = 1,
  sym_stack_element = 2,
  sym_control_register = 3,
  anon_sym_LBRACE = 4,
  anon_sym_RBRACE = 5,
  anon_sym_LBRACK = 6,
  anon_sym_RBRACK = 7,
  anon_sym_EQ_GT = 8,
  sym_hex_literal = 9,
  sym_bin_literal = 10,
  sym_boc_literal = 11,
  sym_string_literal = 12,
  sym_integer_literal = 13,
  sym_kw_ref = 14,
  sym_kw_embed = 15,
  sym_kw_exotic = 16,
  sym_kw_library = 17,
  sym_comment = 18,
  sym_source_file = 19,
  sym_instructions = 20,
  sym_instruction = 21,
  sym_argument = 22,
  sym_code = 23,
  sym_dictionary = 24,
  sym_dictionary_entry = 25,
  sym_explicit_ref = 26,
  sym_embed_slice = 27,
  sym_exotic = 28,
  sym_exotic_library = 29,
  sym_default_exotic = 30,
  sym_data_literal = 31,
  aux_sym_instructions_repeat1 = 32,
  aux_sym_instruction_repeat1 = 33,
  aux_sym_dictionary_repeat1 = 34,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_identifier] = "identifier",
  [sym_stack_element] = "stack_element",
  [sym_control_register] = "control_register",
  [anon_sym_LBRACE] = "{",
  [anon_sym_RBRACE] = "}",
  [anon_sym_LBRACK] = "[",
  [anon_sym_RBRACK] = "]",
  [anon_sym_EQ_GT] = "=>",
  [sym_hex_literal] = "hex_literal",
  [sym_bin_literal] = "bin_literal",
  [sym_boc_literal] = "boc_literal",
  [sym_string_literal] = "string_literal",
  [sym_integer_literal] = "integer_literal",
  [sym_kw_ref] = "kw_ref",
  [sym_kw_embed] = "kw_embed",
  [sym_kw_exotic] = "kw_exotic",
  [sym_kw_library] = "kw_library",
  [sym_comment] = "comment",
  [sym_source_file] = "source_file",
  [sym_instructions] = "instructions",
  [sym_instruction] = "instruction",
  [sym_argument] = "argument",
  [sym_code] = "code",
  [sym_dictionary] = "dictionary",
  [sym_dictionary_entry] = "dictionary_entry",
  [sym_explicit_ref] = "explicit_ref",
  [sym_embed_slice] = "embed_slice",
  [sym_exotic] = "exotic",
  [sym_exotic_library] = "exotic_library",
  [sym_default_exotic] = "default_exotic",
  [sym_data_literal] = "data_literal",
  [aux_sym_instructions_repeat1] = "instructions_repeat1",
  [aux_sym_instruction_repeat1] = "instruction_repeat1",
  [aux_sym_dictionary_repeat1] = "dictionary_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_identifier] = sym_identifier,
  [sym_stack_element] = sym_stack_element,
  [sym_control_register] = sym_control_register,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [anon_sym_LBRACK] = anon_sym_LBRACK,
  [anon_sym_RBRACK] = anon_sym_RBRACK,
  [anon_sym_EQ_GT] = anon_sym_EQ_GT,
  [sym_hex_literal] = sym_hex_literal,
  [sym_bin_literal] = sym_bin_literal,
  [sym_boc_literal] = sym_boc_literal,
  [sym_string_literal] = sym_string_literal,
  [sym_integer_literal] = sym_integer_literal,
  [sym_kw_ref] = sym_kw_ref,
  [sym_kw_embed] = sym_kw_embed,
  [sym_kw_exotic] = sym_kw_exotic,
  [sym_kw_library] = sym_kw_library,
  [sym_comment] = sym_comment,
  [sym_source_file] = sym_source_file,
  [sym_instructions] = sym_instructions,
  [sym_instruction] = sym_instruction,
  [sym_argument] = sym_argument,
  [sym_code] = sym_code,
  [sym_dictionary] = sym_dictionary,
  [sym_dictionary_entry] = sym_dictionary_entry,
  [sym_explicit_ref] = sym_explicit_ref,
  [sym_embed_slice] = sym_embed_slice,
  [sym_exotic] = sym_exotic,
  [sym_exotic_library] = sym_exotic_library,
  [sym_default_exotic] = sym_default_exotic,
  [sym_data_literal] = sym_data_literal,
  [aux_sym_instructions_repeat1] = aux_sym_instructions_repeat1,
  [aux_sym_instruction_repeat1] = aux_sym_instruction_repeat1,
  [aux_sym_dictionary_repeat1] = aux_sym_dictionary_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [sym_stack_element] = {
    .visible = true,
    .named = true,
  },
  [sym_control_register] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ_GT] = {
    .visible = true,
    .named = false,
  },
  [sym_hex_literal] = {
    .visible = true,
    .named = true,
  },
  [sym_bin_literal] = {
    .visible = true,
    .named = true,
  },
  [sym_boc_literal] = {
    .visible = true,
    .named = true,
  },
  [sym_string_literal] = {
    .visible = true,
    .named = true,
  },
  [sym_integer_literal] = {
    .visible = true,
    .named = true,
  },
  [sym_kw_ref] = {
    .visible = true,
    .named = true,
  },
  [sym_kw_embed] = {
    .visible = true,
    .named = true,
  },
  [sym_kw_exotic] = {
    .visible = true,
    .named = true,
  },
  [sym_kw_library] = {
    .visible = true,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym_instructions] = {
    .visible = true,
    .named = true,
  },
  [sym_instruction] = {
    .visible = true,
    .named = true,
  },
  [sym_argument] = {
    .visible = true,
    .named = true,
  },
  [sym_code] = {
    .visible = true,
    .named = true,
  },
  [sym_dictionary] = {
    .visible = true,
    .named = true,
  },
  [sym_dictionary_entry] = {
    .visible = true,
    .named = true,
  },
  [sym_explicit_ref] = {
    .visible = true,
    .named = true,
  },
  [sym_embed_slice] = {
    .visible = true,
    .named = true,
  },
  [sym_exotic] = {
    .visible = true,
    .named = true,
  },
  [sym_exotic_library] = {
    .visible = true,
    .named = true,
  },
  [sym_default_exotic] = {
    .visible = true,
    .named = true,
  },
  [sym_data_literal] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_instructions_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_instruction_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_dictionary_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum ts_field_identifiers {
  field_args = 1,
  field_code = 2,
  field_data = 3,
  field_entries = 4,
  field_id = 5,
  field_instructions = 6,
  field_lib = 7,
  field_name = 8,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_args] = "args",
  [field_code] = "code",
  [field_data] = "data",
  [field_entries] = "entries",
  [field_id] = "id",
  [field_instructions] = "instructions",
  [field_lib] = "lib",
  [field_name] = "name",
};

static const TSMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 1},
  [2] = {.index = 1, .length = 1},
  [3] = {.index = 2, .length = 2},
  [4] = {.index = 4, .length = 1},
  [5] = {.index = 5, .length = 1},
  [6] = {.index = 6, .length = 1},
  [7] = {.index = 7, .length = 1},
  [8] = {.index = 8, .length = 1},
  [9] = {.index = 9, .length = 2},
  [10] = {.index = 11, .length = 1},
  [11] = {.index = 12, .length = 1},
  [12] = {.index = 13, .length = 2},
  [13] = {.index = 15, .length = 2},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_name, 0},
  [1] =
    {field_args, 0},
  [2] =
    {field_args, 1, .inherited = true},
    {field_name, 0},
  [4] =
    {field_code, 1},
  [5] =
    {field_data, 1},
  [6] =
    {field_lib, 1},
  [7] =
    {field_data, 0},
  [8] =
    {field_entries, 0},
  [9] =
    {field_args, 0, .inherited = true},
    {field_args, 1, .inherited = true},
  [11] =
    {field_instructions, 1},
  [12] =
    {field_entries, 1, .inherited = true},
  [13] =
    {field_entries, 0, .inherited = true},
    {field_entries, 1, .inherited = true},
  [15] =
    {field_code, 2},
    {field_id, 0},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 2,
  [6] = 4,
  [7] = 3,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 10,
  [16] = 13,
  [17] = 12,
  [18] = 8,
  [19] = 14,
  [20] = 11,
  [21] = 9,
  [22] = 22,
  [23] = 22,
  [24] = 22,
  [25] = 22,
  [26] = 26,
  [27] = 27,
  [28] = 27,
  [29] = 26,
  [30] = 30,
  [31] = 30,
  [32] = 9,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 11,
  [37] = 37,
  [38] = 38,
  [39] = 33,
  [40] = 35,
  [41] = 37,
  [42] = 8,
  [43] = 43,
  [44] = 9,
  [45] = 45,
  [46] = 11,
  [47] = 8,
  [48] = 43,
  [49] = 45,
  [50] = 34,
  [51] = 38,
  [52] = 52,
  [53] = 53,
  [54] = 52,
  [55] = 53,
  [56] = 56,
  [57] = 57,
  [58] = 58,
  [59] = 58,
  [60] = 60,
  [61] = 61,
  [62] = 62,
  [63] = 63,
  [64] = 64,
  [65] = 65,
  [66] = 64,
  [67] = 64,
  [68] = 64,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(16);
      ADVANCE_MAP(
        '"', 2,
        '-', 4,
        '/', 3,
        '0', 35,
        '=', 5,
        '[', 21,
        ']', 22,
        'b', 26,
        's', 24,
        'x', 27,
        '{', 19,
        '}', 20,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      if (('1' <= lookahead && lookahead <= '9')) ADVANCE(36);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(30);
      END_STATE();
    case 1:
      if (lookahead == '"') ADVANCE(2);
      if (lookahead == '/') ADVANCE(3);
      if (lookahead == 'b') ADVANCE(26);
      if (lookahead == 'x') ADVANCE(27);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(1);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(30);
      END_STATE();
    case 2:
      if (lookahead == '"') ADVANCE(34);
      if (lookahead != 0 &&
          lookahead != '\\') ADVANCE(2);
      END_STATE();
    case 3:
      if (lookahead == '/') ADVANCE(40);
      END_STATE();
    case 4:
      if (lookahead == '0') ADVANCE(35);
      if (('1' <= lookahead && lookahead <= '9')) ADVANCE(36);
      END_STATE();
    case 5:
      if (lookahead == '>') ADVANCE(23);
      END_STATE();
    case 6:
      if (lookahead == '_') ADVANCE(8);
      if (lookahead == '}') ADVANCE(31);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(6);
      END_STATE();
    case 7:
      if (lookahead == '}') ADVANCE(32);
      if (lookahead == '0' ||
          lookahead == '1') ADVANCE(7);
      END_STATE();
    case 8:
      if (lookahead == '}') ADVANCE(31);
      END_STATE();
    case 9:
      if (lookahead == '}') ADVANCE(33);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(9);
      END_STATE();
    case 10:
      if (lookahead == '0' ||
          lookahead == '1') ADVANCE(37);
      END_STATE();
    case 11:
      if (('0' <= lookahead && lookahead <= '7')) ADVANCE(38);
      END_STATE();
    case 12:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(36);
      END_STATE();
    case 13:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(18);
      END_STATE();
    case 14:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(39);
      END_STATE();
    case 15:
      if (eof) ADVANCE(16);
      if (lookahead == '/') ADVANCE(3);
      if (lookahead == '}') ADVANCE(20);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(15);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(30);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(sym_stack_element);
      if (lookahead == '_') ADVANCE(29);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(17);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(sym_stack_element);
      if (lookahead == '_') ADVANCE(13);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(18);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(anon_sym_LBRACK);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(anon_sym_RBRACK);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(anon_sym_EQ_GT);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == '-') ADVANCE(13);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(17);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(30);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'c') ADVANCE(28);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(30);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'o') ADVANCE(25);
      if (lookahead == '{') ADVANCE(7);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(30);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == '{') ADVANCE(6);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(30);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == '{') ADVANCE(9);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(30);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(sym_identifier);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(17);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(30);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(sym_identifier);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(30);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(sym_hex_literal);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(sym_bin_literal);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(sym_boc_literal);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(sym_string_literal);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(sym_integer_literal);
      if (lookahead == '_') ADVANCE(12);
      if (lookahead == 'B' ||
          lookahead == 'b') ADVANCE(10);
      if (lookahead == 'O' ||
          lookahead == 'o') ADVANCE(11);
      if (lookahead == 'X' ||
          lookahead == 'x') ADVANCE(14);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(36);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(sym_integer_literal);
      if (lookahead == '_') ADVANCE(12);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(36);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(sym_integer_literal);
      if (lookahead == '_') ADVANCE(10);
      if (lookahead == '0' ||
          lookahead == '1') ADVANCE(37);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(sym_integer_literal);
      if (lookahead == '_') ADVANCE(11);
      if (('0' <= lookahead && lookahead <= '7')) ADVANCE(38);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(sym_integer_literal);
      if (lookahead == '_') ADVANCE(14);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(39);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(40);
      END_STATE();
    default:
      return false;
  }
}

static bool ts_lex_keywords(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (lookahead == 'c') ADVANCE(1);
      if (lookahead == 'e') ADVANCE(2);
      if (lookahead == 'l') ADVANCE(3);
      if (lookahead == 'r') ADVANCE(4);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      END_STATE();
    case 1:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(5);
      END_STATE();
    case 2:
      if (lookahead == 'm') ADVANCE(6);
      if (lookahead == 'x') ADVANCE(7);
      END_STATE();
    case 3:
      if (lookahead == 'i') ADVANCE(8);
      END_STATE();
    case 4:
      if (lookahead == 'e') ADVANCE(9);
      END_STATE();
    case 5:
      ACCEPT_TOKEN(sym_control_register);
      if (lookahead == '_') ADVANCE(10);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(5);
      END_STATE();
    case 6:
      if (lookahead == 'b') ADVANCE(11);
      END_STATE();
    case 7:
      if (lookahead == 'o') ADVANCE(12);
      END_STATE();
    case 8:
      if (lookahead == 'b') ADVANCE(13);
      END_STATE();
    case 9:
      if (lookahead == 'f') ADVANCE(14);
      END_STATE();
    case 10:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(5);
      END_STATE();
    case 11:
      if (lookahead == 'e') ADVANCE(15);
      END_STATE();
    case 12:
      if (lookahead == 't') ADVANCE(16);
      END_STATE();
    case 13:
      if (lookahead == 'r') ADVANCE(17);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(sym_kw_ref);
      END_STATE();
    case 15:
      if (lookahead == 'd') ADVANCE(18);
      END_STATE();
    case 16:
      if (lookahead == 'i') ADVANCE(19);
      END_STATE();
    case 17:
      if (lookahead == 'a') ADVANCE(20);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(sym_kw_embed);
      END_STATE();
    case 19:
      if (lookahead == 'c') ADVANCE(21);
      END_STATE();
    case 20:
      if (lookahead == 'r') ADVANCE(22);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(sym_kw_exotic);
      END_STATE();
    case 22:
      if (lookahead == 'y') ADVANCE(23);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(sym_kw_library);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 15},
  [2] = {.lex_state = 0},
  [3] = {.lex_state = 0},
  [4] = {.lex_state = 0},
  [5] = {.lex_state = 0},
  [6] = {.lex_state = 0},
  [7] = {.lex_state = 0},
  [8] = {.lex_state = 0},
  [9] = {.lex_state = 0},
  [10] = {.lex_state = 0},
  [11] = {.lex_state = 0},
  [12] = {.lex_state = 0},
  [13] = {.lex_state = 0},
  [14] = {.lex_state = 0},
  [15] = {.lex_state = 0},
  [16] = {.lex_state = 0},
  [17] = {.lex_state = 0},
  [18] = {.lex_state = 0},
  [19] = {.lex_state = 0},
  [20] = {.lex_state = 0},
  [21] = {.lex_state = 0},
  [22] = {.lex_state = 15},
  [23] = {.lex_state = 15},
  [24] = {.lex_state = 15},
  [25] = {.lex_state = 15},
  [26] = {.lex_state = 15},
  [27] = {.lex_state = 15},
  [28] = {.lex_state = 15},
  [29] = {.lex_state = 15},
  [30] = {.lex_state = 1},
  [31] = {.lex_state = 1},
  [32] = {.lex_state = 15},
  [33] = {.lex_state = 15},
  [34] = {.lex_state = 0},
  [35] = {.lex_state = 15},
  [36] = {.lex_state = 15},
  [37] = {.lex_state = 15},
  [38] = {.lex_state = 15},
  [39] = {.lex_state = 15},
  [40] = {.lex_state = 15},
  [41] = {.lex_state = 15},
  [42] = {.lex_state = 15},
  [43] = {.lex_state = 15},
  [44] = {.lex_state = 15},
  [45] = {.lex_state = 0},
  [46] = {.lex_state = 15},
  [47] = {.lex_state = 15},
  [48] = {.lex_state = 15},
  [49] = {.lex_state = 0},
  [50] = {.lex_state = 0},
  [51] = {.lex_state = 15},
  [52] = {.lex_state = 0},
  [53] = {.lex_state = 0},
  [54] = {.lex_state = 0},
  [55] = {.lex_state = 0},
  [56] = {.lex_state = 0},
  [57] = {.lex_state = 0},
  [58] = {.lex_state = 0},
  [59] = {.lex_state = 0},
  [60] = {.lex_state = 0},
  [61] = {.lex_state = 0},
  [62] = {.lex_state = 0},
  [63] = {.lex_state = 0},
  [64] = {.lex_state = 0},
  [65] = {.lex_state = 0},
  [66] = {.lex_state = 0},
  [67] = {.lex_state = 0},
  [68] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym_identifier] = ACTIONS(1),
    [sym_stack_element] = ACTIONS(1),
    [sym_control_register] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [anon_sym_LBRACK] = ACTIONS(1),
    [anon_sym_RBRACK] = ACTIONS(1),
    [anon_sym_EQ_GT] = ACTIONS(1),
    [sym_hex_literal] = ACTIONS(1),
    [sym_bin_literal] = ACTIONS(1),
    [sym_boc_literal] = ACTIONS(1),
    [sym_string_literal] = ACTIONS(1),
    [sym_integer_literal] = ACTIONS(1),
    [sym_kw_ref] = ACTIONS(1),
    [sym_kw_embed] = ACTIONS(1),
    [sym_kw_exotic] = ACTIONS(1),
    [sym_kw_library] = ACTIONS(1),
    [sym_comment] = ACTIONS(3),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(63),
    [sym_instructions] = STATE(62),
    [sym_instruction] = STATE(27),
    [sym_explicit_ref] = STATE(27),
    [sym_embed_slice] = STATE(27),
    [sym_exotic] = STATE(27),
    [aux_sym_instructions_repeat1] = STATE(27),
    [ts_builtin_sym_end] = ACTIONS(5),
    [sym_identifier] = ACTIONS(7),
    [sym_kw_ref] = ACTIONS(9),
    [sym_kw_embed] = ACTIONS(11),
    [sym_kw_exotic] = ACTIONS(13),
    [sym_comment] = ACTIONS(3),
  },
  [STATE(2)] = {
    [sym_argument] = STATE(10),
    [sym_code] = STATE(13),
    [sym_dictionary] = STATE(13),
    [sym_data_literal] = STATE(13),
    [aux_sym_instruction_repeat1] = STATE(3),
    [ts_builtin_sym_end] = ACTIONS(15),
    [sym_identifier] = ACTIONS(17),
    [sym_stack_element] = ACTIONS(19),
    [sym_control_register] = ACTIONS(19),
    [anon_sym_LBRACE] = ACTIONS(21),
    [anon_sym_LBRACK] = ACTIONS(23),
    [sym_hex_literal] = ACTIONS(25),
    [sym_bin_literal] = ACTIONS(25),
    [sym_boc_literal] = ACTIONS(25),
    [sym_string_literal] = ACTIONS(25),
    [sym_integer_literal] = ACTIONS(19),
    [sym_kw_ref] = ACTIONS(15),
    [sym_kw_embed] = ACTIONS(15),
    [sym_kw_exotic] = ACTIONS(15),
    [sym_comment] = ACTIONS(3),
  },
  [STATE(3)] = {
    [sym_argument] = STATE(10),
    [sym_code] = STATE(13),
    [sym_dictionary] = STATE(13),
    [sym_data_literal] = STATE(13),
    [aux_sym_instruction_repeat1] = STATE(4),
    [ts_builtin_sym_end] = ACTIONS(27),
    [sym_identifier] = ACTIONS(29),
    [sym_stack_element] = ACTIONS(19),
    [sym_control_register] = ACTIONS(19),
    [anon_sym_LBRACE] = ACTIONS(21),
    [anon_sym_LBRACK] = ACTIONS(23),
    [sym_hex_literal] = ACTIONS(25),
    [sym_bin_literal] = ACTIONS(25),
    [sym_boc_literal] = ACTIONS(25),
    [sym_string_literal] = ACTIONS(25),
    [sym_integer_literal] = ACTIONS(19),
    [sym_kw_ref] = ACTIONS(27),
    [sym_kw_embed] = ACTIONS(27),
    [sym_kw_exotic] = ACTIONS(27),
    [sym_comment] = ACTIONS(3),
  },
  [STATE(4)] = {
    [sym_argument] = STATE(10),
    [sym_code] = STATE(13),
    [sym_dictionary] = STATE(13),
    [sym_data_literal] = STATE(13),
    [aux_sym_instruction_repeat1] = STATE(4),
    [ts_builtin_sym_end] = ACTIONS(31),
    [sym_identifier] = ACTIONS(33),
    [sym_stack_element] = ACTIONS(35),
    [sym_control_register] = ACTIONS(35),
    [anon_sym_LBRACE] = ACTIONS(38),
    [anon_sym_LBRACK] = ACTIONS(41),
    [sym_hex_literal] = ACTIONS(44),
    [sym_bin_literal] = ACTIONS(44),
    [sym_boc_literal] = ACTIONS(44),
    [sym_string_literal] = ACTIONS(44),
    [sym_integer_literal] = ACTIONS(35),
    [sym_kw_ref] = ACTIONS(31),
    [sym_kw_embed] = ACTIONS(31),
    [sym_kw_exotic] = ACTIONS(31),
    [sym_comment] = ACTIONS(3),
  },
  [STATE(5)] = {
    [sym_argument] = STATE(15),
    [sym_code] = STATE(16),
    [sym_dictionary] = STATE(16),
    [sym_data_literal] = STATE(16),
    [aux_sym_instruction_repeat1] = STATE(7),
    [sym_identifier] = ACTIONS(17),
    [sym_stack_element] = ACTIONS(47),
    [sym_control_register] = ACTIONS(47),
    [anon_sym_LBRACE] = ACTIONS(49),
    [anon_sym_RBRACE] = ACTIONS(15),
    [anon_sym_LBRACK] = ACTIONS(51),
    [sym_hex_literal] = ACTIONS(53),
    [sym_bin_literal] = ACTIONS(53),
    [sym_boc_literal] = ACTIONS(53),
    [sym_string_literal] = ACTIONS(53),
    [sym_integer_literal] = ACTIONS(47),
    [sym_kw_ref] = ACTIONS(15),
    [sym_kw_embed] = ACTIONS(15),
    [sym_kw_exotic] = ACTIONS(15),
    [sym_comment] = ACTIONS(3),
  },
  [STATE(6)] = {
    [sym_argument] = STATE(15),
    [sym_code] = STATE(16),
    [sym_dictionary] = STATE(16),
    [sym_data_literal] = STATE(16),
    [aux_sym_instruction_repeat1] = STATE(6),
    [sym_identifier] = ACTIONS(33),
    [sym_stack_element] = ACTIONS(55),
    [sym_control_register] = ACTIONS(55),
    [anon_sym_LBRACE] = ACTIONS(58),
    [anon_sym_RBRACE] = ACTIONS(31),
    [anon_sym_LBRACK] = ACTIONS(61),
    [sym_hex_literal] = ACTIONS(64),
    [sym_bin_literal] = ACTIONS(64),
    [sym_boc_literal] = ACTIONS(64),
    [sym_string_literal] = ACTIONS(64),
    [sym_integer_literal] = ACTIONS(55),
    [sym_kw_ref] = ACTIONS(31),
    [sym_kw_embed] = ACTIONS(31),
    [sym_kw_exotic] = ACTIONS(31),
    [sym_comment] = ACTIONS(3),
  },
  [STATE(7)] = {
    [sym_argument] = STATE(15),
    [sym_code] = STATE(16),
    [sym_dictionary] = STATE(16),
    [sym_data_literal] = STATE(16),
    [aux_sym_instruction_repeat1] = STATE(6),
    [sym_identifier] = ACTIONS(29),
    [sym_stack_element] = ACTIONS(47),
    [sym_control_register] = ACTIONS(47),
    [anon_sym_LBRACE] = ACTIONS(49),
    [anon_sym_RBRACE] = ACTIONS(27),
    [anon_sym_LBRACK] = ACTIONS(51),
    [sym_hex_literal] = ACTIONS(53),
    [sym_bin_literal] = ACTIONS(53),
    [sym_boc_literal] = ACTIONS(53),
    [sym_string_literal] = ACTIONS(53),
    [sym_integer_literal] = ACTIONS(47),
    [sym_kw_ref] = ACTIONS(27),
    [sym_kw_embed] = ACTIONS(27),
    [sym_kw_exotic] = ACTIONS(27),
    [sym_comment] = ACTIONS(3),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(69), 1,
      sym_identifier,
    ACTIONS(67), 14,
      ts_builtin_sym_end,
      sym_stack_element,
      sym_control_register,
      anon_sym_LBRACE,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      sym_hex_literal,
      sym_bin_literal,
      sym_boc_literal,
      sym_string_literal,
      sym_integer_literal,
      sym_kw_ref,
      sym_kw_embed,
      sym_kw_exotic,
  [23] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(73), 1,
      sym_identifier,
    ACTIONS(71), 14,
      ts_builtin_sym_end,
      sym_stack_element,
      sym_control_register,
      anon_sym_LBRACE,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      sym_hex_literal,
      sym_bin_literal,
      sym_boc_literal,
      sym_string_literal,
      sym_integer_literal,
      sym_kw_ref,
      sym_kw_embed,
      sym_kw_exotic,
  [46] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(77), 1,
      sym_identifier,
    ACTIONS(75), 13,
      ts_builtin_sym_end,
      sym_stack_element,
      sym_control_register,
      anon_sym_LBRACE,
      anon_sym_LBRACK,
      sym_hex_literal,
      sym_bin_literal,
      sym_boc_literal,
      sym_string_literal,
      sym_integer_literal,
      sym_kw_ref,
      sym_kw_embed,
      sym_kw_exotic,
  [68] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(81), 1,
      sym_identifier,
    ACTIONS(79), 13,
      ts_builtin_sym_end,
      sym_stack_element,
      sym_control_register,
      anon_sym_LBRACE,
      anon_sym_LBRACK,
      sym_hex_literal,
      sym_bin_literal,
      sym_boc_literal,
      sym_string_literal,
      sym_integer_literal,
      sym_kw_ref,
      sym_kw_embed,
      sym_kw_exotic,
  [90] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(85), 1,
      sym_identifier,
    ACTIONS(83), 13,
      ts_builtin_sym_end,
      sym_stack_element,
      sym_control_register,
      anon_sym_LBRACE,
      anon_sym_LBRACK,
      sym_hex_literal,
      sym_bin_literal,
      sym_boc_literal,
      sym_string_literal,
      sym_integer_literal,
      sym_kw_ref,
      sym_kw_embed,
      sym_kw_exotic,
  [112] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(89), 1,
      sym_identifier,
    ACTIONS(87), 13,
      ts_builtin_sym_end,
      sym_stack_element,
      sym_control_register,
      anon_sym_LBRACE,
      anon_sym_LBRACK,
      sym_hex_literal,
      sym_bin_literal,
      sym_boc_literal,
      sym_string_literal,
      sym_integer_literal,
      sym_kw_ref,
      sym_kw_embed,
      sym_kw_exotic,
  [134] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(93), 1,
      sym_identifier,
    ACTIONS(91), 13,
      ts_builtin_sym_end,
      sym_stack_element,
      sym_control_register,
      anon_sym_LBRACE,
      anon_sym_LBRACK,
      sym_hex_literal,
      sym_bin_literal,
      sym_boc_literal,
      sym_string_literal,
      sym_integer_literal,
      sym_kw_ref,
      sym_kw_embed,
      sym_kw_exotic,
  [156] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(77), 1,
      sym_identifier,
    ACTIONS(75), 13,
      sym_stack_element,
      sym_control_register,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_LBRACK,
      sym_hex_literal,
      sym_bin_literal,
      sym_boc_literal,
      sym_string_literal,
      sym_integer_literal,
      sym_kw_ref,
      sym_kw_embed,
      sym_kw_exotic,
  [178] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(89), 1,
      sym_identifier,
    ACTIONS(87), 13,
      sym_stack_element,
      sym_control_register,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_LBRACK,
      sym_hex_literal,
      sym_bin_literal,
      sym_boc_literal,
      sym_string_literal,
      sym_integer_literal,
      sym_kw_ref,
      sym_kw_embed,
      sym_kw_exotic,
  [200] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(85), 1,
      sym_identifier,
    ACTIONS(83), 13,
      sym_stack_element,
      sym_control_register,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_LBRACK,
      sym_hex_literal,
      sym_bin_literal,
      sym_boc_literal,
      sym_string_literal,
      sym_integer_literal,
      sym_kw_ref,
      sym_kw_embed,
      sym_kw_exotic,
  [222] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(69), 1,
      sym_identifier,
    ACTIONS(67), 13,
      sym_stack_element,
      sym_control_register,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_LBRACK,
      sym_hex_literal,
      sym_bin_literal,
      sym_boc_literal,
      sym_string_literal,
      sym_integer_literal,
      sym_kw_ref,
      sym_kw_embed,
      sym_kw_exotic,
  [244] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(93), 1,
      sym_identifier,
    ACTIONS(91), 13,
      sym_stack_element,
      sym_control_register,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_LBRACK,
      sym_hex_literal,
      sym_bin_literal,
      sym_boc_literal,
      sym_string_literal,
      sym_integer_literal,
      sym_kw_ref,
      sym_kw_embed,
      sym_kw_exotic,
  [266] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(81), 1,
      sym_identifier,
    ACTIONS(79), 13,
      sym_stack_element,
      sym_control_register,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_LBRACK,
      sym_hex_literal,
      sym_bin_literal,
      sym_boc_literal,
      sym_string_literal,
      sym_integer_literal,
      sym_kw_ref,
      sym_kw_embed,
      sym_kw_exotic,
  [288] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(73), 1,
      sym_identifier,
    ACTIONS(71), 13,
      sym_stack_element,
      sym_control_register,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_LBRACK,
      sym_hex_literal,
      sym_bin_literal,
      sym_boc_literal,
      sym_string_literal,
      sym_integer_literal,
      sym_kw_ref,
      sym_kw_embed,
      sym_kw_exotic,
  [310] = 8,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(95), 1,
      sym_identifier,
    ACTIONS(97), 1,
      anon_sym_RBRACE,
    ACTIONS(99), 1,
      sym_kw_ref,
    ACTIONS(101), 1,
      sym_kw_embed,
    ACTIONS(103), 1,
      sym_kw_exotic,
    STATE(66), 1,
      sym_instructions,
    STATE(28), 5,
      sym_instruction,
      sym_explicit_ref,
      sym_embed_slice,
      sym_exotic,
      aux_sym_instructions_repeat1,
  [339] = 8,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(95), 1,
      sym_identifier,
    ACTIONS(99), 1,
      sym_kw_ref,
    ACTIONS(101), 1,
      sym_kw_embed,
    ACTIONS(103), 1,
      sym_kw_exotic,
    ACTIONS(105), 1,
      anon_sym_RBRACE,
    STATE(64), 1,
      sym_instructions,
    STATE(28), 5,
      sym_instruction,
      sym_explicit_ref,
      sym_embed_slice,
      sym_exotic,
      aux_sym_instructions_repeat1,
  [368] = 8,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(95), 1,
      sym_identifier,
    ACTIONS(99), 1,
      sym_kw_ref,
    ACTIONS(101), 1,
      sym_kw_embed,
    ACTIONS(103), 1,
      sym_kw_exotic,
    ACTIONS(107), 1,
      anon_sym_RBRACE,
    STATE(67), 1,
      sym_instructions,
    STATE(28), 5,
      sym_instruction,
      sym_explicit_ref,
      sym_embed_slice,
      sym_exotic,
      aux_sym_instructions_repeat1,
  [397] = 8,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(95), 1,
      sym_identifier,
    ACTIONS(99), 1,
      sym_kw_ref,
    ACTIONS(101), 1,
      sym_kw_embed,
    ACTIONS(103), 1,
      sym_kw_exotic,
    ACTIONS(109), 1,
      anon_sym_RBRACE,
    STATE(68), 1,
      sym_instructions,
    STATE(28), 5,
      sym_instruction,
      sym_explicit_ref,
      sym_embed_slice,
      sym_exotic,
      aux_sym_instructions_repeat1,
  [426] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(111), 1,
      ts_builtin_sym_end,
    ACTIONS(113), 1,
      sym_identifier,
    ACTIONS(116), 1,
      sym_kw_ref,
    ACTIONS(119), 1,
      sym_kw_embed,
    ACTIONS(122), 1,
      sym_kw_exotic,
    STATE(26), 5,
      sym_instruction,
      sym_explicit_ref,
      sym_embed_slice,
      sym_exotic,
      aux_sym_instructions_repeat1,
  [452] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(7), 1,
      sym_identifier,
    ACTIONS(9), 1,
      sym_kw_ref,
    ACTIONS(11), 1,
      sym_kw_embed,
    ACTIONS(13), 1,
      sym_kw_exotic,
    ACTIONS(125), 1,
      ts_builtin_sym_end,
    STATE(26), 5,
      sym_instruction,
      sym_explicit_ref,
      sym_embed_slice,
      sym_exotic,
      aux_sym_instructions_repeat1,
  [478] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(95), 1,
      sym_identifier,
    ACTIONS(99), 1,
      sym_kw_ref,
    ACTIONS(101), 1,
      sym_kw_embed,
    ACTIONS(103), 1,
      sym_kw_exotic,
    ACTIONS(125), 1,
      anon_sym_RBRACE,
    STATE(29), 5,
      sym_instruction,
      sym_explicit_ref,
      sym_embed_slice,
      sym_exotic,
      aux_sym_instructions_repeat1,
  [504] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(111), 1,
      anon_sym_RBRACE,
    ACTIONS(127), 1,
      sym_identifier,
    ACTIONS(130), 1,
      sym_kw_ref,
    ACTIONS(133), 1,
      sym_kw_embed,
    ACTIONS(136), 1,
      sym_kw_exotic,
    STATE(29), 5,
      sym_instruction,
      sym_explicit_ref,
      sym_embed_slice,
      sym_exotic,
      aux_sym_instructions_repeat1,
  [530] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(141), 1,
      sym_kw_library,
    STATE(37), 1,
      sym_data_literal,
    STATE(35), 2,
      sym_exotic_library,
      sym_default_exotic,
    ACTIONS(139), 4,
      sym_hex_literal,
      sym_bin_literal,
      sym_boc_literal,
      sym_string_literal,
  [550] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(145), 1,
      sym_kw_library,
    STATE(41), 1,
      sym_data_literal,
    STATE(40), 2,
      sym_exotic_library,
      sym_default_exotic,
    ACTIONS(143), 4,
      sym_hex_literal,
      sym_bin_literal,
      sym_boc_literal,
      sym_string_literal,
  [570] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(73), 1,
      sym_identifier,
    ACTIONS(71), 4,
      anon_sym_RBRACE,
      sym_kw_ref,
      sym_kw_embed,
      sym_kw_exotic,
  [583] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(149), 1,
      sym_identifier,
    ACTIONS(147), 4,
      ts_builtin_sym_end,
      sym_kw_ref,
      sym_kw_embed,
      sym_kw_exotic,
  [596] = 3,
    ACTIONS(3), 1,
      sym_comment,
    STATE(48), 1,
      sym_data_literal,
    ACTIONS(139), 4,
      sym_hex_literal,
      sym_bin_literal,
      sym_boc_literal,
      sym_string_literal,
  [609] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(153), 1,
      sym_identifier,
    ACTIONS(151), 4,
      ts_builtin_sym_end,
      sym_kw_ref,
      sym_kw_embed,
      sym_kw_exotic,
  [622] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(81), 1,
      sym_identifier,
    ACTIONS(79), 4,
      ts_builtin_sym_end,
      sym_kw_ref,
      sym_kw_embed,
      sym_kw_exotic,
  [635] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(157), 1,
      sym_identifier,
    ACTIONS(155), 4,
      ts_builtin_sym_end,
      sym_kw_ref,
      sym_kw_embed,
      sym_kw_exotic,
  [648] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(159), 1,
      sym_identifier,
    ACTIONS(161), 4,
      anon_sym_RBRACE,
      sym_kw_ref,
      sym_kw_embed,
      sym_kw_exotic,
  [661] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(149), 1,
      sym_identifier,
    ACTIONS(147), 4,
      anon_sym_RBRACE,
      sym_kw_ref,
      sym_kw_embed,
      sym_kw_exotic,
  [674] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(153), 1,
      sym_identifier,
    ACTIONS(151), 4,
      anon_sym_RBRACE,
      sym_kw_ref,
      sym_kw_embed,
      sym_kw_exotic,
  [687] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(157), 1,
      sym_identifier,
    ACTIONS(155), 4,
      anon_sym_RBRACE,
      sym_kw_ref,
      sym_kw_embed,
      sym_kw_exotic,
  [700] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(69), 1,
      sym_identifier,
    ACTIONS(67), 4,
      ts_builtin_sym_end,
      sym_kw_ref,
      sym_kw_embed,
      sym_kw_exotic,
  [713] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(163), 1,
      sym_identifier,
    ACTIONS(165), 4,
      anon_sym_RBRACE,
      sym_kw_ref,
      sym_kw_embed,
      sym_kw_exotic,
  [726] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(73), 1,
      sym_identifier,
    ACTIONS(71), 4,
      ts_builtin_sym_end,
      sym_kw_ref,
      sym_kw_embed,
      sym_kw_exotic,
  [739] = 3,
    ACTIONS(3), 1,
      sym_comment,
    STATE(33), 1,
      sym_data_literal,
    ACTIONS(139), 4,
      sym_hex_literal,
      sym_bin_literal,
      sym_boc_literal,
      sym_string_literal,
  [752] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(81), 1,
      sym_identifier,
    ACTIONS(79), 4,
      anon_sym_RBRACE,
      sym_kw_ref,
      sym_kw_embed,
      sym_kw_exotic,
  [765] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(69), 1,
      sym_identifier,
    ACTIONS(67), 4,
      anon_sym_RBRACE,
      sym_kw_ref,
      sym_kw_embed,
      sym_kw_exotic,
  [778] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(163), 1,
      sym_identifier,
    ACTIONS(165), 4,
      ts_builtin_sym_end,
      sym_kw_ref,
      sym_kw_embed,
      sym_kw_exotic,
  [791] = 3,
    ACTIONS(3), 1,
      sym_comment,
    STATE(39), 1,
      sym_data_literal,
    ACTIONS(143), 4,
      sym_hex_literal,
      sym_bin_literal,
      sym_boc_literal,
      sym_string_literal,
  [804] = 3,
    ACTIONS(3), 1,
      sym_comment,
    STATE(43), 1,
      sym_data_literal,
    ACTIONS(143), 4,
      sym_hex_literal,
      sym_bin_literal,
      sym_boc_literal,
      sym_string_literal,
  [817] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(159), 1,
      sym_identifier,
    ACTIONS(161), 4,
      ts_builtin_sym_end,
      sym_kw_ref,
      sym_kw_embed,
      sym_kw_exotic,
  [830] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(167), 1,
      anon_sym_RBRACK,
    ACTIONS(169), 1,
      sym_integer_literal,
    STATE(55), 1,
      aux_sym_dictionary_repeat1,
    STATE(61), 1,
      sym_dictionary_entry,
  [846] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(169), 1,
      sym_integer_literal,
    ACTIONS(171), 1,
      anon_sym_RBRACK,
    STATE(56), 1,
      aux_sym_dictionary_repeat1,
    STATE(61), 1,
      sym_dictionary_entry,
  [862] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(169), 1,
      sym_integer_literal,
    ACTIONS(173), 1,
      anon_sym_RBRACK,
    STATE(53), 1,
      aux_sym_dictionary_repeat1,
    STATE(61), 1,
      sym_dictionary_entry,
  [878] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(169), 1,
      sym_integer_literal,
    ACTIONS(175), 1,
      anon_sym_RBRACK,
    STATE(56), 1,
      aux_sym_dictionary_repeat1,
    STATE(61), 1,
      sym_dictionary_entry,
  [894] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(177), 1,
      anon_sym_RBRACK,
    ACTIONS(179), 1,
      sym_integer_literal,
    STATE(56), 1,
      aux_sym_dictionary_repeat1,
    STATE(61), 1,
      sym_dictionary_entry,
  [910] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(21), 1,
      anon_sym_LBRACE,
    STATE(60), 1,
      sym_code,
  [920] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(182), 1,
      anon_sym_LBRACE,
    STATE(38), 1,
      sym_code,
  [930] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(184), 1,
      anon_sym_LBRACE,
    STATE(51), 1,
      sym_code,
  [940] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(186), 2,
      anon_sym_RBRACK,
      sym_integer_literal,
  [948] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(188), 2,
      anon_sym_RBRACK,
      sym_integer_literal,
  [956] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(190), 1,
      ts_builtin_sym_end,
  [963] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(192), 1,
      ts_builtin_sym_end,
  [970] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(194), 1,
      anon_sym_RBRACE,
  [977] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(196), 1,
      anon_sym_EQ_GT,
  [984] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(198), 1,
      anon_sym_RBRACE,
  [991] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(200), 1,
      anon_sym_RBRACE,
  [998] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(202), 1,
      anon_sym_RBRACE,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(8)] = 0,
  [SMALL_STATE(9)] = 23,
  [SMALL_STATE(10)] = 46,
  [SMALL_STATE(11)] = 68,
  [SMALL_STATE(12)] = 90,
  [SMALL_STATE(13)] = 112,
  [SMALL_STATE(14)] = 134,
  [SMALL_STATE(15)] = 156,
  [SMALL_STATE(16)] = 178,
  [SMALL_STATE(17)] = 200,
  [SMALL_STATE(18)] = 222,
  [SMALL_STATE(19)] = 244,
  [SMALL_STATE(20)] = 266,
  [SMALL_STATE(21)] = 288,
  [SMALL_STATE(22)] = 310,
  [SMALL_STATE(23)] = 339,
  [SMALL_STATE(24)] = 368,
  [SMALL_STATE(25)] = 397,
  [SMALL_STATE(26)] = 426,
  [SMALL_STATE(27)] = 452,
  [SMALL_STATE(28)] = 478,
  [SMALL_STATE(29)] = 504,
  [SMALL_STATE(30)] = 530,
  [SMALL_STATE(31)] = 550,
  [SMALL_STATE(32)] = 570,
  [SMALL_STATE(33)] = 583,
  [SMALL_STATE(34)] = 596,
  [SMALL_STATE(35)] = 609,
  [SMALL_STATE(36)] = 622,
  [SMALL_STATE(37)] = 635,
  [SMALL_STATE(38)] = 648,
  [SMALL_STATE(39)] = 661,
  [SMALL_STATE(40)] = 674,
  [SMALL_STATE(41)] = 687,
  [SMALL_STATE(42)] = 700,
  [SMALL_STATE(43)] = 713,
  [SMALL_STATE(44)] = 726,
  [SMALL_STATE(45)] = 739,
  [SMALL_STATE(46)] = 752,
  [SMALL_STATE(47)] = 765,
  [SMALL_STATE(48)] = 778,
  [SMALL_STATE(49)] = 791,
  [SMALL_STATE(50)] = 804,
  [SMALL_STATE(51)] = 817,
  [SMALL_STATE(52)] = 830,
  [SMALL_STATE(53)] = 846,
  [SMALL_STATE(54)] = 862,
  [SMALL_STATE(55)] = 878,
  [SMALL_STATE(56)] = 894,
  [SMALL_STATE(57)] = 910,
  [SMALL_STATE(58)] = 920,
  [SMALL_STATE(59)] = 930,
  [SMALL_STATE(60)] = 940,
  [SMALL_STATE(61)] = 948,
  [SMALL_STATE(62)] = 956,
  [SMALL_STATE(63)] = 963,
  [SMALL_STATE(64)] = 970,
  [SMALL_STATE(65)] = 977,
  [SMALL_STATE(66)] = 984,
  [SMALL_STATE(67)] = 991,
  [SMALL_STATE(68)] = 998,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT_EXTRA(),
  [5] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [7] = {.entry = {.count = 1, .reusable = false}}, SHIFT(2),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(59),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(45),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [15] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_instruction, 1, 0, 1),
  [17] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_instruction, 1, 0, 1),
  [19] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [21] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [23] = {.entry = {.count = 1, .reusable = true}}, SHIFT(54),
  [25] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [27] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_instruction, 2, 0, 3),
  [29] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_instruction, 2, 0, 3),
  [31] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_instruction_repeat1, 2, 0, 9),
  [33] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_instruction_repeat1, 2, 0, 9),
  [35] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_instruction_repeat1, 2, 0, 9), SHIFT_REPEAT(13),
  [38] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_instruction_repeat1, 2, 0, 9), SHIFT_REPEAT(22),
  [41] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_instruction_repeat1, 2, 0, 9), SHIFT_REPEAT(54),
  [44] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_instruction_repeat1, 2, 0, 9), SHIFT_REPEAT(11),
  [47] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [49] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [51] = {.entry = {.count = 1, .reusable = true}}, SHIFT(52),
  [53] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [55] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_instruction_repeat1, 2, 0, 9), SHIFT_REPEAT(16),
  [58] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_instruction_repeat1, 2, 0, 9), SHIFT_REPEAT(24),
  [61] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_instruction_repeat1, 2, 0, 9), SHIFT_REPEAT(52),
  [64] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_instruction_repeat1, 2, 0, 9), SHIFT_REPEAT(20),
  [67] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_code, 2, 0, 0),
  [69] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_code, 2, 0, 0),
  [71] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_code, 3, 0, 10),
  [73] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_code, 3, 0, 10),
  [75] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_instruction_repeat1, 1, 0, 2),
  [77] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_instruction_repeat1, 1, 0, 2),
  [79] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_data_literal, 1, 0, 0),
  [81] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_data_literal, 1, 0, 0),
  [83] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_dictionary, 2, 0, 0),
  [85] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_dictionary, 2, 0, 0),
  [87] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_argument, 1, 0, 0),
  [89] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_argument, 1, 0, 0),
  [91] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_dictionary, 3, 0, 11),
  [93] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_dictionary, 3, 0, 11),
  [95] = {.entry = {.count = 1, .reusable = false}}, SHIFT(5),
  [97] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [99] = {.entry = {.count = 1, .reusable = true}}, SHIFT(58),
  [101] = {.entry = {.count = 1, .reusable = true}}, SHIFT(49),
  [103] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [105] = {.entry = {.count = 1, .reusable = true}}, SHIFT(42),
  [107] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [109] = {.entry = {.count = 1, .reusable = true}}, SHIFT(47),
  [111] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_instructions_repeat1, 2, 0, 0),
  [113] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_instructions_repeat1, 2, 0, 0), SHIFT_REPEAT(2),
  [116] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_instructions_repeat1, 2, 0, 0), SHIFT_REPEAT(59),
  [119] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_instructions_repeat1, 2, 0, 0), SHIFT_REPEAT(45),
  [122] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_instructions_repeat1, 2, 0, 0), SHIFT_REPEAT(30),
  [125] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_instructions, 1, 0, 0),
  [127] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_instructions_repeat1, 2, 0, 0), SHIFT_REPEAT(5),
  [130] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_instructions_repeat1, 2, 0, 0), SHIFT_REPEAT(58),
  [133] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_instructions_repeat1, 2, 0, 0), SHIFT_REPEAT(49),
  [136] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_instructions_repeat1, 2, 0, 0), SHIFT_REPEAT(31),
  [139] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
  [141] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [143] = {.entry = {.count = 1, .reusable = true}}, SHIFT(46),
  [145] = {.entry = {.count = 1, .reusable = true}}, SHIFT(50),
  [147] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_embed_slice, 2, 0, 5),
  [149] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_embed_slice, 2, 0, 5),
  [151] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_exotic, 2, 0, 6),
  [153] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_exotic, 2, 0, 6),
  [155] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_default_exotic, 1, 0, 7),
  [157] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_default_exotic, 1, 0, 7),
  [159] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_explicit_ref, 2, 0, 4),
  [161] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_explicit_ref, 2, 0, 4),
  [163] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_exotic_library, 2, 0, 5),
  [165] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_exotic_library, 2, 0, 5),
  [167] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [169] = {.entry = {.count = 1, .reusable = true}}, SHIFT(65),
  [171] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [173] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [175] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [177] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_dictionary_repeat1, 2, 0, 12),
  [179] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_dictionary_repeat1, 2, 0, 12), SHIFT_REPEAT(65),
  [182] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [184] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [186] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_dictionary_entry, 3, 0, 13),
  [188] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_dictionary_repeat1, 1, 0, 8),
  [190] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [192] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [194] = {.entry = {.count = 1, .reusable = true}}, SHIFT(44),
  [196] = {.entry = {.count = 1, .reusable = true}}, SHIFT(57),
  [198] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [200] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [202] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_tasm(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .keyword_lex_fn = ts_lex_keywords,
    .keyword_capture_token = sym_identifier,
    .primary_state_ids = ts_primary_state_ids,
    .name = "tasm",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
