[package]
name = "localton"
description = "A complete headless local TON development network"
version = { workspace = true }
publish = false
authors = { workspace = true }
edition = { workspace = true }
rust-version = { workspace = true }
repository = { workspace = true }
license = { workspace = true }

[workspace]
members = ["xtask"]

[workspace.package]
version = "0.1.0"
authors = ["TON Core"]
edition = "2024"
rust-version = "1.97.1"
repository = "https://github.com/ton-blockchain/acton"
license = "MIT OR Apache-2.0"

[dependencies]
anyhow = "1.0"
async-trait = "0.1.89"
axum = { version = "0.8", features = ["json", "query", "tokio", "http1"] }
base64 = "0.22"
clap = { version = "4.5", features = ["derive", "env"] }
crc = "3.3"
dunce = "1.0.5"
ed25519-dalek = "2.2"
fastnum = "0.7.5"
fs2 = "0.4"
futures-util = "0.3"
hex = "0.4"
include_dir = "0.7"
indicatif = "0.18.3"
nix = { version = "0.30", features = ["process", "signal"] }
num-bigint = "0.4"
rand = "0.8"
regex = "1.11"
reqwest = { version = "0.12", default-features = false, features = ["json", "rustls-tls", "stream"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
sha2 = "0.10"
tokio = { version = "1.47", features = ["fs", "io-util", "macros", "net", "process", "rt-multi-thread", "signal", "sync", "time"] }
ton = "0.4.1"
tonutils = { version = "1.1.0", features = ["full"] }
tower-http = { version = "0.6", features = ["fs"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter", "fmt"] }
tycho-types = { version = "0.3.5", default-features = false, features = ["models"] }
utoipa = { version = "5.5", features = ["axum_extras", "macros"] }
zip = { version = "4.6", default-features = false, features = ["deflate"] }

[dev-dependencies]
expect-test = "1.5.0"
tempfile = "3.20"

[profile.release]
strip = true
lto = "thin"
