all: precommit

build:
    cargo build --release --workspace --locked

build-dev:
    cargo build --workspace --locked

build-ci: build

fmt:
    cargo fmt --all

fmt-check:
    cargo fmt --all --check

clippy:
    cargo clippy --workspace --all-targets --locked -- -D warnings

test:
    cargo test --workspace --all-targets --locked

doc:
    RUSTDOCFLAGS="-D warnings" cargo doc --workspace --no-deps --locked

check-ci: fmt-check clippy doc

check: check-ci test

precommit: fmt build check

run:
    cargo run --locked

clean:
    cargo clean
