*

!Cargo.toml
!build.rs
!src/
!crates/
crates/**/target/
!xtask/

!apps/
apps/*
!apps/actonscan-backend/
apps/actonscan-backend/*
!apps/actonscan-backend/Cargo.toml
!apps/actonscan-backend/Cargo.lock
!apps/actonscan-backend/rust-toolchain.toml
!apps/actonscan-backend/src/
!apps/actonscan-backend/docker/
apps/actonscan-backend/docker/*
!apps/actonscan-backend/docker/config.toml
