use acton_mdman::{Format, ManMap, convert};
use anyhow::{Context, Result};
use std::fs;
use std::path::Path;

use super::command_manuals::{COMMAND_MANUAL_SOURCE_DIR, COMMAND_MANUALS, CommandManualSpec};

const GENERATED_NOTICE: &str =
    "{/* This file is generated by `acton docgen`. Do not edit directly. */}\n\n";

pub(super) fn generate_command_manual_docs(command_docs_out_dir: &Path) -> Result<()> {
    fs::create_dir_all(command_docs_out_dir)?;

    for spec in COMMAND_MANUALS {
        generate_single_command_manual_doc(spec, command_docs_out_dir)?;
    }

    Ok(())
}

fn generate_single_command_manual_doc(
    spec: &CommandManualSpec,
    command_docs_out_dir: &Path,
) -> Result<()> {
    let source_path = Path::new(COMMAND_MANUAL_SOURCE_DIR).join(spec.source_name);
    let docs_body = convert(&source_path, Format::Md, None, ManMap::new())
        .with_context(|| format!("Failed to render markdown manual {}", source_path.display()))?;

    fs::write(
        command_docs_out_dir.join(format!("{}.mdx", spec.docs_slug)),
        render_docs_page(spec, &docs_body),
    )?;

    Ok(())
}

fn render_docs_page(spec: &CommandManualSpec, body: &str) -> String {
    let body = strip_leading_h1(body);
    let body = strip_leading_section(body, "NAME");
    format!(
        "---\ntitle: {:?}\ndescription: {:?}\n---\n\n{GENERATED_NOTICE}{body}",
        spec.docs_title, spec.docs_description
    )
}

fn strip_leading_h1(body: &str) -> &str {
    let Some(rest) = body.strip_prefix("# ") else {
        return body;
    };
    let Some((_, rest)) = rest.split_once('\n') else {
        return body;
    };
    rest.trim_start_matches('\n')
}

fn strip_leading_section<'a>(body: &'a str, title: &str) -> &'a str {
    let heading = format!("## {title}\n");
    let Some(rest) = body.strip_prefix(&heading) else {
        return body;
    };

    match rest.find("\n## ") {
        Some(next_section_idx) => rest[next_section_idx + 1..].trim_start_matches('\n'),
        None => "",
    }
}

#[cfg(test)]
mod tests {
    use super::{GENERATED_NOTICE, render_docs_page, strip_leading_section};
    use crate::commands::docgen::command_manuals::COMMAND_MANUALS;

    #[test]
    fn docs_page_includes_frontmatter_and_notice() {
        let spec = COMMAND_MANUALS
            .iter()
            .find(|spec| spec.command == "new")
            .expect("new command manual spec");
        let rendered = render_docs_page(
            spec,
            "# acton-new(1)\n\n## NAME\n\nacton-new --- Create a new Acton project\n\n## DESCRIPTION\n\nBody.\n",
        );
        assert!(rendered.contains("title: \"acton new\""));
        assert!(rendered.contains("description: \"Reference manual for the acton new command\""));
        assert!(rendered.contains(GENERATED_NOTICE.trim_end()));
        assert!(!rendered.contains("# acton-new(1)"));
        assert!(!rendered.contains("## NAME\n"));
        assert!(rendered.ends_with("## DESCRIPTION\n\nBody.\n"));
    }

    #[test]
    fn strip_leading_section_removes_only_the_first_matching_section() {
        let body = "## NAME\n\nIntro.\n\n## DESCRIPTION\n\nBody.\n\n## SEE ALSO\n\nMore.\n";

        assert_eq!(
            strip_leading_section(body, "NAME"),
            "## DESCRIPTION\n\nBody.\n\n## SEE ALSO\n\nMore.\n"
        );
    }
}
