use acton_mdman::{Format, ManMap, convert};
use anyhow::{Context, Result};
use std::fs;
use std::path::Path;

use super::command_manuals::{COMMAND_MANUAL_SOURCE_DIR, COMMAND_MANUALS, CommandManualSpec};
use super::generated_notice_from_path;

const DOCS_SITE_PREFIX: &str = "https://ton-blockchain.github.io/acton/docs";
const DOCS_PATH_PREFIX: &str = "/docs";

pub(super) fn generate_command_manual_docs(command_docs_out_dir: &Path) -> Result<()> {
    fs::create_dir_all(command_docs_out_dir)?;

    for spec in COMMAND_MANUALS {
        generate_single_command_manual_doc(spec, command_docs_out_dir)?;
    }

    Ok(())
}

fn generate_single_command_manual_doc(
    spec: &CommandManualSpec,
    command_docs_out_dir: &Path,
) -> Result<()> {
    let source_path = Path::new(COMMAND_MANUAL_SOURCE_DIR).join(spec.source_name);
    let docs_body = convert(&source_path, Format::Md, None, ManMap::new())
        .with_context(|| format!("Failed to render markdown manual {}", source_path.display()))?;

    fs::write(
        command_docs_out_dir.join(format!("{}.mdx", spec.docs_slug)),
        render_docs_page(spec, &source_path, &docs_body),
    )?;

    Ok(())
}

fn render_docs_page(spec: &CommandManualSpec, source_path: &Path, body: &str) -> String {
    let body = rewrite_docs_links(body);
    let body = strip_leading_h1(&body);
    let body = strip_leading_section(body, "NAME");
    let generated_notice = generated_notice_from_path(source_path);
    format!(
        "---\ntitle: {:?}\ndescription: {:?}\n---\n\n{generated_notice}{body}",
        spec.docs_title, spec.docs_description
    )
}

fn rewrite_docs_links(body: &str) -> String {
    body.replace(DOCS_SITE_PREFIX, DOCS_PATH_PREFIX)
}

fn strip_leading_h1(body: &str) -> &str {
    let Some(rest) = body.strip_prefix("# ") else {
        return body;
    };
    let Some((_, rest)) = rest.split_once('\n') else {
        return body;
    };
    rest.trim_start_matches('\n')
}

fn strip_leading_section<'a>(body: &'a str, title: &str) -> &'a str {
    let Some(rest) = body.strip_prefix("## ") else {
        return body;
    };
    let Some((heading_title, rest)) = rest.split_once('\n') else {
        return body;
    };
    if !heading_title.eq_ignore_ascii_case(title) {
        return body;
    }

    match rest.find("\n## ") {
        Some(next_section_idx) => rest[next_section_idx + 1..].trim_start_matches('\n'),
        None => "",
    }
}

#[cfg(test)]
mod tests {
    use super::{DOCS_PATH_PREFIX, render_docs_page, strip_leading_section};
    use crate::commands::docgen::command_manuals::COMMAND_MANUALS;
    use std::path::Path;

    #[test]
    fn docs_page_includes_frontmatter_and_notice() {
        let spec = COMMAND_MANUALS
            .iter()
            .find(|spec| spec.command == "new")
            .expect("new command manual spec");
        let rendered = render_docs_page(
            spec,
            Path::new("src/doc/man/acton-new.md"),
            "# acton-new(1)\n\n## NAME\n\nacton-new --- Create a new Acton project\n\n## DESCRIPTION\n\nBody.\n",
        );
        assert!(rendered.contains("title: \"acton new\""));
        assert!(rendered.contains("description: \"Reference manual for the acton new command\""));
        assert!(rendered.contains(
            "{/* @generated by `acton docgen`. Do not edit directly. */}\n{/* Source: `src/doc/man/acton-new.md` */}"
        ));
        assert!(!rendered.contains("# acton-new(1)"));
        assert!(!rendered.contains("## NAME\n"));
        assert!(rendered.ends_with("## DESCRIPTION\n\nBody.\n"));
    }

    #[test]
    fn strip_leading_section_removes_only_the_first_matching_section() {
        let body = "## NAME\n\nIntro.\n\n## DESCRIPTION\n\nBody.\n\n## SEE ALSO\n\nMore.\n";

        assert_eq!(
            strip_leading_section(body, "NAME"),
            "## DESCRIPTION\n\nBody.\n\n## SEE ALSO\n\nMore.\n"
        );
    }

    #[test]
    fn strip_leading_section_matches_case_insensitively() {
        let body = "## Name\n\nIntro.\n\n## Description\n\nBody.\n";

        assert_eq!(
            strip_leading_section(body, "NAME"),
            "## Description\n\nBody.\n"
        );
    }

    #[test]
    fn docs_page_rewrites_absolute_docs_links_to_relative_paths() {
        let spec = COMMAND_MANUALS
            .iter()
            .find(|spec| spec.command == "run")
            .expect("run command manual spec");
        let rendered = render_docs_page(
            spec,
            Path::new("src/doc/man/acton-run.md"),
            "## DESCRIPTION\n\n- [Run command guide](https://ton-blockchain.github.io/acton/docs/commands/run)\n",
        );

        assert!(rendered.contains(&format!("]({DOCS_PATH_PREFIX}/commands/run)")));
        assert!(!rendered.contains("https://ton-blockchain.github.io/acton/docs/commands/run"));
    }
}
