use acton_config::color::OwoColorize;
use anyhow::Result;
use similar::{ChangeTag, TextDiff};
use std::collections::{BTreeMap, BTreeSet};
use std::env;
use std::fs;
use std::path::{Path, PathBuf};
use tempfile::TempDir;
use walkdir::WalkDir;

mod command_manual_docs;
mod command_manuals;
mod linter;
mod stdlib;

const DEFAULT_COMMAND_DOCS_OUT: &str = "docs/content/docs/commands";
const DEFAULT_STDLIB_OUT: &str = "docs/content/docs/standard_library";
const DEFAULT_TOLK_STDLIB_OUT: &str = "docs/content/docs/tolk_standard_library";
const DEFAULT_LINTER_OUT: &str = "docs/content/docs/rules";
const DEFAULT_MAN_OUT: &str = "src/etc/man";
const DEFAULT_TERMINAL_HELP_OUT: &str = "src/doc/man/generated_txt";
const ACTON_STDLIB_SRC: &str = "lib";
const TOLK_STDLIB_SRC: &str = "crates/tolk-compiler/assets/tolk-stdlib";
const LINTER_RULES_SOURCE_DIR: &str = "crates/tolk-linter/src/rules";
const GITHUB_SOURCE_BASE: &str = "https://github.com/ton-blockchain/acton/blob/master";

#[derive(Debug, Clone)]
struct DocgenOutputPaths {
    command_docs_out_dir: PathBuf,
    stdlib_out_dir: PathBuf,
    tolk_stdlib_out_dir: PathBuf,
    linter_out_dir: PathBuf,
    man_out_dir: PathBuf,
    terminal_help_out_dir: PathBuf,
}

pub fn docgen_cmd(output: Option<String>, check: bool) -> Result<()> {
    let repo_root = resolve_docgen_repo_root()?;
    env::set_current_dir(&repo_root)?;

    let output_paths = resolve_output_paths(output);

    if check {
        let temp_out = TempDir::new()?;
        let generated_out = resolve_output_paths(Some(
            temp_out
                .path()
                .join("standard_library")
                .display()
                .to_string(),
        ));
        generate_docs(&generated_out)?;

        let changed_files = print_docgen_diff(&output_paths, &generated_out)?;
        if changed_files > 0 {
            anyhow::bail!("Documentation is out of date. Run `acton docgen` to regenerate.")
        }

        return Ok(());
    }

    generate_docs(&output_paths)
}

fn resolve_docgen_repo_root() -> Result<PathBuf> {
    let current_dir = env::current_dir()?;
    if has_docgen_inputs(&current_dir) {
        return Ok(current_dir);
    }

    let manifest_dir = PathBuf::from(env!("CARGO_MANIFEST_DIR"));
    if has_docgen_inputs(&manifest_dir) {
        return Ok(manifest_dir);
    }

    anyhow::bail!(
        "acton docgen requires the Acton source checkout. Run it from the Acton repository root, or rebuild Acton from a checkout that still exists. Missing required inputs such as '{}', '{}', and '{}'.",
        command_manuals::COMMAND_MANUAL_SOURCE_DIR,
        ACTON_STDLIB_SRC,
        TOLK_STDLIB_SRC,
    )
}

fn has_docgen_inputs(root: &Path) -> bool {
    root.join(command_manuals::COMMAND_MANUAL_SOURCE_DIR)
        .is_dir()
        && root.join(ACTON_STDLIB_SRC).is_dir()
        && root.join(TOLK_STDLIB_SRC).is_dir()
}

fn resolve_output_paths(output: Option<String>) -> DocgenOutputPaths {
    let (
        command_docs_out_dir,
        stdlib_out_dir,
        tolk_stdlib_out_dir,
        linter_out_dir,
        man_out_dir,
        terminal_help_out_dir,
    ) = if let Some(output) = output {
        let stdlib_out_dir = PathBuf::from(output);
        let base_dir = stdlib_out_dir
            .parent()
            .map_or_else(|| PathBuf::from("."), Path::to_path_buf);
        (
            base_dir.join("commands"),
            stdlib_out_dir,
            base_dir.join("tolk_standard_library"),
            base_dir.join("linting").join("rules"),
            base_dir.join("etc").join("man"),
            base_dir.join("doc").join("man").join("generated_txt"),
        )
    } else {
        (
            PathBuf::from(DEFAULT_COMMAND_DOCS_OUT),
            PathBuf::from(DEFAULT_STDLIB_OUT),
            PathBuf::from(DEFAULT_TOLK_STDLIB_OUT),
            PathBuf::from(DEFAULT_LINTER_OUT),
            PathBuf::from(DEFAULT_MAN_OUT),
            PathBuf::from(DEFAULT_TERMINAL_HELP_OUT),
        )
    };

    DocgenOutputPaths {
        command_docs_out_dir,
        stdlib_out_dir,
        tolk_stdlib_out_dir,
        linter_out_dir,
        man_out_dir,
        terminal_help_out_dir,
    }
}

fn generate_docs(output_paths: &DocgenOutputPaths) -> Result<()> {
    command_manual_docs::generate_command_manual_docs(&output_paths.command_docs_out_dir)?;
    command_manuals::generate_command_manual_artifacts(
        &output_paths.man_out_dir,
        &output_paths.terminal_help_out_dir,
    )?;
    stdlib::generate_stdlib_docs(
        Path::new(ACTON_STDLIB_SRC),
        Path::new(TOLK_STDLIB_SRC),
        &output_paths.stdlib_out_dir,
        &output_paths.tolk_stdlib_out_dir,
    )?;
    linter::generate_linter_docs(&output_paths.linter_out_dir)?;
    Ok(())
}

fn generated_notice_from_path(source_path: &Path) -> String {
    let source_path = source_path.to_string_lossy().replace('\\', "/");
    format!(
        "{{/* @generated by `acton docgen`. Do not edit directly. */}}\n{{/* Source: `{source_path}` */}}\n\n"
    )
}

fn print_docgen_diff(current: &DocgenOutputPaths, generated: &DocgenOutputPaths) -> Result<usize> {
    let mut changed_files = 0usize;
    let command_manual_paths = command_manuals::generated_output_paths();

    changed_files += print_selected_diff(
        &current.command_docs_out_dir,
        &generated.command_docs_out_dir,
        &command_manual_paths.docs,
    )?;
    changed_files += print_dir_diff(&current.stdlib_out_dir, &generated.stdlib_out_dir)?;
    changed_files += print_dir_diff(&current.tolk_stdlib_out_dir, &generated.tolk_stdlib_out_dir)?;
    changed_files += print_dir_diff(&current.linter_out_dir, &generated.linter_out_dir)?;
    changed_files += print_selected_diff(
        &current.man_out_dir,
        &generated.man_out_dir,
        &command_manual_paths.man,
    )?;
    changed_files += print_selected_diff(
        &current.terminal_help_out_dir,
        &generated.terminal_help_out_dir,
        &command_manual_paths.terminal_help,
    )?;

    Ok(changed_files)
}

fn print_dir_diff(current_dir: &Path, generated_dir: &Path) -> Result<usize> {
    let current_files = read_text_tree(current_dir)?;
    let generated_files = read_text_tree(generated_dir)?;

    let mut keys: BTreeSet<PathBuf> = current_files.keys().cloned().collect();
    keys.extend(generated_files.keys().cloned());

    let mut changed_files = 0usize;

    for relative_path in keys {
        let current_content = current_files.get(&relative_path);
        let generated_content = generated_files.get(&relative_path);

        if current_content == generated_content {
            continue;
        }

        changed_files += 1;

        let current_text = current_content.map_or("", String::as_str);
        let generated_text = generated_content.map_or("", String::as_str);
        let target = current_dir.join(&relative_path);
        eprintln!("Diff in {}:", target.display().to_string().bold());

        let diff = TextDiff::from_lines(current_text, generated_text);
        for hunk in diff.unified_diff().context_radius(3).iter_hunks() {
            for change in hunk.iter_changes() {
                let (sign, value) = match change.tag() {
                    ChangeTag::Delete => ("-".red().to_string(), change.value().red().to_string()),
                    ChangeTag::Insert => {
                        ("+".green().to_string(), change.value().green().to_string())
                    }
                    ChangeTag::Equal => (
                        " ".dimmed().to_string(),
                        change.value().dimmed().to_string(),
                    ),
                };
                eprint!("{sign}{value}");
            }
        }
        eprintln!();
    }

    Ok(changed_files)
}

fn print_selected_diff(
    current_dir: &Path,
    generated_dir: &Path,
    relative_paths: &[PathBuf],
) -> Result<usize> {
    let current_files = read_text_tree(current_dir)?;
    let generated_files = read_text_tree(generated_dir)?;

    let mut changed_files = 0usize;

    for relative_path in relative_paths {
        let current_content = current_files.get(relative_path);
        let generated_content = generated_files.get(relative_path);

        if current_content == generated_content {
            continue;
        }

        changed_files += 1;

        let current_text = current_content.map_or("", String::as_str);
        let generated_text = generated_content.map_or("", String::as_str);
        let target = current_dir.join(relative_path);
        eprintln!("Diff in {}:", target.display().to_string().bold());

        let diff = TextDiff::from_lines(current_text, generated_text);
        for hunk in diff.unified_diff().context_radius(3).iter_hunks() {
            for change in hunk.iter_changes() {
                let (sign, value) = match change.tag() {
                    ChangeTag::Delete => ("-".red().to_string(), change.value().red().to_string()),
                    ChangeTag::Insert => {
                        ("+".green().to_string(), change.value().green().to_string())
                    }
                    ChangeTag::Equal => (
                        " ".dimmed().to_string(),
                        change.value().dimmed().to_string(),
                    ),
                };
                eprint!("{sign}{value}");
            }
        }
        eprintln!();
    }

    Ok(changed_files)
}

fn read_text_tree(root: &Path) -> Result<BTreeMap<PathBuf, String>> {
    let mut files = BTreeMap::new();
    if !root.exists() {
        return Ok(files);
    }

    for entry in WalkDir::new(root)
        .into_iter()
        .filter_map(std::result::Result::ok)
    {
        if !entry.file_type().is_file() {
            continue;
        }
        let path = entry.path();
        let relative = path.strip_prefix(root)?.to_path_buf();
        let content = fs::read_to_string(path)?;
        files.insert(relative, content);
    }

    Ok(files)
}
