// Generated by scripts/generate-registry.mjs. Do not edit.

export const SUPPORTED_FUNC_VERSIONS = [
  "0.4.6-wasmfix.0",
  "0.4.6",
  "0.4.5",
  "0.4.4-newops.1",
  "0.4.4-newops",
  "0.4.4",
  "0.4.3",
  "0.4.2",
  "0.4.1",
  "0.4.0",
  "0.3.0",
  "0.2.0",
];

export const SUPPORTED_TACT_VERSIONS = [
  "1.6.13",
  "1.6.12",
  "1.6.11",
  "1.6.10",
  "1.6.7",
  "1.6.6",
  "1.6.5",
  "1.6.4",
  "1.6.3",
  "1.6.2",
  "1.5.4",
  "1.5.3",
  "1.5.2",
  "1.5.1",
  "1.5.0",
  "1.4.4",
  "1.4.3",
  "1.4.2",
  "1.4.1",
  "1.4.0",
  "1.3.1",
  "1.3.0",
  "1.2.0",
  "1.1.5",
  "1.1.4",
  "1.1.3",
  "1.1.2",
  "1.1.1",
  "1.1.0",
  "1.0.0",
];

export const SUPPORTED_TOLK_VERSIONS = [
  "1.4.2",
  "1.4.1",
  "1.4.0",
  "1.3.0",
  "1.2.0",
  "1.1.0",
  "1.0.0",
  "0.99.0",
  "0.13.0",
  "0.12.0",
  "0.11.0",
  "0.10.0",
  "0.9.0",
  "0.8.0",
  "0.7.0",
  "0.6.0",
];

const funcLoaders = {
  "0.4.6-wasmfix.0": () => import("func-0.4.6-wasmfix.0"),
  "0.4.6": () => import("func-0.4.6"),
  "0.4.5": () => import("func-0.4.5"),
  "0.4.4-newops.1": () => import("func-0.4.4-newops.1"),
  "0.4.4-newops": () => import("func-0.4.4-newops"),
  "0.4.4": () => import("func-0.4.4"),
  "0.4.3": () => import("func-0.4.3"),
  "0.4.2": () => import("func-0.4.2"),
  "0.4.1": () => import("func-0.4.1"),
  "0.4.0": () => import("func-0.4.0"),
  "0.3.0": () => import("func-0.3.0"),
  "0.2.0": () => import("func-0.2.0"),
};

const tactLoaders = {
  "1.6.13": () => import("tact-1.6.13"),
  "1.6.12": () => import("tact-1.6.12"),
  "1.6.11": () => import("tact-1.6.11"),
  "1.6.10": () => import("tact-1.6.10"),
  "1.6.7": () => import("tact-1.6.7"),
  "1.6.6": () => import("tact-1.6.6"),
  "1.6.5": () => import("tact-1.6.5"),
  "1.6.4": () => import("tact-1.6.4"),
  "1.6.3": () => import("tact-1.6.3"),
  "1.6.2": () => import("tact-1.6.2"),
  "1.5.4": () => import("tact-1.5.4"),
  "1.5.3": () => import("tact-1.5.3"),
  "1.5.2": () => import("tact-1.5.2"),
  "1.5.1": () => import("tact-1.5.1"),
  "1.5.0": () => import("tact-1.5.0"),
  "1.4.4": () => import("tact-1.4.4"),
  "1.4.3": () => import("tact-1.4.3"),
  "1.4.2": () => import("tact-1.4.2"),
  "1.4.1": () => import("tact-1.4.1"),
  "1.4.0": () => import("tact-1.4.0"),
  "1.3.1": () => import("tact-1.3.1"),
  "1.3.0": () => import("tact-1.3.0"),
  "1.2.0": () => import("tact-1.2.0"),
  "1.1.5": () => import("tact-1.1.5"),
  "1.1.4": () => import("tact-1.1.4"),
  "1.1.3": () => import("tact-1.1.3"),
  "1.1.2": () => import("tact-1.1.2"),
  "1.1.1": () => import("tact-1.1.1"),
  "1.1.0": () => import("tact-1.1.0"),
  "1.0.0": () => import("tact-1.0.0"),
};

const tolkLoaders = {
  "1.4.2": () => import("tolk-1.4.2"),
  "1.4.1": () => import("tolk-1.4.1"),
  "1.4.0": () => import("tolk-1.4.0"),
  "1.3.0": () => import("tolk-1.3.0"),
  "1.2.0": () => import("tolk-1.2.0"),
  "1.1.0": () => import("tolk-1.1.0"),
  "1.0.0": () => import("tolk-1.0.0"),
  "0.99.0": () => import("tolk-0.99.0"),
  "0.13.0": () => import("tolk-0.13.0"),
  "0.12.0": () => import("tolk-0.12.0"),
  "0.11.0": () => import("tolk-0.11.0"),
  "0.10.0": () => import("tolk-0.10.0"),
  "0.9.0": () => import("tolk-0.9.0"),
  "0.8.0": () => import("tolk-0.8.0"),
  "0.7.0": () => import("tolk-0.7.0"),
  "0.6.0": () => import("tolk-0.6.0"),
};

export async function importFunc(version) {
  return importSupported("func", version, funcLoaders, SUPPORTED_FUNC_VERSIONS);
}

export async function importTact(version) {
  return importSupported("tact", version, tactLoaders, SUPPORTED_TACT_VERSIONS);
}

export async function importTolk(version) {
  return importSupported("tolk", version, tolkLoaders, SUPPORTED_TOLK_VERSIONS);
}

async function importSupported(language, version, loaders, supportedVersions) {
  const loader = loaders[version];
  if (!loader) {
    throw new Error(
      `unsupported ${language} compiler_version: ${version}; supported versions: ${supportedVersions.join(", ")}`,
    );
  }

  return loader();
}
