use serde::{Deserialize, Serialize};
use std::sync::Arc;
use ton_api::toncenter::v3;
use tycho_types::cell::Cell;
use tycho_types::models::{IntAddr, OutAction, StdAddr};

/// Minimal "handle" for locating a transaction on the TON blockchain.
///
/// A tuple of (lt, hash, address) is guaranteed to be unique and can be
/// passed to RPC methods such as `get_account_transactions` to retrieve
/// the full on‑chain record.
///
/// Can be obtained by [`crate::find_base_tx_by_hash`].
#[derive(Debug, Clone)]
pub struct BaseTxInfo {
    /// Logical‑time of the transaction.
    pub lt: u64,
    /// Raw 256‑bit hash of the transaction `BoC`.
    pub hash: [u8; 32],
    /// Contract address that issued / owns the transaction.
    pub address: StdAddr,
    /// Indexed shard-block locator used to load the header required for replay.
    pub block: v3::BlockId,
}

/// Detailed information about the compute phase of a transaction.
///
/// This enum captures whether the compute phase was skipped or executed,
/// along with detailed statistics like gas usage and exit codes.
///
/// # Example
///
/// ```ignore
/// match result.emulated_tx.compute_info {
///     ComputeInfo::Skipped => println!("Compute phase skipped"),
///     ComputeInfo::Success { exit_code, gas_used, .. } => {
///         println!("Exit code: {}, Gas used: {}", exit_code, gas_used);
///     }
/// }
/// ```
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(tag = "type")]
pub enum ComputeInfo {
    /// Compute phase was skipped (e.g., account is uninitialized or not enough funds for storage).
    #[serde(rename = "skipped")]
    Skipped,
    /// Compute phase was executed.
    #[serde(rename = "success")]
    Success {
        /// Whether the compute phase was successful.
        success: bool,
        /// VM exit code.
        #[serde(rename = "exitCode")]
        exit_code: i32,
        /// Number of VM steps executed.
        #[serde(rename = "vmSteps")]
        vm_steps: u32,
        /// Amount of gas used.
        #[serde(rename = "gasUsed")]
        gas_used: u64,
        /// Fees paid for gas.
        #[serde(rename = "gasFees")]
        gas_fees: u64,
    },
}

/// Contract address and incoming message details for a retraced transaction.
///
/// Tick-tock transactions have no incoming message: only `contract` is populated.
/// The transaction kind is available in [`TraceEmulatedTx::raw`].
///
/// # Example
///
/// ```ignore
/// let in_msg = &result.in_msg;
/// println!("From: {:?}, To: {:?}, Amount: {:?}", in_msg.sender, in_msg.contract, in_msg.amount);
/// ```
#[derive(Debug, Clone)]
pub struct TraceInMessage {
    /// Sender address (None for external-in and tick-tock transactions).
    pub sender: Option<IntAddr>,
    /// Address of the contract whose transaction was replayed.
    pub contract: IntAddr,
    /// Amount of nanograms sent with the message.
    pub amount: Option<u64>,
    /// Opcode extracted from the message body.
    pub opcode: Option<u32>,
}

/// Detailed information about the emulated transaction.
///
/// Contains the raw transaction object, execution timing, and full logs.
#[derive(Debug, Clone)]
pub struct TraceEmulatedTx {
    /// Emulated transaction.
    pub raw: tycho_types::models::Transaction,
    /// Unix time of the transaction execution.
    pub utime: u64,
    /// Logical‑time of the transaction.
    pub lt: u64,
    /// Information about the compute phase (gas usage, exit code, etc).
    pub compute_info: ComputeInfo,
    /// Detailed logs from the sandbox executor.
    pub executor_logs: Arc<str>,
    /// List of outgoing actions generated by the transaction.
    pub actions: Vec<OutAction>,
    /// Final state of the `c5` control register (action list cell).
    pub c5: Option<Cell>,
    /// Detailed VM execution logs.
    pub vm_logs: Arc<str>,
    /// Missing global-library hashes reported by the native emulator.
    pub missing_libraries: Vec<String>,
}

/// Breakdown of money movements and fees within the transaction.
///
/// All values are in nanograms (10^-9 GRAM).
///
/// # Example
///
/// ```ignore
/// let money = &result.money;
/// println!("Fees: {} nanograms", money.total_fees);
/// println!("Balance after: {} nanograms", money.balance_after);
/// ```
#[derive(Debug, Clone)]
pub struct TraceMoneyResult {
    /// Balance of the account **before** the transaction execution.
    pub balance_before: u64,
    /// Sum of all nanograms sent via *internal* outgoing messages.
    /// External messages are excluded as they carry no value.
    pub sent_total: u64,
    /// Total fees of the transaction (including storage, gas and action fees).
    pub total_fees: u64,
    /// Balance of the account **after** the transaction execution and fee deduction.
    pub balance_after: u64,
}

/// The final report containing all data from the transaction retrace process.
///
/// This is the primary output of the [`crate::retrace`] function.
///
/// # Example
///
/// ```ignore
/// let result = retrace(Network::Mainnet, hash, libs, &Default::default()).await?;
/// if result.state_update_hash_ok {
///     println!("Deterministic replay verified!");
/// }
/// ```
#[derive(Debug, Clone)]
pub struct TraceResult {
    /// True if the emulated state‑update hash matches the one recorded on‑chain.
    pub state_update_hash_ok: bool,
    /// The actual code cell used for execution (resolved library code if exotic).
    pub code_cell: Option<Cell>,
    /// The code cell as stored in the account state (may be an exotic library cell).
    pub original_code_cell: Option<Cell>,
    /// Contract address and message details; tick-tock has no sender, amount or opcode.
    pub in_msg: TraceInMessage,
    /// Detailed breakdown of balances and fees.
    pub money: TraceMoneyResult,
    /// Full details of the emulated transaction execution results.
    pub emulated_tx: TraceEmulatedTx,
}
