[package]
name = "ton-language-server-wasm"
version = { workspace = true }
publish = false
authors = { workspace = true }
edition = { workspace = true }
rust-version = { workspace = true }
homepage = { workspace = true }
documentation = { workspace = true }
repository = { workspace = true }
license = { workspace = true }

[lib]
crate-type = ["cdylib", "rlib"]
doctest = false

[features]
default = ["all-languages"]
all-languages = ["tlb", "tasm", "fift", "tolk"]
tlb = ["ton-language-server-core/tlb"]
tasm = ["ton-language-server-core/tasm"]
fift = ["ton-language-server-core/fift"]
tolk = ["ton-language-server-core/tolk"]

[dependencies]
console_error_panic_hook = "0.1.7"
serde = { workspace = true, features = ["derive"] }
serde-wasm-bindgen = "0.6.5"
ton-language-server-core = { path = "../ton-language-server-core", default-features = false }
tracing = { workspace = true }
tree-sitter = { workspace = true }
wasm-bindgen = { workspace = true }

[dev-dependencies]
serde_json = { workspace = true }

[lints]
workspace = true
