//! Targeted updates to configuration files generated by TON binaries.
//!
//! `dht-server` and `validator-engine` create their own JSON configuration.
//! The launcher preserves that structure and only replaces values that belong
//! to the local-network settings, currently the outbound ADNL port.

use std::{fs, path::Path};

use anyhow::{Context, Result, ensure};
use serde_json::{Value, json};

use crate::storage::write_json_atomic;

/// Replaces every generated `out_port` field without assuming config shape.
///
/// TON releases may nest this setting at different depths. Recursive replacement
/// preserves all unknown engine-owned fields and requires at least one match, so
/// an incompatible schema fails during bootstrap rather than at process startup.
pub(super) fn patch_out_port(path: &Path, out_port: u16) -> Result<()> {
    let mut value: Value = serde_json::from_slice(&fs::read(path)?)
        .with_context(|| format!("invalid JSON config {}", path.display()))?;
    let changes = replace_named_value(&mut value, "out_port", json!(out_port));
    ensure!(
        changes > 0,
        "{} contains no out_port setting",
        path.display()
    );
    write_json_atomic(path, &value)
}

/// Recursively updates a named JSON field and returns the number of replacements.
fn replace_named_value(value: &mut Value, key: &str, replacement: Value) -> usize {
    match value {
        Value::Object(object) => {
            let mut changes = 0;
            if let Some(current) = object.get_mut(key) {
                *current = replacement.clone();
                changes += 1;
            }
            changes
                + object
                    .values_mut()
                    .map(|child| replace_named_value(child, key, replacement.clone()))
                    .sum::<usize>()
        }
        Value::Array(array) => array
            .iter_mut()
            .map(|child| replace_named_value(child, key, replacement.clone()))
            .sum(),
        _ => 0,
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::storage::OUT_PORT;

    #[test]
    fn replaces_nested_out_ports() {
        let mut value = json!({
            "out_port": 1,
            "nested": [{"out_port": 2}, {"other": 3}],
        });
        assert_eq!(
            replace_named_value(&mut value, "out_port", json!(OUT_PORT)),
            2
        );
        assert_eq!(value["out_port"], json!(OUT_PORT));
        assert_eq!(value["nested"][0]["out_port"], json!(OUT_PORT));
    }
}
