//! Construction and installation of TON masterchain and basechain zerostates.
//!
//! The launcher renders the bundled Fift templates from network settings,
//! optionally inserts user-supplied `ShardAccount` values into the basechain,
//! runs `create-state`, verifies the resulting BoCs and hashes, and installs
//! the static states where validator-engine expects to find them.

use std::{fs, path::Path, time::Duration};

use anyhow::{Context, Result, ensure};
use base64::{Engine, engine::general_purpose::STANDARD as BASE64};
use sha2::{Digest, Sha256};
use tokio::process::Command;
use tracing::{info, warn};
use tycho_types::{
    boc::{Boc, BocRepr},
    models::{McStateExtra, ShardStateUnsplit},
    num::Tokens,
};

use crate::{
    binaries::TonBinaries,
    runtime::run_checked,
    storage::Layout,
    storage::NetworkSettings,
    ton::accounts::{ImportedAccount, load_cell_exact},
};

const TON_GLOBAL_VERSION: u32 = 15;
const TON_GLOBAL_CAPABILITIES: u64 = 0x3ee;

/// Produces the initial masterchain state and, when enabled, basechain state.
///
/// Zerostate is the complete blockchain state before block 1; its hashes become
/// part of the network identity in global config. With injected accounts the
/// basechain must be generated first, because the masterchain zerostate stores a
/// reference to that basechain state. Without injected accounts the bundled TON
/// script can generate both states in one pass.
pub(super) async fn create_zero_state(
    layout: &Layout,
    binaries: &TonBinaries,
    network: &NetworkSettings,
    accounts: &[ImportedAccount],
    timeout: Duration,
) -> Result<()> {
    if accounts.is_empty() {
        write_genesis_script(layout, network, false)?;
    } else {
        // `create-state` cannot add arbitrary ShardAccount values through the
        // masterchain template. Build basechain separately, then make the
        // masterchain script reference the resulting root and file hashes.
        write_basechain_script(layout, network, accounts)?;
        run_create_state_script(
            layout,
            binaries,
            &layout.smartcont.join("gen-basestate.fif"),
            "create-state basechain",
            timeout,
        )
        .await?;
        write_genesis_script(layout, network, true)?;
        info!(
            accounts = accounts.len(),
            "added accounts to basechain zerostate"
        );
    }
    // Masterchain contains global configuration and the initial validator set;
    // it is always the final state generated by this function.
    run_create_state_script(
        layout,
        binaries,
        &layout.smartcont.join("gen-zerostate.fif"),
        "create-state masterchain",
        timeout,
    )
    .await?;
    if !accounts.is_empty() {
        include_basechain_balance_in_master_state(layout, accounts)?;
    }

    // Both root hashes and serialized-file hashes are required by global config
    // and validator static storage, so missing sidecar files are fatal here.
    for name in [
        "zerostate.boc",
        "zerostate.rhash",
        "zerostate.fhash",
        "basestate0.boc",
        "basestate0.rhash",
        "basestate0.fhash",
    ] {
        ensure!(
            layout.zerostate.join(name).is_file(),
            "create-state did not produce {name}"
        );
    }
    Ok(())
}

/// Renders the masterchain Fift template for the selected network settings.
///
/// The template defines global configuration, gas/storage prices, validator and
/// election rules, Simplex timing, initial stake, and the genesis validator key.
/// When basechain was generated separately, the marked section is replaced with
/// code that loads its hashes instead of constructing it in the same process.
fn write_genesis_script(
    layout: &Layout,
    network: &NetworkSettings,
    external_basechain_state: bool,
) -> Result<()> {
    let validator_pub = layout
        .smartcont
        .join("validator-keys-1.pub")
        .to_string_lossy()
        .replace('\\', "\\\\");
    let mut script = include_str!("../../assets/gen-zerostate.fif").to_owned();
    let replacements = [
        ("GLOBAL_VERSION", TON_GLOBAL_VERSION.to_string()),
        ("GLOBAL_CAPABILITIES", TON_GLOBAL_CAPABILITIES.to_string()),
        ("GLOBAL_ID", network.global_id.to_string()),
        ("INITIAL_BALANCE", network.initial_balance.to_string()),
        ("GAS_PRICE_MC", network.gas_price_masterchain.to_string()),
        ("GAS_PRICE", network.gas_price.to_string()),
        ("CELL_PRICE_MC", network.cell_price_masterchain.to_string()),
        ("CELL_PRICE", network.cell_price.to_string()),
        ("MAX_VALIDATORS", network.max_validators.to_string()),
        (
            "MAX_MAIN_VALIDATORS",
            network.max_masterchain_validators.to_string(),
        ),
        ("MIN_VALIDATORS", network.min_validators.to_string()),
        ("MIN_STAKE", network.min_validator_stake.to_string()),
        ("MAX_STAKE", network.max_validator_stake.to_string()),
        (
            "MIN_TOTAL_STAKE",
            network.min_total_validator_stake.to_string(),
        ),
        ("MAX_FACTOR", network.max_stake_factor.to_string()),
        ("ELECTED_FOR", network.elected_for_seconds.to_string()),
        (
            "ELECTION_START_BEFORE",
            network.election_start_before_seconds.to_string(),
        ),
        (
            "ELECTION_END_BEFORE",
            network.election_end_before_seconds.to_string(),
        ),
        (
            "ELECTION_STAKE_FROZEN",
            network.stakes_frozen_for_seconds.to_string(),
        ),
        (
            "ORIGINAL_VSET_VALID_FOR",
            network.original_validator_set_valid_for_seconds.to_string(),
        ),
        (
            "SIMPLEX_TARGET_RATE_MS",
            network.simplex_target_rate_ms.to_string(),
        ),
        (
            "SIMPLEX_SLOTS_PER_LEADER_WINDOW",
            network.simplex_slots_per_leader_window.to_string(),
        ),
        (
            "SIMPLEX_FIRST_BLOCK_TIMEOUT_MS",
            network.simplex_first_block_timeout_ms.to_string(),
        ),
        (
            "SIMPLEX_MAX_LEADER_WINDOW_DESYNC",
            network.simplex_max_leader_window_desync_ms.to_string(),
        ),
    ];
    // Values are substituted into a versioned template bundled with the
    // launcher. The generated file remains available in state for inspection.
    for (placeholder, value) in replacements {
        script = script.replace(placeholder, &value);
    }
    if external_basechain_state {
        // The masterchain registers a workchain by state hashes, not by reading
        // every account again. Fift loads the two 256-bit hashes produced in the
        // preceding basechain pass.
        replace_marked_section(
            &mut script,
            "// LOCALTON_BASECHAIN_STATE_BEGIN",
            "// LOCALTON_BASECHAIN_STATE_END",
            r#"
"basestate0.fhash" file>B
dup Blen 32 <> abort"invalid basestate0 file hash"
256 B>u@ constant basestate0_fhash
"basestate0.rhash" file>B
dup Blen 32 <> abort"invalid basestate0 root hash"
256 B>u@ constant basestate0_rhash
"#,
        )?;
    }
    if !network.workchain_enabled {
        // A masterchain-only test network deliberately omits workchain 0 from
        // config even though the upstream template enables it by default.
        script = script.replace(
            "basestate0_rhash basestate0_fhash now 0 0 4 0 add-std-workchain",
            "// basic workchain disabled by settings",
        );
    }
    script = script.replace(
        "// \"path_to_genesis_pub_key\"",
        &format!("\"{validator_pub}\""),
    );
    script = script.replace("initial_stake_genesis", "1");
    ensure!(
        !script.contains("path_to_genesis_pub_key"),
        "failed to configure genesis validator public key"
    );
    fs::write(layout.smartcont.join("gen-zerostate.fif"), script)?;
    Ok(())
}

/// Renders a basechain zerostate containing the requested `ShardAccount` values.
///
/// Rust has already parsed and validated each TL-B value. Fift's `register_smc`
/// interface accepts the account's code, data, libraries, balance, address, and
/// shard-prefix metadata as separate stack values, so those components are
/// written as BoCs and referenced from generated script entries.
fn write_basechain_script(
    layout: &Layout,
    network: &NetworkSettings,
    accounts: &[ImportedAccount],
) -> Result<()> {
    let account_dir = layout.zerostate.join("accounts");
    fs::create_dir_all(&account_dir)?;
    let mut entries = String::new();

    for account in accounts {
        // Preserve the original validated ShardAccount next to its extracted
        // components. Its account ID gives every artifact a deterministic name.
        let stem = &account.account_id_hex;
        let shard_name = format!("{stem}.shard-account.boc");
        fs::write(account_dir.join(&shard_name), &account.shard_account_boc)?;

        let code_expr =
            write_optional_cell(&account_dir, stem, "code", account.code_boc.as_deref())?;
        let data_expr =
            write_optional_cell(&account_dir, stem, "data", account.data_boc.as_deref())?;
        let libraries_expr = write_optional_cell(
            &account_dir,
            stem,
            "libraries",
            account.libraries_boc.as_deref(),
        )?;

        entries.push_str(&format!(
            r#"
// {address}
{code_expr}
{data_expr}
{libraries_expr}
{balance_nano}
{fixed_prefix_length}
0
0x{account_id_hex}
6
register_smc drop
"#,
            address = account.descriptor.address,
            balance_nano = account.balance_nano,
            fixed_prefix_length = account.fixed_prefix_length,
            account_id_hex = account.account_id_hex,
        ));
    }

    let mut script = include_str!("../../assets/gen-basestate.fif").to_owned();
    script = script.replace("GLOBAL_ID", &network.global_id.to_string());
    script = script.replace("// LOCALTON_IMPORTED_ACCOUNTS", &entries);
    ensure!(
        !script.contains("LOCALTON_IMPORTED_ACCOUNTS"),
        "failed to render imported basechain accounts"
    );
    fs::write(layout.smartcont.join("gen-basestate.fif"), script)?;
    Ok(())
}

/// Writes one optional account cell and returns the Fift expression loading it.
fn write_optional_cell(
    account_dir: &Path,
    stem: &str,
    kind: &str,
    boc: Option<&[u8]>,
) -> Result<String> {
    let Some(boc) = boc else {
        return Ok("empty_cell".to_owned());
    };
    let name = format!("{stem}.{kind}.boc");
    fs::write(account_dir.join(&name), boc)?;
    Ok(format!("\"accounts/{name}\" file>B B>boc"))
}

/// Replaces a controlled template region and fails if template markers drift.
///
/// Failing loudly protects genesis semantics when the bundled upstream template
/// changes: silently appending the snippet could create a different network.
fn replace_marked_section(
    source: &mut String,
    begin_marker: &str,
    end_marker: &str,
    replacement: &str,
) -> Result<()> {
    let begin = source
        .find(begin_marker)
        .with_context(|| format!("genesis template is missing `{begin_marker}`"))?;
    let body_start = begin + begin_marker.len();
    let end = source[body_start..]
        .find(end_marker)
        .map(|offset| body_start + offset)
        .with_context(|| format!("genesis template is missing `{end_marker}`"))?;
    source.replace_range(body_start..end, &format!("\n{replacement}\n"));
    Ok(())
}

/// Adds imported basechain funds to the masterchain's global balance.
///
/// `create-state` keeps allocated balance in process memory. Basechain and
/// masterchain are produced by separate invocations, so their supplies must be
/// reconciled in the encoded masterchain state after both passes complete.
fn include_basechain_balance_in_master_state(
    layout: &Layout,
    accounts: &[ImportedAccount],
) -> Result<()> {
    // Decode through tycho TL-B types rather than changing raw cell bits. This
    // also verifies that the generated root is a masterchain ShardStateUnsplit.
    let state_path = layout.zerostate.join("zerostate.boc");
    let state_boc = fs::read(&state_path)
        .with_context(|| format!("failed to read {}", state_path.display()))?;
    let root = Boc::decode(&state_boc).context("masterchain zerostate is not a valid BoC")?;
    let mut state = load_cell_exact::<ShardStateUnsplit>(
        &root,
        "masterchain zerostate is not a valid ShardStateUnsplit",
    )?;
    ensure!(
        state.shard_ident.is_masterchain(),
        "generated zerostate is not a masterchain state"
    );

    // `McStateExtra.global_balance` represents supply allocated outside the
    // masterchain. Add exactly the balances inserted into basechain zerostate.
    let expected_global_balance = {
        let custom = state
            .custom
            .as_mut()
            .context("masterchain zerostate has no McStateExtra")?;
        let mut extra = load_cell_exact::<McStateExtra>(
            custom.inner(),
            "masterchain zerostate contains invalid McStateExtra",
        )?;
        for account in accounts {
            extra
                .global_balance
                .try_add_assign_tokens(Tokens::new(account.balance_nano))
                .with_context(|| {
                    format!(
                        "global balance overflow while adding imported account `{}`",
                        account.descriptor.address
                    )
                })?;
        }
        let expected = extra.global_balance.clone();
        custom
            .set(&extra)
            .context("failed to update masterchain global balance")?;
        expected
    };

    // Re-encode and decode once more before writing. The second decode catches
    // serialization mistakes, and the equality check guards against losing the
    // intended balance mutation while rebuilding the cell tree.
    let updated_boc =
        BocRepr::encode(&state).context("failed to encode updated masterchain zerostate")?;
    let updated_root =
        Boc::decode(&updated_boc).context("updated masterchain zerostate is not a valid BoC")?;
    let verified_state = load_cell_exact::<ShardStateUnsplit>(
        &updated_root,
        "updated masterchain zerostate is not a valid ShardStateUnsplit",
    )?;
    let verified_custom = verified_state
        .custom
        .as_ref()
        .context("updated masterchain zerostate has no McStateExtra")?;
    let verified_extra = load_cell_exact::<McStateExtra>(
        verified_custom.inner(),
        "updated masterchain zerostate contains invalid McStateExtra",
    )?;
    ensure!(
        verified_extra.global_balance == expected_global_balance,
        "updated masterchain global balance does not match imported basechain balances"
    );

    // Changing the BoC changes both its root representation hash and whole-file
    // SHA-256 hash; all three files must remain synchronized.
    fs::write(&state_path, &updated_boc)
        .with_context(|| format!("failed to write {}", state_path.display()))?;
    fs::write(
        layout.zerostate.join("zerostate.rhash"),
        updated_root.repr_hash().as_slice(),
    )?;
    fs::write(
        layout.zerostate.join("zerostate.fhash"),
        &Sha256::digest(&updated_boc)[..],
    )?;
    info!(
        accounts = accounts.len(),
        "included basechain genesis balances in masterchain global balance"
    );
    Ok(())
}

/// Executes one rendered Fift genesis script with the matching TON libraries.
///
/// `FIFTPATH` combines libraries from the selected binary release with the
/// copied smart-contract directory. Running inside `zerostate/` makes all
/// generated BoCs and hash sidecars land in the persistent state layout.
async fn run_create_state_script(
    layout: &Layout,
    binaries: &TonBinaries,
    script: &Path,
    label: &str,
    timeout: Duration,
) -> Result<()> {
    let mut command = Command::new(binaries.command("create-state"));
    command.arg(script).current_dir(&layout.zerostate).env(
        "FIFTPATH",
        std::env::join_paths([binaries.lib_dir(), layout.smartcont.clone()])?,
    );
    let output = run_checked(label, command, timeout).await?;
    if !output.stderr.trim().is_empty() {
        warn!(
            stderr = output.stderr.trim(),
            command = label,
            "create-state wrote to stderr"
        );
    }
    Ok(())
}

/// Reads a TON root/file hash sidecar and enforces its 256-bit size.
pub(super) fn read_hash(path: &Path) -> Result<Vec<u8>> {
    let bytes = fs::read(path).with_context(|| format!("failed to read {}", path.display()))?;
    ensure!(
        bytes.len() == 32,
        "{} must contain a 32-byte hash, got {}",
        path.display(),
        bytes.len()
    );
    Ok(bytes)
}

pub(super) fn read_hash_base64(path: &Path) -> Result<String> {
    Ok(BASE64.encode(read_hash(path)?))
}

/// Installs a zerostate BoC under validator-engine's content-addressed filename.
///
/// Static storage is keyed by the uppercase file hash rather than the friendly
/// source filename. validator-engine resolves the hash from global config and
/// opens this file before any block database exists.
pub(super) fn install_static_state(
    layout: &Layout,
    boc_name: &str,
    file_hash: &[u8],
) -> Result<()> {
    let static_dir = layout.validator_db.join("static");
    fs::create_dir_all(&static_dir)?;
    fs::copy(
        layout.zerostate.join(boc_name),
        static_dir.join(static_state_filename(file_hash)),
    )
    .with_context(|| format!("failed to install {boc_name} into validator static storage"))?;
    Ok(())
}

fn static_state_filename(file_hash: &[u8]) -> String {
    hex::encode_upper(file_hash)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn genesis_uses_current_ton_global_version_and_capabilities() {
        let rendered = include_str!("../../assets/gen-zerostate.fif")
            .replace("GLOBAL_VERSION", &TON_GLOBAL_VERSION.to_string())
            .replace("GLOBAL_CAPABILITIES", &TON_GLOBAL_CAPABILITIES.to_string());
        assert!(rendered.contains("15 1006 config.version!"));
    }

    #[test]
    fn static_state_filenames_match_linux_validator_lookup() {
        assert_eq!(static_state_filename(&[0xbe, 0xe3, 0xab, 0xa8]), "BEE3ABA8");
    }
}
