//! Construction and installation of TON masterchain and basechain zerostates.
//!
//! The bootstrap workflow renders the bundled Fift templates from network settings,
//! optionally inserts user-supplied `ShardAccount` values into the basechain,
//! delegates state creation to the typed TON tool boundary, and installs the
//! resulting static states where validator-engine expects to find them.

use std::{fs, path::Path, time::Instant};

use anyhow::{Context, Result, ensure};
use tracing::{info, warn};
use tycho_types::{
    boc::{Boc, BocRepr},
    models::{McStateExtra, ShardStateUnsplit},
    num::Tokens,
};

use crate::{
    storage::Layout,
    storage::NetworkSettings,
    ton::accounts::{ImportedAccount, load_cell_exact},
    ton::tools::{
        create_state::{CreateState, CreateStateRequest, ZeroStateArtifacts, ZeroStateKind},
        types::{OperationContext, TonBlockHash},
    },
};

const TON_GLOBAL_VERSION: u32 = 15;
const TON_GLOBAL_CAPABILITIES: u64 = 0x3ee;

/// Complete masterchain and basechain identities produced by genesis bootstrap.
///
/// Both artifacts have already been validated and installed into validator-engine
/// static storage. Returning them together prevents later bootstrap stages from
/// rediscovering binary-owned filenames or reconstructing hash pairs.
pub(super) struct GenesisStates {
    pub masterchain: ZeroStateArtifacts,
    pub basechain: ZeroStateArtifacts,
}

/// Produces the initial masterchain state and, when enabled, basechain state.
///
/// Zerostate is the complete blockchain state before block 1; its hashes become
/// part of the network identity in global config. With injected accounts the
/// basechain must be generated first, because the masterchain zerostate stores a
/// reference to that basechain state. Without injected accounts the bundled TON
/// script can generate both states in one pass.
///
/// The workflow receives a [`CreateState`] implementation instead of a binary
/// distribution so this module owns only genesis ordering and Localton-authored
/// files. FIFTPATH construction, process execution, and artifact parsing remain
/// inside the official adapter and can be replaced in workflow tests.
pub(super) async fn create_genesis_states(
    layout: &Layout,
    create_state: &dyn CreateState,
    context: &OperationContext,
    network: &NetworkSettings,
    accounts: &[ImportedAccount],
) -> Result<GenesisStates> {
    let started = Instant::now();
    let node = context.node_name.as_deref().unwrap_or("network");
    info!(
        workflow = "genesis_zerostate",
        stage = "started",
        %node,
        imported_accounts = accounts.len(),
        "creating TON genesis states"
    );

    let result: Result<GenesisStates> = async {
        let generated_basechain = if accounts.is_empty() {
            write_genesis_script(layout, network, false)?;
            info!(
                workflow = "genesis_zerostate",
                stage = "masterchain_script_ready",
                external_basechain = false,
                "rendered combined genesis script"
            );
            None
        } else {
            // `create-state` cannot add arbitrary ShardAccount values through the
            // masterchain template. Build basechain separately, then make the
            // masterchain script reference the resulting root and file hashes.
            write_basechain_script(layout, network, accounts)?;
            info!(
                workflow = "genesis_zerostate",
                stage = "basechain_script_ready",
                imported_accounts = accounts.len(),
                "rendered imported-account basechain script"
            );
            let basechain = create_state
                .create(
                    context,
                    CreateStateRequest {
                        kind: ZeroStateKind::Basechain,
                        script: layout.smartcont.join("gen-basestate.fif"),
                        output_dir: layout.zerostate.clone(),
                        include_paths: vec![layout.smartcont.clone()],
                    },
                )
                .await?;
            info!(
                workflow = "genesis_zerostate",
                stage = "basechain_generated",
                artifact_boc = %basechain.boc_path().display(),
                imported_accounts = accounts.len(),
                "generated imported-account basechain zerostate"
            );
            write_genesis_script(layout, network, true)?;
            info!(
                workflow = "genesis_zerostate",
                stage = "masterchain_script_ready",
                external_basechain = true,
                "rendered masterchain script referencing basechain artifacts"
            );
            Some(basechain)
        };

        // Masterchain contains global configuration and the initial validator
        // set; it is always the final state generated by this workflow.
        let masterchain = create_state
            .create(
                context,
                CreateStateRequest {
                    kind: ZeroStateKind::Masterchain,
                    script: layout.smartcont.join("gen-zerostate.fif"),
                    output_dir: layout.zerostate.clone(),
                    include_paths: vec![layout.smartcont.clone()],
                },
            )
            .await?;
        info!(
            workflow = "genesis_zerostate",
            stage = "masterchain_generated",
            artifact_boc = %masterchain.boc_path().display(),
            "generated masterchain zerostate"
        );

        let masterchain = if accounts.is_empty() {
            masterchain
        } else {
            let masterchain = include_basechain_balance_in_master_state(&masterchain, accounts)?;
            info!(
                workflow = "genesis_zerostate",
                stage = "global_balance_reconciled",
                imported_accounts = accounts.len(),
                "reconciled imported supply into masterchain state"
            );
            masterchain
        };

        // The combined upstream masterchain script emits basechain artifacts as
        // a side effect. Load that fixed output through the same typed boundary
        // instead of teaching this workflow its three filenames.
        let basechain = match generated_basechain {
            Some(basechain) => basechain,
            None => ZeroStateArtifacts::load(ZeroStateKind::Basechain, &layout.zerostate)?,
        };

        masterchain.install_for_validator_engine(&layout.node.db)?;
        basechain.install_for_validator_engine(&layout.node.db)?;
        Ok(GenesisStates {
            masterchain,
            basechain,
        })
    }
    .await;

    let duration_ms = u64::try_from(started.elapsed().as_millis()).unwrap_or(u64::MAX);
    let outcome = if result.is_ok() { "success" } else { "error" };
    match &result {
        Ok(states) => info!(
            workflow = "genesis_zerostate",
            stage = "completed",
            %node,
            duration_ms,
            outcome,
            masterchain_file_hash = %states.masterchain.id().file_hash(),
            basechain_file_hash = %states.basechain.id().file_hash(),
            "TON genesis states are ready"
        ),
        // Tool diagnostics remain in the returned error and are not copied into
        // tracing because official Fift output may contain payload material.
        Err(_) => warn!(
            workflow = "genesis_zerostate",
            stage = "failed",
            %node,
            duration_ms,
            outcome,
            "TON genesis state workflow failed"
        ),
    }
    result
}

/// Renders the masterchain Fift template for the selected network settings.
///
/// The template defines global configuration, gas/storage prices, validator and
/// election rules, Simplex timing, initial stake, and the genesis validator key.
/// When basechain was generated separately, the marked section is replaced with
/// code that loads its hashes instead of constructing it in the same process.
fn write_genesis_script(
    layout: &Layout,
    network: &NetworkSettings,
    external_basechain_state: bool,
) -> Result<()> {
    let validator_pub = layout
        .smartcont
        .join("validator-keys-1.pub")
        .to_string_lossy()
        .replace('\\', "\\\\");
    let mut script = include_str!("../../assets/gen-zerostate.fif").to_owned();
    let replacements = [
        ("GLOBAL_VERSION", TON_GLOBAL_VERSION.to_string()),
        ("GLOBAL_CAPABILITIES", TON_GLOBAL_CAPABILITIES.to_string()),
        ("GLOBAL_ID", network.global_id.to_string()),
        ("INITIAL_BALANCE", network.initial_balance.to_string()),
        ("GAS_PRICE_MC", network.gas_price_masterchain.to_string()),
        ("GAS_PRICE", network.gas_price.to_string()),
        ("CELL_PRICE_MC", network.cell_price_masterchain.to_string()),
        ("CELL_PRICE", network.cell_price.to_string()),
        ("MAX_VALIDATORS", network.max_validators.to_string()),
        (
            "MAX_MAIN_VALIDATORS",
            network.max_masterchain_validators.to_string(),
        ),
        ("MIN_VALIDATORS", network.min_validators.to_string()),
        ("MIN_STAKE", network.min_validator_stake.to_string()),
        ("MAX_STAKE", network.max_validator_stake.to_string()),
        (
            "MIN_TOTAL_STAKE",
            network.min_total_validator_stake.to_string(),
        ),
        ("MAX_FACTOR", network.max_stake_factor.to_string()),
        ("ELECTED_FOR", network.elected_for_seconds.to_string()),
        (
            "ELECTION_START_BEFORE",
            network.election_start_before_seconds.to_string(),
        ),
        (
            "ELECTION_END_BEFORE",
            network.election_end_before_seconds.to_string(),
        ),
        (
            "ELECTION_STAKE_FROZEN",
            network.stakes_frozen_for_seconds.to_string(),
        ),
        (
            "ORIGINAL_VSET_VALID_FOR",
            network.original_validator_set_valid_for_seconds.to_string(),
        ),
        (
            "SIMPLEX_TARGET_RATE_MS",
            network.simplex_target_rate_ms.to_string(),
        ),
        (
            "SIMPLEX_SLOTS_PER_LEADER_WINDOW",
            network.simplex_slots_per_leader_window.to_string(),
        ),
        (
            "SIMPLEX_FIRST_BLOCK_TIMEOUT_MS",
            network.simplex_first_block_timeout_ms.to_string(),
        ),
        (
            "SIMPLEX_MAX_LEADER_WINDOW_DESYNC",
            network.simplex_max_leader_window_desync.to_string(),
        ),
    ];
    // Values are substituted into a versioned template bundled with the
    // bootstrap workflow. The generated file remains available in state for inspection.
    for (placeholder, value) in replacements {
        script = script.replace(placeholder, &value);
    }
    if external_basechain_state {
        // The masterchain registers a workchain by state hashes, not by reading
        // every account again. Fift loads the two 256-bit hashes produced in the
        // preceding basechain pass.
        replace_marked_section(
            &mut script,
            "// LOCALTON_BASECHAIN_STATE_BEGIN",
            "// LOCALTON_BASECHAIN_STATE_END",
            r#"
"basestate0.fhash" file>B
dup Blen 32 <> abort"invalid basestate0 file hash"
256 B>u@ constant basestate0_fhash
"basestate0.rhash" file>B
dup Blen 32 <> abort"invalid basestate0 root hash"
256 B>u@ constant basestate0_rhash
"#,
        )?;
    }
    if !network.workchain_enabled {
        // A masterchain-only test network deliberately omits workchain 0 from
        // config even though the upstream template enables it by default.
        script = script.replace(
            "basestate0_rhash basestate0_fhash now 0 0 4 0 add-std-workchain",
            "// basic workchain disabled by settings",
        );
    }
    script = script.replace(
        "// \"path_to_genesis_pub_key\"",
        &format!("\"{validator_pub}\""),
    );
    script = script.replace("initial_stake_genesis", "1");
    ensure!(
        !script.contains("path_to_genesis_pub_key"),
        "failed to configure genesis validator public key"
    );
    fs::write(layout.smartcont.join("gen-zerostate.fif"), script)?;
    Ok(())
}

/// Renders a basechain zerostate containing the requested `ShardAccount` values.
///
/// Rust has already parsed and validated each TL-B value. Fift's `register_smc`
/// interface accepts the account's code, data, libraries, balance, address, and
/// shard-prefix metadata as separate stack values, so those components are
/// written as BoCs and referenced from generated script entries.
fn write_basechain_script(
    layout: &Layout,
    network: &NetworkSettings,
    accounts: &[ImportedAccount],
) -> Result<()> {
    let account_dir = layout.zerostate.join("accounts");
    fs::create_dir_all(&account_dir)?;
    let mut entries = String::new();

    for account in accounts {
        // Preserve the original validated ShardAccount next to its extracted
        // components. Its account ID gives every artifact a deterministic name.
        let stem = &account.account_id_hex;
        let shard_name = format!("{stem}.shard-account.boc");
        fs::write(account_dir.join(&shard_name), &account.shard_account_boc)?;

        let code_expr =
            write_optional_cell(&account_dir, stem, "code", account.code_boc.as_deref())?;
        let data_expr =
            write_optional_cell(&account_dir, stem, "data", account.data_boc.as_deref())?;
        let libraries_expr = write_optional_cell(
            &account_dir,
            stem,
            "libraries",
            account.libraries_boc.as_deref(),
        )?;

        entries.push_str(&format!(
            r#"
// {address}
{code_expr}
{data_expr}
{libraries_expr}
{balance_nano}
{fixed_prefix_length}
0
0x{account_id_hex}
6
register_smc drop
"#,
            address = account.descriptor.address,
            balance_nano = account.balance_nano,
            fixed_prefix_length = account.fixed_prefix_length,
            account_id_hex = account.account_id_hex,
        ));
    }

    let mut script = include_str!("../../assets/gen-basestate.fif").to_owned();
    script = script.replace("GLOBAL_ID", &network.global_id.to_string());
    script = script.replace("// LOCALTON_IMPORTED_ACCOUNTS", &entries);
    ensure!(
        !script.contains("LOCALTON_IMPORTED_ACCOUNTS"),
        "failed to render imported basechain accounts"
    );
    fs::write(layout.smartcont.join("gen-basestate.fif"), script)?;
    Ok(())
}

/// Writes one optional account cell and returns the Fift expression loading it.
fn write_optional_cell(
    account_dir: &Path,
    stem: &str,
    kind: &str,
    boc: Option<&[u8]>,
) -> Result<String> {
    let Some(boc) = boc else {
        return Ok("empty_cell".to_owned());
    };
    let name = format!("{stem}.{kind}.boc");
    fs::write(account_dir.join(&name), boc)?;
    Ok(format!("\"accounts/{name}\" file>B B>boc"))
}

/// Replaces a controlled template region and fails if template markers drift.
///
/// Failing loudly protects genesis semantics when the bundled upstream template
/// changes: silently appending the snippet could create a different network.
fn replace_marked_section(
    source: &mut String,
    begin_marker: &str,
    end_marker: &str,
    replacement: &str,
) -> Result<()> {
    let begin = source
        .find(begin_marker)
        .with_context(|| format!("genesis template is missing `{begin_marker}`"))?;
    let body_start = begin + begin_marker.len();
    let end = source[body_start..]
        .find(end_marker)
        .map(|offset| body_start + offset)
        .with_context(|| format!("genesis template is missing `{end_marker}`"))?;
    source.replace_range(body_start..end, &format!("\n{replacement}\n"));
    Ok(())
}

/// Adds imported basechain funds to the masterchain's global balance.
///
/// `create-state` keeps allocated balance in process memory. Basechain and
/// masterchain are produced by separate invocations, so their supplies must be
/// reconciled in the encoded masterchain state after both passes complete.
fn include_basechain_balance_in_master_state(
    masterchain: &ZeroStateArtifacts,
    accounts: &[ImportedAccount],
) -> Result<ZeroStateArtifacts> {
    // Decode through tycho TL-B types rather than changing raw cell bits. This
    // also verifies that the generated root is a masterchain ShardStateUnsplit.
    let state_path = masterchain.boc_path();
    let state_boc =
        fs::read(state_path).with_context(|| format!("failed to read {}", state_path.display()))?;
    let root = Boc::decode(&state_boc).context("masterchain zerostate is not a valid BoC")?;
    let mut state = load_cell_exact::<ShardStateUnsplit>(
        &root,
        "masterchain zerostate is not a valid ShardStateUnsplit",
    )?;
    ensure!(
        state.shard_ident.is_masterchain(),
        "generated zerostate is not a masterchain state"
    );

    // `McStateExtra.global_balance` represents supply allocated outside the
    // masterchain. Add exactly the balances inserted into basechain zerostate.
    let expected_global_balance = {
        let custom = state
            .custom
            .as_mut()
            .context("masterchain zerostate has no McStateExtra")?;
        let mut extra = load_cell_exact::<McStateExtra>(
            custom.inner(),
            "masterchain zerostate contains invalid McStateExtra",
        )?;
        for account in accounts {
            extra
                .global_balance
                .try_add_assign_tokens(Tokens::new(account.balance_nano))
                .with_context(|| {
                    format!(
                        "global balance overflow while adding imported account `{}`",
                        account.descriptor.address
                    )
                })?;
        }
        let expected = extra.global_balance.clone();
        custom
            .set(&extra)
            .context("failed to update masterchain global balance")?;
        expected
    };

    // Re-encode and decode once more before writing. The second decode catches
    // serialization mistakes, and the equality check guards against losing the
    // intended balance mutation while rebuilding the cell tree.
    let updated_boc =
        BocRepr::encode(&state).context("failed to encode updated masterchain zerostate")?;
    let updated_root =
        Boc::decode(&updated_boc).context("updated masterchain zerostate is not a valid BoC")?;
    let verified_state = load_cell_exact::<ShardStateUnsplit>(
        &updated_root,
        "updated masterchain zerostate is not a valid ShardStateUnsplit",
    )?;
    let verified_custom = verified_state
        .custom
        .as_ref()
        .context("updated masterchain zerostate has no McStateExtra")?;
    let verified_extra = load_cell_exact::<McStateExtra>(
        verified_custom.inner(),
        "updated masterchain zerostate contains invalid McStateExtra",
    )?;
    ensure!(
        verified_extra.global_balance == expected_global_balance,
        "updated masterchain global balance does not match imported basechain balances"
    );

    // Let the artifact update all three files and return the new identity. The
    // value returned by `create-state` is stale as soon as this BoC changes.
    let masterchain = masterchain.replace_boc(
        &updated_boc,
        TonBlockHash::from_bytes(updated_root.repr_hash().0),
    )?;
    info!(
        accounts = accounts.len(),
        "included basechain genesis balances in masterchain global balance"
    );
    Ok(masterchain)
}

#[cfg(test)]
mod tests {
    use std::{sync::Mutex, time::Duration};

    use async_trait::async_trait;
    use expect_test::expect;

    use super::*;

    #[derive(Default)]
    struct RecordingCreateState {
        requests: Mutex<Vec<CreateStateRequest>>,
    }

    #[async_trait]
    impl CreateState for RecordingCreateState {
        async fn create(
            &self,
            _context: &OperationContext,
            request: CreateStateRequest,
        ) -> Result<ZeroStateArtifacts> {
            self.requests.lock().unwrap().push(request.clone());
            let stem = match request.kind {
                ZeroStateKind::Masterchain => "zerostate",
                ZeroStateKind::Basechain => "basestate0",
            };
            let file_hash = match request.kind {
                ZeroStateKind::Masterchain => 0x22,
                ZeroStateKind::Basechain => 0x33,
            };
            write_artifacts(&request.output_dir, stem, file_hash)?;
            // The official combined masterchain script emits basechain artifacts
            // as a side effect when no imported accounts require a separate pass.
            if request.kind == ZeroStateKind::Masterchain {
                write_artifacts(&request.output_dir, "basestate0", 0x33)?;
            }
            ZeroStateArtifacts::load(request.kind, &request.output_dir)
        }
    }

    #[tokio::test]
    async fn combined_genesis_delegates_one_typed_masterchain_operation() {
        let directory = tempfile::tempdir_in("/tmp").unwrap();
        let layout = Layout::new(directory.path().join("state"));
        layout.create_bootstrap_dirs().unwrap();
        let create_state = RecordingCreateState::default();

        let states = create_genesis_states(
            &layout,
            &create_state,
            &OperationContext::for_node(Duration::from_secs(15), "genesis"),
            &NetworkSettings::default(),
            &[],
        )
        .await
        .unwrap();

        let requests = create_state.requests.lock().unwrap();
        let request = &requests[0];
        let rendered_genesis =
            fs::read_to_string(layout.smartcont.join("gen-zerostate.fif")).unwrap();
        let summary = format!(
            "calls={}\nkind={:?}\nscript={}\noutput={}\ninclude={}\nsimplex_v2={}\nmasterchain={}\nbasechain={}",
            requests.len(),
            request.kind,
            request.script.file_name().unwrap().to_string_lossy(),
            request.output_dir.file_name().unwrap().to_string_lossy(),
            request.include_paths[0]
                .file_name()
                .unwrap()
                .to_string_lossy(),
            rendered_genesis.contains("0 1000 simplex-param!")
                && rendered_genesis.contains("1 700 simplex-param!")
                && rendered_genesis.contains("10 250 simplex-param!")
                && rendered_genesis.contains("4\n  <b x{22}"),
            states.masterchain.id().file_hash(),
            states.basechain.id().file_hash(),
        );

        expect![[r#"
            calls=1
            kind=Masterchain
            script=gen-zerostate.fif
            output=zerostate
            include=smartcont
            simplex_v2=true
            masterchain=2222222222222222222222222222222222222222222222222222222222222222
            basechain=3333333333333333333333333333333333333333333333333333333333333333"#]]
        .assert_eq(&summary);
    }

    #[test]
    fn genesis_uses_current_ton_global_version_and_capabilities() {
        let rendered = include_str!("../../assets/gen-zerostate.fif")
            .replace("GLOBAL_VERSION", &TON_GLOBAL_VERSION.to_string())
            .replace("GLOBAL_CAPABILITIES", &TON_GLOBAL_CAPABILITIES.to_string());
        assert!(rendered.contains("15 1006 config.version!"));
    }

    // The recording adapter writes only the fixed files the workflow consumes;
    // it intentionally does not simulate Fift or validate hashes, because those
    // are separate `CreateState` adapter responsibilities.
    fn write_artifacts(output_dir: &Path, stem: &str, file_hash: u8) -> Result<()> {
        fs::write(output_dir.join(format!("{stem}.boc")), [0xb5, 0xee])?;
        fs::write(output_dir.join(format!("{stem}.rhash")), [0x11; 32])?;
        fs::write(output_dir.join(format!("{stem}.fhash")), [file_hash; 32])?;
        Ok(())
    }
}
