import {generateCode} from "@ton-community/tlb-codegen"
import {readFile, writeFile} from "node:fs/promises"

const SOURCE_REVISION = "ca7d6e456745a64eac8204a7b0b64516b61cf2db"
const schemaUrl = new URL("../src/cell-inspector/block.tlb", import.meta.url)
const outputUrl = new URL("../src/cell-inspector/block.tlb.generated.ts", import.meta.url)
const schema = await readFile(schemaUrl, "utf8")
const generated = generateCode(schema, "typescript")

const header = `// Generated by scripts/generate-block-tlb.ts. Do not edit manually.
// Source: ton-blockchain/ton@${SOURCE_REVISION}/crypto/block/block.tlb
// @ts-nocheck

`

await writeFile(outputUrl, `${header}${generated}`)
