import {generateCode} from "@ton-community/tlb-codegen"
import {spawnSync, type SpawnSyncReturns} from "node:child_process"
import {createHash} from "node:crypto"
import {mkdtemp, readFile, rm, writeFile} from "node:fs/promises"
import {tmpdir} from "node:os"
import {join} from "node:path"
import process from "node:process"
import {fileURLToPath} from "node:url"

import type {ConfigTlbCatalog} from "../src/config/tlb"

const schemaUrl = new URL("../src/cell-inspector/block.tlb", import.meta.url)
const sourceUrl = new URL("../src/cell-inspector/block.tlb.source.json", import.meta.url)
const outputUrl = new URL("../src/cell-inspector/block.tlb.generated.ts", import.meta.url)
const catalogUrl = new URL("../src/config/tlb.generated.json", import.meta.url)
const parametersUrl = new URL("../src/config/tlb.parameters.generated.json", import.meta.url)
const check = process.argv.includes("--check")
const update = process.argv.includes("--update")
const started = performance.now()
const operation = "generate.block-tlb"
const target = fileURLToPath(schemaUrl)

console.info(JSON.stringify({operation, target, outcome: "started", check, update}))

try {
  if (check && update) throw new Error("--check and --update cannot be used together")

  let schema = await readFile(schemaUrl, "utf8")
  let source: {revision: string; sha256: string} = JSON.parse(await readFile(sourceUrl, "utf8"))
  const previousRevision = source.revision
  if (!/^[a-f0-9]{40}$/.test(source.revision)) throw new Error("Invalid pinned TON revision")
  if (createHash("sha256").update(schema).digest("hex") !== source.sha256) {
    throw new Error(`Pinned TL-B checksum mismatch: ${target}`)
  }

  if (update) {
    // Resolve the file's commit first, then fetch that immutable revision so a
    // concurrent upstream push cannot mismatch the schema and its source link.
    const commitsUrl =
      "https://api.github.com/repos/ton-blockchain/ton/commits?sha=master&path=crypto%2Fblock%2Fblock.tlb&per_page=1"
    const response = await fetch(commitsUrl, {
      headers: {
        Accept: "application/vnd.github+json",
        ...(process.env.GH_TOKEN ? {Authorization: `Bearer ${process.env.GH_TOKEN}`} : {}),
      },
      signal: AbortSignal.timeout(30_000),
    })
    if (!response.ok)
      throw new Error(`TON revision lookup failed: ${response.status} ${commitsUrl}`)
    const commits: {sha: string}[] = await response.json()
    const revision = commits[0]?.sha
    if (!revision || !/^[a-f0-9]{40}$/.test(revision))
      throw new Error("TON returned no valid file revision")

    const upstreamUrl = `https://raw.githubusercontent.com/ton-blockchain/ton/${revision}/crypto/block/block.tlb`
    const upstream = await fetch(upstreamUrl, {signal: AbortSignal.timeout(30_000)})
    if (!upstream.ok)
      throw new Error(`TON schema download failed: ${upstream.status} ${upstreamUrl}`)
    const candidate = await upstream.text()
    const sha256 = createHash("sha256").update(candidate).digest("hex")
    // Changes elsewhere in TON, or commits with identical file content, must
    // not create a version-only update PR.
    if (sha256 !== source.sha256) {
      schema = candidate
      source = {revision, sha256}
    }
  }

  const generated = generateCode(schema, "typescript")
  // Validate the candidate before replacing the checked-in source.
  const temporaryDirectory = await mkdtemp(join(tmpdir(), "acton-block-tlb-"))
  const candidatePath = join(temporaryDirectory, "block.tlb")
  let extraction: SpawnSyncReturns<string>
  try {
    await writeFile(candidatePath, schema)
    extraction = spawnSync(
      "cargo",
      ["run", "--quiet", "--locked", "-p", "xtask", "--", "config-tlb", candidatePath],
      {
        cwd: new URL("../../../", import.meta.url),
        encoding: "utf8",
        stdio: ["ignore", "pipe", "inherit"],
        maxBuffer: 8 * 1024 * 1024,
      },
    )
  } finally {
    await rm(temporaryDirectory, {recursive: true, force: true})
  }
  if (extraction.error) throw extraction.error
  if (extraction.status !== 0) {
    throw new Error(`TL-B extraction failed for ${target} with status ${extraction.status}`)
  }

  const catalog: ConfigTlbCatalog = {
    ...JSON.parse(extraction.stdout),
    source: {
      ...source,
      url: `https://github.com/ton-blockchain/ton/blob/${source.revision}/crypto/block/block.tlb`,
    },
  }

  // A syntactically valid slice can still omit a dependency. The same compiler
  // as the decoder must accept every extracted schema on its own before writing.
  for (const [id, parameter] of Object.entries(catalog.parameters)) {
    const source = [...parameter.roots, ...parameter.dependencies.map(item => item.declaration)]
      .map(index => catalog.declarations[index])
      .join("\n\n")
    try {
      generateCode(source, "typescript")
    } catch (cause) {
      throw new Error(`Incomplete TL-B schema for ConfigParam ${id}`, {cause})
    }
  }

  const header = `// Generated by scripts/generate-block-tlb.ts. Do not edit manually.
// Source: ton-blockchain/ton@${source.revision}/crypto/block/block.tlb
// @ts-nocheck

`

  for (const [url, content] of [
    [schemaUrl, schema],
    [sourceUrl, `${JSON.stringify(source, null, 2)}\n`],
    [outputUrl, `${header}${generated.trimEnd()}\n`],
    [catalogUrl, `${JSON.stringify(catalog, null, 2)}\n`],
    [parametersUrl, `${JSON.stringify(Object.keys(catalog.parameters).map(Number), null, 2)}\n`],
  ] as const) {
    if (check) {
      if ((await readFile(url, "utf8")) !== content) {
        throw new Error(`Generated TL-B artifact is out of date: ${fileURLToPath(url)}`)
      }
    } else {
      await writeFile(url, content)
    }
  }

  await import("./generate-config-editor-schema")
  console.info(
    JSON.stringify({
      operation,
      target,
      outcome: "success",
      check,
      update,
      previousRevision,
      revision: source.revision,
      sourceChanged: source.revision !== previousRevision,
      parameters: Object.keys(catalog.parameters).length,
      durationMs: Math.round(performance.now() - started),
    }),
  )
} catch (error) {
  console.error(
    JSON.stringify({
      operation,
      target,
      outcome: "error",
      durationMs: Math.round(performance.now() - started),
      error: String(error),
    }),
  )
  throw error
}
