import type {Address} from "@ton/core"
import type {ContractABI} from "@ton/tolk-abi-to-typescript"
import type React from "react"
import {
  memo,
  useCallback,
  useDeferredValue,
  useLayoutEffect,
  useMemo,
  useRef,
  useState,
} from "react"
import {
  buildStorageDiff,
  formatOpcode,
  formatGramAmount,
  formatNumberValue,
  GramAmount,
  InlineButton,
  shortenMiddle,
  type ParsedValueDiff,
  ParsedValueDiffView,
} from "@acton/ui"
import {GitBranch, Route} from "lucide-react"
import {
  type CustomNodeElementProps,
  type RawNodeDatum,
  Tree,
  type TreeLinkDatum,
} from "react-d3-tree"

import type {BackendContractInfo, SourceLocation} from "../../model/backend"
import type {
  ContractData,
  LoadedTransactionActions,
  TransactionBlockRef,
  TransactionInfo,
} from "../../model/transaction"
import type {ContractVerifiedSource} from "../ContractSourcePanel/ContractSourcePanel"
import type {ResolveVerifiedSourceByCodeHash} from "../CodeCellDetails/CodeCellDetails"
import {decodeTransactionMessageBody} from "../../lib/messageBody"
import {
  getTransactionActionPhase,
  getTransactionComputePhase,
  getTransactionOpcode,
  getTransactionSourceLabel,
  getTransactionTriggerLabel,
  isSystemSourceAddress,
  resolveTransactionOpcodeName,
} from "../../lib/transaction"

import {TransactionDetails} from "../TransactionDetails/TransactionDetails"
import {ExternalOutMessageDetails} from "../TransactionDetails/ExternalOutMessageDetails"

import {SmartTooltip} from "./SmartTooltip"
import styles from "./TransactionTree.module.css"
import {useTooltip} from "./useTooltip"

const EAGER_MESSAGE_BODY_DECODE_TRANSACTION_LIMIT = 50
const MemoizedTransactionDetails = memo(TransactionDetails)

interface TreeSelection {
  readonly transactionId: string
  // Dictionary keys distinguish even identical external-out messages from one transaction.
  readonly externalMessageIndex?: number
}

interface EdgeTransactionTooltipData {
  readonly fromAddress: string | undefined
  readonly fromLabel: string | undefined
  readonly computePhase: {
    readonly success: boolean
    readonly exitCode?: number
    readonly gasUsed?: bigint
    readonly vmSteps?: number
  }
  readonly fees: {
    readonly gasFees?: bigint
    readonly totalFees: bigint
  }
  readonly sentTotal: bigint
}

interface NodeTransactionTooltipData {
  readonly contract: {
    readonly typeName: string
    readonly address: string | undefined
  }
  readonly account: {
    readonly isCreated: boolean
    readonly isDestroyed: boolean
  }
  readonly storageDiff: ParsedValueDiff | undefined
}

function SystemSourceTooltipContent({trigger}: {readonly trigger?: string}): React.JSX.Element {
  return (
    <div className={`${styles.tooltipContent} ${styles.systemTooltip}`}>
      <div className={styles.tooltipField}>
        <div className={styles.tooltipFieldLabel}>System{trigger ? ` · ${trigger}` : ""}</div>
        <div className={`${styles.tooltipFieldValue} ${styles.tooltipDescription}`}>
          {trigger
            ? `This ${trigger} transaction was initiated by the blockchain protocol, not by an incoming message.`
            : "This internal message was generated by the blockchain protocol, not sent by a smart contract."}
        </div>
      </div>
    </div>
  )
}

interface TransactionTreeProps {
  readonly transactions: readonly TransactionInfo[]
  readonly contracts: Map<string, ContractData>
  readonly compilerAbisByCodeHash?: ReadonlyMap<string, ContractData["abi"]>
  readonly verifiedSourcesByCodeHash?: ReadonlyMap<string, ContractVerifiedSource>
  readonly resolveVerifiedSourceByCodeHash?: ResolveVerifiedSourceByCodeHash
  readonly allContracts: readonly BackendContractInfo[]
  readonly selectedTransactionId?: string
  readonly highlightedTransactionIds?: ReadonlySet<string>
  readonly originatingTransaction?: TransactionInfo
  readonly omittedTransactionCount?: number
  readonly traceGapActionLabel?: string
  readonly traceGapLoading?: boolean
  readonly traceGapError?: string
  readonly onCellInspect?: (boc: string) => void
  readonly onContractClick?: (address: string) => void
  readonly onTransactionSelect?: (tx: TransactionInfo) => void
  readonly onTraceGapLoad?: () => void
  readonly renderAddressChip?: (
    address: string,
    options: {readonly shorten: boolean},
  ) => React.ReactNode
  readonly renderSourceLocation?: (location: SourceLocation) => React.ReactNode
  readonly renderSelectedTransactionExtra?: (tx: TransactionInfo) => React.ReactNode
  readonly renderSelectedTransactionMessageRouteAction?: (
    tx: TransactionInfo,
    messageName: string | undefined,
  ) => React.ReactNode
  readonly getBlockPath?: (blockRef: TransactionBlockRef) => string | undefined
  readonly onBlockClick?: (
    blockRef: TransactionBlockRef,
    event: React.MouseEvent<HTMLElement>,
  ) => void
  readonly loadActions?: (tx: TransactionInfo) => Promise<LoadedTransactionActions>
}

interface TreeLayout {
  readonly height: number
  readonly width: number
  readonly translate: {
    readonly x: number
    readonly y: number
  }
}

const TREE_NODE_SIZE = {x: 200, y: 120} as const
const TREE_SEPARATION = {siblings: 0.7, nonSiblings: 1} as const
const TREE_MIN_SIZE = {height: 80, width: 800} as const
const TREE_PADDING = {top: 8, right: 32, bottom: 8, left: 50} as const
const TREE_DETAILS_GAP = 15
const TREE_EDGE_LABEL = {width: 150, height: 64, failedHeight: 84, x: -180, y: -40} as const
const TREE_ACCOUNT_LABEL_MAX_LENGTH = 20
const TREE_SCALE_EXTENT = {min: 1, max: 1} as const

const getTreeLinkPath = ({source, target}: TreeLinkDatum): string => {
  const attributes = target.data.attributes ?? {}
  if (attributes.isFirst) {
    return "M"
      .concat(source.y.toString(), ",")
      .concat(source.x.toString(), "V")
      .concat((target.x + 10).toString(), "a10 10 0 0 1 10 -10H")
      .concat((target.y - 18).toString())
  }
  if (attributes.isLast) {
    return "M"
      .concat(source.y.toString(), ",")
      .concat(source.x.toString(), "V")
      .concat((target.x - 10).toString(), "a10 10 0 0 0 10 10H")
      .concat((target.y - 18).toString())
  }
  return "M"
    .concat(source.y.toString(), ",")
    .concat(source.x.toString(), "V")
    .concat(target.x.toString(), "H")
    .concat((target.y - 18).toString())
}

const getTreeLinkClass = ({source, target}: TreeLinkDatum): string => {
  const attributes = target.data.attributes
  if (attributes?.isTraceGap || source.data.attributes?.isTraceGap) {
    return `${styles.edgeStyle} ${styles.edgeStyleTraceGap}`
  }
  if (attributes?.withInitCode) {
    return `${styles.edgeStyle} ${styles.edgeStyleWithInit}`
  }
  if (attributes?.isBounced) {
    return `${styles.edgeStyle} ${styles.edgeStyleBounced}`
  }
  return styles.edgeStyle
}
const ACTION_HIGHLIGHT_SCROLL_DELAY_MS = 200

const INITIAL_TREE_LAYOUT: TreeLayout = {
  height: TREE_MIN_SIZE.height,
  width: TREE_MIN_SIZE.width,
  translate: {
    x: TREE_PADDING.left,
    y: TREE_MIN_SIZE.height / 2,
  },
}

interface TransactionTreeCanvasProps {
  readonly data: RawNodeDatum
  readonly translate: TreeLayout["translate"]
  readonly renderNode: (props: CustomNodeElementProps) => React.JSX.Element
}

const TransactionTreeCanvas = memo(function TransactionTreeCanvas({
  data,
  translate,
  renderNode,
}: TransactionTreeCanvasProps): React.JSX.Element {
  return (
    <Tree
      data={data}
      orientation="horizontal"
      pathFunc={getTreeLinkPath}
      nodeSize={TREE_NODE_SIZE}
      separation={TREE_SEPARATION}
      renderCustomNodeElement={renderNode}
      pathClassFunc={getTreeLinkClass}
      translate={translate}
      zoom={1}
      enableLegacyTransitions={false}
      collapsible={false}
      zoomable={false}
      draggable={false}
      scaleExtent={TREE_SCALE_EXTENT}
    />
  )
})

function EdgeTransactionTooltipContent({
  data,
  renderAddressChip,
}: {
  data: EdgeTransactionTooltipData
  renderAddressChip?: (address: string, options: {readonly shorten: boolean}) => React.ReactNode
}): React.JSX.Element {
  const fromAddressContent = data.fromAddress
    ? renderAddressChip?.(data.fromAddress, {shorten: true})
    : undefined

  return (
    <div className={styles.tooltipContent}>
      <div className={styles.tooltipField}>
        <div className={styles.tooltipFieldLabel}>From Address</div>
        <div className={styles.tooltipFieldValue}>
          {data.fromAddress ? (
            <span className={fromAddressContent ? styles.tooltipAddressChip : undefined}>
              {fromAddressContent ?? data.fromAddress}
            </span>
          ) : (
            (data.fromLabel ?? "unknown")
          )}
        </div>
      </div>

      <div className={styles.tooltipField}>
        <div className={styles.tooltipFieldLabel}>Compute Phase</div>
        <div className={styles.tooltipFieldValue}>
          {data.computePhase.success ? "Success" : "Failed"}
          {data.computePhase.exitCode !== undefined && data.computePhase.exitCode !== 0 && (
            <span>
              {" "}
              {"(Exit:"} {data.computePhase.exitCode})
            </span>
          )}
          {data.computePhase.gasUsed !== undefined && (
            <div className={styles.tooltipSubValue}>
              Gas Used: {data.computePhase.gasUsed.toString()}
            </div>
          )}
          {data.computePhase.vmSteps !== undefined && (
            <div className={styles.tooltipSubValue}>
              VM Steps: {data.computePhase.vmSteps.toString()}
            </div>
          )}
        </div>
      </div>

      <div className={styles.tooltipField}>
        <div className={styles.tooltipFieldLabel}>Money</div>
        <div className={styles.tooltipFieldValue}>
          <div>
            Sent Total: <GramAmount value={data.sentTotal} />
          </div>
          <div className={styles.tooltipSubValue}>
            Total Fees: <GramAmount value={data.fees.totalFees} />
          </div>
          {data.fees.gasFees !== undefined && (
            <div className={styles.tooltipSubValue}>
              Gas Fees: <GramAmount value={data.fees.gasFees} />
            </div>
          )}
        </div>
      </div>
    </div>
  )
}

function NodeTransactionTooltipContent({
  data,
  contracts,
  onContractClick,
  renderAddressChip,
}: {
  data: NodeTransactionTooltipData
  contracts: Map<string, ContractData>
  onContractClick?: (address: string) => void
  renderAddressChip?: (address: string, options: {readonly shorten: boolean}) => React.ReactNode
}): React.JSX.Element {
  const contractAddressContent = data.contract.address
    ? renderAddressChip?.(data.contract.address, {shorten: false})
    : undefined

  return (
    <div className={styles.tooltipContent}>
      <div className={styles.tooltipField}>
        <div className={styles.tooltipFieldLabel}>{data.contract.typeName}</div>
        <div className={styles.tooltipFieldValue}>
          {data.contract.address ? (
            <span className={contractAddressContent ? styles.tooltipAddressChip : undefined}>
              {contractAddressContent ?? data.contract.address}
            </span>
          ) : (
            "unknown"
          )}
        </div>
      </div>

      {data.storageDiff && (
        <div className={styles.tooltipField}>
          <div className={styles.tooltipFieldLabel}>Storage</div>
          <div className={`${styles.tooltipFieldValue} ${styles.tooltipFieldValueStructured}`}>
            {(data.account.isCreated || data.account.isDestroyed) && (
              <div className={styles.storageMeta}>
                {data.account.isCreated && (
                  <span className={`${styles.storageMetaBadge} ${styles.storageMetaBadgeCreated}`}>
                    Account created
                  </span>
                )}
                {data.account.isDestroyed && (
                  <span
                    className={`${styles.storageMetaBadge} ${styles.storageMetaBadgeDestroyed}`}
                  >
                    Account destroyed
                  </span>
                )}
              </div>
            )}
            <div className={styles.storageDiffScroll}>
              <ParsedValueDiffView
                diff={data.storageDiff}
                contracts={contracts}
                onContractClick={onContractClick}
              />
            </div>
          </div>
        </div>
      )}
    </div>
  )
}

function TransactionTreeComponent({
  transactions,
  contracts,
  compilerAbisByCodeHash,
  verifiedSourcesByCodeHash,
  resolveVerifiedSourceByCodeHash,
  allContracts,
  selectedTransactionId,
  highlightedTransactionIds,
  originatingTransaction,
  omittedTransactionCount,
  traceGapActionLabel,
  traceGapLoading = false,
  traceGapError,
  onCellInspect,
  onContractClick,
  onTransactionSelect,
  onTraceGapLoad,
  renderAddressChip,
  renderSourceLocation,
  renderSelectedTransactionExtra,
  renderSelectedTransactionMessageRouteAction,
  getBlockPath,
  onBlockClick,
  loadActions,
}: TransactionTreeProps): React.JSX.Element {
  const {
    tooltip,
    showTooltip,
    hideTooltip,
    forceHideTooltip,
    setIsTooltipHovered,
    calculateOptimalPosition,
  } = useTooltip()

  const [selection, setSelection] = useState<TreeSelection | undefined>(
    selectedTransactionId ? {transactionId: selectedTransactionId} : undefined,
  )
  const selectionRef = useRef(selection)
  const triggerRectReference = useRef<DOMRect | undefined>(undefined)
  const treeContainerRef = useRef<HTMLDivElement | null>(null)
  const treeWrapperRef = useRef<HTMLDivElement | null>(null)
  const selectedNodeRef = useRef<SVGGElement | null>(null)
  const [treeLayout, setTreeLayout] = useState<TreeLayout>(INITIAL_TREE_LAYOUT)
  const shouldDecodeMessageBodies =
    transactions.length <= EAGER_MESSAGE_BODY_DECODE_TRANSACTION_LIMIT

  const rootTransactions = useMemo(() => {
    return transactions
      .filter(tx => !tx.parent)
      .sort((a, b) => Number(a.transaction.lt - b.transaction.lt))
  }, [transactions])

  const transactionMap = useMemo(() => {
    const map: Map<string, TransactionInfo> = new Map()
    for (const tx of transactions) {
      map.set(tx.id, tx)
    }
    if (originatingTransaction) {
      map.set(originatingTransaction.id, originatingTransaction)
    }
    return map
  }, [originatingTransaction, transactions])

  const additionalAbis = useMemo(
    () =>
      [
        ...allContracts.map(contract => contract.abi),
        ...(compilerAbisByCodeHash?.values() ?? []),
      ].filter((abi): abi is ContractABI => abi !== undefined),
    [allContracts, compilerAbisByCodeHash],
  )

  // react-d3-tree calls the node renderer for every node whenever its callback changes.
  // Keep event-only dependencies behind a committed ref so route changes and tooltip state do
  // not invalidate the structural canvas, while handlers still observe the latest props.
  const eventContextRef = useRef({
    transactionMap,
    contracts,
    onContractClick,
    onTransactionSelect,
    onTraceGapLoad,
    renderAddressChip,
  })
  useLayoutEffect(() => {
    eventContextRef.current = {
      transactionMap,
      contracts,
      onContractClick,
      onTransactionSelect,
      onTraceGapLoad,
      renderAddressChip,
    }
  }, [
    contracts,
    onContractClick,
    onTraceGapLoad,
    onTransactionSelect,
    renderAddressChip,
    transactionMap,
  ])

  const updateSelection = useCallback((nextSelection: TreeSelection | undefined): void => {
    selectionRef.current = nextSelection
    setSelection(nextSelection)
  }, [])

  const handleNodeClick = useCallback(
    (id: string): void => {
      const {transactionMap: currentTransactionMap, onTransactionSelect: selectTransaction} =
        eventContextRef.current
      const transaction = currentTransactionMap.get(id)
      if (!transaction) return

      forceHideTooltip()
      if (
        selectionRef.current?.transactionId === id &&
        selectionRef.current.externalMessageIndex === undefined
      ) {
        updateSelection(undefined)
        return
      }

      updateSelection({transactionId: id})
      selectTransaction?.(transaction)
    },
    [forceHideTooltip, updateSelection],
  )

  const handleExternalOutClick = useCallback(
    (parentId: string, messageIndex: number): void => {
      const {transactionMap: currentTransactionMap, onTransactionSelect: selectTransaction} =
        eventContextRef.current
      const parentTransaction = currentTransactionMap.get(parentId)
      if (
        parentTransaction?.transaction.outMessages.get(messageIndex)?.info.type !== "external-out"
      )
        return

      forceHideTooltip()
      if (
        selectionRef.current?.transactionId === parentId &&
        selectionRef.current.externalMessageIndex === messageIndex
      ) {
        updateSelection(undefined)
        return
      }

      updateSelection({transactionId: parentId, externalMessageIndex: messageIndex})
      selectTransaction?.(parentTransaction)
    },
    [forceHideTooltip, updateSelection],
  )

  const handleTraceGapLoad = useCallback((): void => {
    eventContextRef.current.onTraceGapLoad?.()
  }, [])

  const showEdgeTransactionTooltip = useCallback(
    (event: React.MouseEvent, transactionId: string): void => {
      const {transactionMap: currentTransactionMap, renderAddressChip: renderCurrentAddressChip} =
        eventContextRef.current
      const tx = currentTransactionMap.get(transactionId)
      if (!tx) return

      const rect = (event.currentTarget as HTMLElement).getBoundingClientRect()
      triggerRectReference.current = rect

      const computePhase = getTransactionComputePhase(tx.transaction)
      const sourceLabel = getTransactionSourceLabel(tx.transaction)
      const sourceAddress =
        sourceLabel === undefined && tx.transaction.inMessage?.info.src
          ? tx.transaction.inMessage.info.src.toString()
          : undefined

      const tooltipData: EdgeTransactionTooltipData = {
        fromAddress: sourceAddress,
        fromLabel: sourceLabel,
        computePhase: {
          success: computePhase?.type === "vm" ? computePhase.success : true,
          exitCode: computePhase?.type === "vm" ? computePhase.exitCode : undefined,
          gasUsed: computePhase?.type === "vm" ? computePhase.gasUsed : undefined,
          vmSteps: computePhase?.type === "vm" ? computePhase.vmSteps : undefined,
        },
        fees: {
          gasFees: computePhase?.type === "vm" ? computePhase.gasFees : undefined,
          totalFees: tx.transaction.totalFees.coins,
        },
        sentTotal: [...tx.transaction.outMessages.values()].reduce(
          (accumulator: bigint, message) =>
            accumulator + (message.info.type === "internal" ? message.info.value.coins : 0n),
          0n,
        ),
      }

      showTooltip({
        x: rect.left,
        y: rect.top,
        content: (
          <EdgeTransactionTooltipContent
            data={tooltipData}
            renderAddressChip={renderCurrentAddressChip}
          />
        ),
      })
    },
    [showTooltip],
  )

  const showNodeTransactionTooltip = useCallback(
    (event: React.MouseEvent, transactionId: string): void => {
      const {
        transactionMap: currentTransactionMap,
        contracts: currentContracts,
        onContractClick: handleContractClick,
        renderAddressChip: renderCurrentAddressChip,
      } = eventContextRef.current
      const tx = currentTransactionMap.get(transactionId)
      if (!tx) return

      const rect = (event.currentTarget as HTMLElement).getBoundingClientRect()
      triggerRectReference.current = rect

      const contractAddress = tx.address ? tx.address.toString() : undefined
      const isCreated =
        tx.transaction.oldStatus === "non-existing" && tx.transaction.endStatus === "active"
      const isDestroyed =
        tx.transaction.oldStatus === "active" && tx.transaction.endStatus === "non-existing"
      const contractTypeName = tx.contractName ?? tx.contractAbi?.contract_name?.trim() ?? "unknown"

      const tooltipData: NodeTransactionTooltipData = {
        contract: {
          typeName: contractTypeName,
          address: contractAddress,
        },
        account: {
          isCreated,
          isDestroyed,
        },
        storageDiff: buildStorageDiff(tx.parsedStorageBefore, tx.parsedStorageAfter),
      }

      showTooltip({
        x: rect.left,
        y: rect.top,
        content: (
          <NodeTransactionTooltipContent
            data={tooltipData}
            contracts={currentContracts}
            onContractClick={handleContractClick}
            renderAddressChip={renderCurrentAddressChip}
          />
        ),
      })
    },
    [showTooltip],
  )

  const showSourceContractTooltip = useCallback(
    (event: React.MouseEvent, address: string): void => {
      const {
        contracts: currentContracts,
        onContractClick: handleContractClick,
        renderAddressChip: renderCurrentAddressChip,
      } = eventContextRef.current
      const trigger = event.currentTarget as SVGGElement
      const rect =
        trigger.querySelector<SVGCircleElement>(":scope > circle")?.getBoundingClientRect() ??
        trigger.getBoundingClientRect()
      const contract = currentContracts.get(address)
      triggerRectReference.current = rect

      showTooltip({
        x: rect.left,
        y: rect.top,
        content: (
          <NodeTransactionTooltipContent
            data={{
              contract: {
                typeName: contract?.abi?.contract_name?.trim() || "unknown",
                address,
              },
              account: {
                isCreated: false,
                isDestroyed: false,
              },
              storageDiff: undefined,
            }}
            contracts={currentContracts}
            onContractClick={handleContractClick}
            renderAddressChip={renderCurrentAddressChip}
          />
        ),
      })
    },
    [showTooltip],
  )

  const treeData: RawNodeDatum = useMemo<RawNodeDatum>(() => {
    const convertTransactionToNode = (tx: TransactionInfo): RawNodeDatum => {
      const thisAddress = tx.address
      const addressName = formatAddress(thisAddress, contracts)

      const computePhase = getTransactionComputePhase(tx.transaction)
      const actionPhase = getTransactionActionPhase(tx.transaction)

      const inMessage = tx.transaction.inMessage
      const withInitCode = inMessage?.init?.code !== undefined
      const isBounced = inMessage?.info.type === "internal" ? inMessage.info.bounced : false

      const isComputeSuccess = computePhase?.type === "vm" ? computePhase.success : true
      const isActionSuccess = actionPhase ? actionPhase.resultCode === 0 : true
      const isSuccess = isComputeSuccess && isActionSuccess
      const exitCode = computePhase?.type === "vm" ? computePhase.exitCode : undefined

      const value =
        inMessage?.info.type === "external-in"
          ? "—"
          : formatGramAmount(
              inMessage?.info.type === "internal" ? inMessage.info.value.coins : undefined,
            )

      const parsedBody = shouldDecodeMessageBodies
        ? decodeTransactionMessageBody(tx, contracts, allContracts, compilerAbisByCodeHash)
        : undefined
      const opcode = getTransactionOpcode(tx.transaction, parsedBody)
      const targetContract = thisAddress ? contracts.get(thisAddress.toString()) : undefined
      const opcodeName = resolveTransactionOpcodeName(tx, contracts, allContracts, parsedBody)
      const opcodeHex =
        opcodeName ??
        (parsedBody && opcode === undefined
          ? parsedBody.name
          : opcode === undefined
            ? "empty"
            : (formatOpcode(opcode) ?? "unknown"))

      const contractLetter = thisAddress ? (targetContract?.letter ?? "?") : "?"

      const lt = tx.lt
      const id = tx.id
      const isActionHighlighted = highlightedTransactionIds?.has(id) ?? false

      const externalOutChildren: RawNodeDatum[] = []
      for (const [messageIndex, message] of tx.transaction.outMessages) {
        if (message.info.type !== "external-out") continue

        externalOutChildren.push({
          name: "",
          attributes: {
            isExternalOut: true,
            parentId: id,
            messageIndex,
            destination: message.info.dest?.toString() ?? "External",
            createdLt: message.info.createdLt.toString(),
          },
          children: [],
        })
      }

      return {
        name: addressName,
        attributes: {
          from:
            getTransactionSourceLabel(tx.transaction) ??
            inMessage?.info.src?.toString() ??
            "unknown",
          to: inMessage?.info.dest?.toString() ?? "unknown",
          id,
          lt,
          success: isSuccess ? "✓" : "✗",
          exitCode: exitCode?.toString() ?? "0",
          value,
          opcode: opcodeHex,
          outMsgs: tx.transaction.outMessagesCount.toString(),
          withInitCode,
          isBounced,
          contractLetter,
          isActionHighlighted,
        },
        children: [...tx.children.map(it => convertTransactionToNode(it)), ...externalOutChildren],
      } satisfies RawNodeDatum
    }

    const buildCurrentTraceRoot = (): RawNodeDatum => {
      if (rootTransactions.length === 0) {
        return {
          name: "No transactions",
          attributes: {
            isRoot: "false",
            systemTrigger: "",
            contractLetter: "",
          },
          children: [],
        } satisfies RawNodeDatum
      }

      const rootTransaction = rootTransactions.length === 1 ? rootTransactions[0] : undefined
      const systemTrigger = rootTransaction
        ? getTransactionTriggerLabel(rootTransaction.transaction)
        : undefined
      const sharedInternalSource = getSharedInternalSource(rootTransactions)

      if (rootTransaction?.transaction.inMessage?.info.type === "external-in") {
        return {
          name: "",
          attributes: {
            isRoot: "hidden",
            systemTrigger: "",
            contractLetter: "",
          },
          children: [convertTransactionToNode(rootTransaction)],
        } satisfies RawNodeDatum
      }

      if (rootTransaction && systemTrigger) {
        return {
          name: "System",
          attributes: {
            isRoot: "system",
            systemTrigger,
            contractLetter: "",
          },
          children: [convertTransactionToNode(rootTransaction)],
        } satisfies RawNodeDatum
      }

      if (sharedInternalSource) {
        const sourceContract = contracts.get(sharedInternalSource.toString())
        const isSystemSource = isSystemSourceAddress(sharedInternalSource)

        return {
          name: isSystemSource ? "System" : formatAddress(sharedInternalSource, contracts),
          attributes: {
            isRoot: isSystemSource ? "system" : "source",
            systemTrigger: "",
            contractLetter: sourceContract?.letter ?? "?",
            sourceAddress: sharedInternalSource.toString(),
          },
          children: rootTransactions.map(it => convertTransactionToNode(it)),
        } satisfies RawNodeDatum
      }

      return {
        name: "Trace",
        attributes: {
          isRoot: "root",
          systemTrigger: "",
          contractLetter: "",
        },
        children: rootTransactions.map(it => convertTransactionToNode(it)),
      } satisfies RawNodeDatum
    }

    const currentTraceRoot = buildCurrentTraceRoot()
    const isOriginAlreadyVisible =
      originatingTransaction !== undefined &&
      transactions.some(transaction => transaction.id === originatingTransaction.id)
    const omittedLabel =
      omittedTransactionCount === undefined
        ? "Trace segment unavailable"
        : `${formatNumberValue(omittedTransactionCount, {locale: "en-US"})} tx omitted`
    const createTraceGapNode = (children: RawNodeDatum[] = []): RawNodeDatum => ({
      name: omittedLabel,
      attributes: {
        isTraceGap: true,
        omittedLabel,
      },
      children,
    })

    if (!originatingTransaction || isOriginAlreadyVisible) {
      if (omittedTransactionCount === undefined || omittedTransactionCount <= 0) {
        return currentTraceRoot
      }

      const traceGapBranch = createTraceGapNode()
      const currentRootChildren = currentTraceRoot.children ?? []
      if (currentTraceRoot.attributes?.isRoot === "hidden" && currentRootChildren.length > 0) {
        const [rootNode, ...otherRoots] = currentRootChildren
        if (rootNode) {
          return {
            ...currentTraceRoot,
            children: [
              {
                ...rootNode,
                children: [...(rootNode.children ?? []), traceGapBranch],
              },
              ...otherRoots,
            ],
          } satisfies RawNodeDatum
        }
      }

      return {
        ...currentTraceRoot,
        children: [...currentRootChildren, traceGapBranch],
      } satisfies RawNodeDatum
    }

    if (omittedTransactionCount === 0) {
      return currentTraceRoot
    }

    const originNode = convertTransactionToNode(originatingTransaction)
    const continuationRoot = {
      ...currentTraceRoot,
      attributes: {
        ...currentTraceRoot.attributes,
        isTraceGapContinuation: true,
      },
    } satisfies RawNodeDatum

    return {
      name: "",
      attributes: {
        isRoot: "hidden",
        systemTrigger: "",
        contractLetter: "",
      },
      children: [
        {
          ...originNode,
          children: [createTraceGapNode([continuationRoot])],
        },
      ],
    } satisfies RawNodeDatum
  }, [
    rootTransactions,
    contracts,
    highlightedTransactionIds,
    allContracts,
    compilerAbisByCodeHash,
    shouldDecodeMessageBodies,
    originatingTransaction,
    omittedTransactionCount,
    transactions,
  ])

  const canLoadTraceGap = onTraceGapLoad !== undefined
  const renderCustomNodeElement = useCallback(
    ({nodeDatum}: CustomNodeElementProps): React.JSX.Element => {
      if (nodeDatum.attributes?.isRoot === "hidden") {
        return <g />
      }

      if (
        nodeDatum.attributes?.isRoot === "source" ||
        nodeDatum.attributes?.isRoot === "system" ||
        nodeDatum.attributes?.isRoot === "root"
      ) {
        const isSystemSource = nodeDatum.attributes.isRoot === "system"
        const isTraceGapContinuation = nodeDatum.attributes.isTraceGapContinuation === true
        const systemTrigger = nodeDatum.attributes.systemTrigger as string | undefined
        const sourceAddress = nodeDatum.attributes.sourceAddress as string | undefined
        const sourceLabel = isSystemSource
          ? `System${systemTrigger ? ` · ${systemTrigger}` : ""}`
          : nodeDatum.name

        return (
          // biome-ignore lint/a11y/noStaticElementInteractions: Hover only reveals explanatory context for this SVG node.
          <g
            className={`${styles.rootNode} ${isSystemSource ? styles.systemRootNode : ""} ${
              isTraceGapContinuation ? styles.traceGapContinuationNode : ""
            }`}
            onMouseEnter={event => {
              if (isSystemSource) {
                const rect = event.currentTarget.getBoundingClientRect()
                triggerRectReference.current = rect
                showTooltip({
                  x: rect.left,
                  y: rect.top,
                  content: <SystemSourceTooltipContent trigger={systemTrigger} />,
                })
              } else if (isTraceGapContinuation && sourceAddress) {
                showSourceContractTooltip(event, sourceAddress)
              }
            }}
            onMouseLeave={() => {
              if (isSystemSource || isTraceGapContinuation) hideTooltip()
            }}
          >
            <title>{sourceLabel}</title>
            <circle
              r={15}
              fill="var(--acton-color-surface)"
              stroke="var(--acton-color-text)"
              strokeWidth={1.5}
              className={styles.rootCircle}
            />
            {isSystemSource ? (
              <text
                fill="var(--acton-color-text)"
                strokeWidth="0"
                x="0"
                y="3.5"
                fontSize="9"
                fontWeight="bold"
                letterSpacing="0.25"
                textAnchor="middle"
                className={styles.nodeText}
              >
                SYS
              </text>
            ) : (
              <text
                fill="var(--acton-color-text)"
                strokeWidth="0"
                x="0"
                y="5"
                fontSize="14"
                fontWeight="bold"
                textAnchor="middle"
                className={styles.nodeText}
              >
                {(nodeDatum.attributes?.contractLetter as string) || "?"}
              </text>
            )}
            {isTraceGapContinuation && (
              <foreignObject
                width={TREE_EDGE_LABEL.width}
                height={TREE_EDGE_LABEL.height}
                x={TREE_EDGE_LABEL.x}
                y={TREE_EDGE_LABEL.y}
              >
                <div className={styles.edgeText} role="note">
                  <div className={styles.topText}>
                    <p className={styles.edgeTextTitle} aria-label={nodeDatum.name}>
                      {shortenMiddle(nodeDatum.name, {maxLength: TREE_ACCOUNT_LABEL_MAX_LENGTH})}
                    </p>
                    <p className={styles.edgeTextContent}>—</p>
                  </div>
                  <div className={styles.bottomText}>
                    <p className={styles.edgeTextContent}>—</p>
                  </div>
                </div>
              </foreignObject>
            )}
          </g>
        )
      }

      if (nodeDatum.attributes?.isTraceGap) {
        const omittedLabel = nodeDatum.attributes.omittedLabel as string

        return (
          <g className={styles.traceGapNode}>
            <title>Trace unavailable · {omittedLabel}</title>
            <circle
              r={15}
              fill="var(--acton-color-surface)"
              stroke="var(--acton-color-warning)"
              strokeWidth={1.5}
              strokeDasharray="2 2"
            />
            <g>
              <circle
                cx={-5}
                cy={0}
                r={1.8}
                style={{fill: "var(--acton-color-warning)", stroke: "none"}}
              />
              <circle
                cx={0}
                cy={0}
                r={1.8}
                style={{fill: "var(--acton-color-warning)", stroke: "none"}}
              />
              <circle
                cx={5}
                cy={0}
                r={1.8}
                style={{fill: "var(--acton-color-warning)", stroke: "none"}}
              />
            </g>
            <foreignObject
              width={TREE_EDGE_LABEL.width}
              height={traceGapError ? 96 : TREE_EDGE_LABEL.height}
              x={TREE_EDGE_LABEL.x}
              y={TREE_EDGE_LABEL.y}
            >
              <div className={`${styles.edgeText} ${styles.traceGapLabel}`}>
                <div className={styles.topText}>
                  <p className={`${styles.edgeTextTitle} ${styles.traceGapTitle}`}>
                    Trace unavailable
                  </p>
                  <p className={`${styles.edgeTextContent} ${styles.traceGapCount}`}>
                    {omittedLabel}
                  </p>
                </div>
                {canLoadTraceGap && (
                  <div className={`${styles.bottomText} ${styles.traceGapAction}`}>
                    <InlineButton
                      variant="utility"
                      className={styles.traceGapButton}
                      leadingIcon={
                        traceGapActionLabel === "Restore path" ? (
                          <Route size={11} />
                        ) : (
                          <GitBranch size={11} />
                        )
                      }
                      disabled={traceGapLoading}
                      aria-busy={traceGapLoading || undefined}
                      title={
                        traceGapActionLabel === "Restore path"
                          ? "Restore up to 10 causal transactions from Toncenter"
                          : "Load up to 10 more transactions from Toncenter"
                      }
                      onClick={event => {
                        event.stopPropagation()
                        handleTraceGapLoad()
                      }}
                    >
                      {traceGapLoading ? "Loading…" : (traceGapActionLabel ?? "Load 10")}
                    </InlineButton>
                  </div>
                )}
                {traceGapError && (
                  <p className={styles.traceGapError} role="alert">
                    {traceGapError}
                  </p>
                )}
              </div>
            </foreignObject>
          </g>
        )
      }

      if (nodeDatum.attributes?.isExternalOut) {
        const parentId = nodeDatum.attributes.parentId as string
        const messageIndex = nodeDatum.attributes.messageIndex as number
        const externalOutAriaLabel = `External-out message ${messageIndex} from transaction ${parentId}`
        const externalOutDestination = nodeDatum.attributes.destination as string
        const createdLt = nodeDatum.attributes.createdLt as string

        return (
          <g data-external-message-id={`${parentId}:${messageIndex}`}>
            <foreignObject
              width="4"
              height="6"
              x="-20"
              y="-3"
              className={styles.foreignObjectContainer}
            >
              <svg
                width="4"
                height="6"
                viewBox="0 0 4 5"
                xmlns="http://www.w3.org/2000/svg"
                className={styles.iconSvg}
              >
                <title>External Out</title>
                <path
                  d="M0.400044 0.549983C0.648572 0.218612 1.11867 0.151455 1.45004 0.399983L3.45004 1.89998C3.6389 2.04162 3.75004 2.26392 3.75004 2.49998C3.75004 2.73605 3.6389 2.95834 3.45004 3.09998L1.45004 4.59998C1.11867 4.84851 0.648572 4.78135 0.400044 4.44998C0.151516 4.11861 0.218673 3.64851 0.550044 3.39998L1.75004 2.49998L0.550044 1.59998C0.218673 1.35145 0.151516 0.881354 0.400044 0.549983Z"
                  fill="var(--acton-color-text-subtle)"
                ></path>
              </svg>
            </foreignObject>

            <circle
              r={15}
              role="button"
              tabIndex={0}
              aria-label={externalOutAriaLabel}
              aria-pressed={false}
              fill="transparent"
              stroke="var(--acton-color-border)"
              strokeWidth={1}
              className={styles.nodeCircle}
              onClick={() => {
                handleExternalOutClick(parentId, messageIndex)
              }}
              onKeyDown={event => {
                if (event.key === "Enter" || event.key === " ") {
                  event.preventDefault()
                  handleExternalOutClick(parentId, messageIndex)
                }
              }}
            />
            {/* biome-ignore lint/a11y/noAriaHiddenOnFocusable: The SVG focus ring is decorative and cannot receive focus. */}
            <circle r={20} className={styles.nodeFocusRing} aria-hidden="true" />

            <foreignObject
              width={TREE_EDGE_LABEL.width}
              height={TREE_EDGE_LABEL.height}
              x={TREE_EDGE_LABEL.x}
              y={TREE_EDGE_LABEL.y}
            >
              <div className={styles.edgeText}>
                <div className={styles.topText}>
                  <p className={styles.edgeTextTitle}>{externalOutDestination}</p>
                  <p className={styles.edgeTextContent}>Lt: {createdLt}</p>
                </div>
                <div className={styles.bottomText}>
                  <p className={styles.edgeTextContent}>Type: external-out</p>
                </div>
              </div>
            </foreignObject>
          </g>
        )
      }

      const opcode = (nodeDatum.attributes?.opcode as string | undefined) ?? "empty opcode"
      const id = nodeDatum.attributes?.id as string
      const isActionHighlighted = nodeDatum.attributes?.isActionHighlighted as boolean
      const exitCode = (nodeDatum.attributes?.exitCode as string | undefined) ?? "0"
      const hasFailureDetails = exitCode !== "0"
      const successMark = nodeDatum.attributes?.success as string | undefined
      const isFailed = successMark !== "✓"
      const nodeCircleClassName = [
        styles.nodeCircle,
        isActionHighlighted ? styles.nodeCircleActionHighlighted : undefined,
      ]
        .filter(Boolean)
        .join(" ")
      const transactionNodeClassName = [
        isFailed ? styles.transactionNodeFailed : undefined,
        isActionHighlighted ? styles.transactionNodeActionHighlighted : undefined,
      ]
        .filter(Boolean)
        .join(" ")

      return (
        <g data-transaction-id={id} className={transactionNodeClassName}>
          <foreignObject
            width="4"
            height="6"
            x="-20"
            y="-3"
            className={styles.foreignObjectContainer}
          >
            <svg
              width="4"
              height="6"
              viewBox="0 0 4 5"
              xmlns="http://www.w3.org/2000/svg"
              className={styles.iconSvg}
            >
              <title>Incoming Message</title>
              <path
                d="M0.400044 0.549983C0.648572 0.218612 1.11867 0.151455 1.45004 0.399983L3.45004 1.89998C3.6389 2.04162 3.75004 2.26392 3.75004 2.49998C3.75004 2.73605 3.6389 2.95834 3.45004 3.09998L1.45004 4.59998C1.11867 4.84851 0.648572 4.78135 0.400044 4.44998C0.151516 4.11861 0.218673 3.64851 0.550044 3.39998L1.75004 2.49998L0.550044 1.59998C0.218673 1.35145 0.151516 0.881354 0.400044 0.549983Z"
                fill="var(--acton-color-text-subtle)"
              ></path>
            </svg>
          </foreignObject>
          <circle
            r={15}
            role="button"
            tabIndex={0}
            aria-label={`Transaction ${id}`}
            aria-pressed={false}
            fill={
              isActionHighlighted
                ? "var(--transaction-tree-action-highlight-fill)"
                : isFailed
                  ? "var(--transaction-tree-failed-node-fill)"
                  : "var(--acton-color-surface)"
            }
            stroke={
              isActionHighlighted
                ? "var(--transaction-tree-action-highlight-stroke)"
                : isFailed
                  ? "var(--transaction-tree-failed-node-stroke)"
                  : "var(--acton-color-text)"
            }
            strokeWidth={isActionHighlighted || isFailed ? 2 : 1.5}
            onClick={() => {
              handleNodeClick(id)
            }}
            onKeyDown={event => {
              if (event.key === "Enter" || event.key === " ") {
                event.preventDefault()
                handleNodeClick(id)
              }
            }}
            onMouseEnter={event => {
              showNodeTransactionTooltip(event, id)
            }}
            onMouseLeave={() => {
              hideTooltip()
            }}
            className={nodeCircleClassName}
          />
          {/* biome-ignore lint/a11y/noAriaHiddenOnFocusable: The SVG focus ring is decorative and cannot receive focus. */}
          <circle r={20} className={styles.nodeFocusRing} aria-hidden="true" />

          <text
            fill={
              isActionHighlighted
                ? "var(--transaction-tree-action-highlight-text)"
                : isFailed
                  ? "var(--transaction-tree-failed-node-text)"
                  : "var(--acton-color-text)"
            }
            strokeWidth="0"
            x="0"
            y="5"
            fontSize="14"
            fontWeight="bold"
            textAnchor="middle"
            className={styles.nodeText}
          >
            {nodeDatum.attributes?.contractLetter as string}
          </text>
          {isFailed && (
            // biome-ignore lint/a11y/noAriaHiddenOnFocusable: This failure badge is purely decorative.
            <g className={styles.failedBadge} aria-hidden="true">
              <circle
                cx={10}
                cy={10}
                r={5.4}
                fill="var(--transaction-tree-failed-badge-fill)"
                stroke="var(--transaction-tree-failed-badge-stroke)"
                strokeWidth={0.75}
              />
              <rect
                x={9.05}
                y={6.5}
                width={1.9}
                height={4.4}
                rx={0.95}
                strokeWidth={0}
                fill="var(--transaction-tree-failed-badge-text)"
                stroke="var(--transaction-tree-failed-badge-mark-stroke)"
              />
              <circle
                cx={10}
                cy={12.7}
                r={0.9}
                strokeWidth={0}
                fill="var(--transaction-tree-failed-badge-text)"
                stroke="var(--transaction-tree-failed-badge-mark-stroke)"
              />
            </g>
          )}
          <foreignObject
            width={TREE_EDGE_LABEL.width}
            height={hasFailureDetails ? TREE_EDGE_LABEL.failedHeight : TREE_EDGE_LABEL.height}
            x={TREE_EDGE_LABEL.x}
            y={TREE_EDGE_LABEL.y}
          >
            <div
              className={styles.edgeText}
              role="note"
              onMouseEnter={event => {
                showEdgeTransactionTooltip(event, id)
              }}
              onMouseLeave={() => {
                hideTooltip()
              }}
            >
              <div className={styles.topText}>
                <p className={styles.edgeTextTitle} aria-label={nodeDatum.name}>
                  {shortenMiddle(nodeDatum.name, {maxLength: TREE_ACCOUNT_LABEL_MAX_LENGTH})}
                </p>
                {nodeDatum.attributes?.value && (
                  <p className={styles.edgeTextContent}>{nodeDatum.attributes.value as string}</p>
                )}
              </div>
              <div className={styles.bottomText}>
                <p className={styles.edgeTextContent}>{opcode}</p>
                {hasFailureDetails && (
                  <p className={styles.edgeTextContent}>
                    Exit: {exitCode} | Success: {successMark === "✓" ? "true" : "false"}
                  </p>
                )}
              </div>
            </div>
          </foreignObject>
        </g>
      )
    },
    [
      canLoadTraceGap,
      handleExternalOutClick,
      handleNodeClick,
      handleTraceGapLoad,
      hideTooltip,
      showEdgeTransactionTooltip,
      showNodeTransactionTooltip,
      showSourceContractTooltip,
      showTooltip,
      traceGapActionLabel,
      traceGapError,
      traceGapLoading,
    ],
  )

  useLayoutEffect(() => {
    // Selecting an external-out also selects its parent route. Preserve the message selection
    // when the caller reflects that same parent back through selectedTransactionId.
    if (selectedTransactionId !== selectionRef.current?.transactionId) {
      updateSelection(selectedTransactionId ? {transactionId: selectedTransactionId} : undefined)
    }
  }, [selectedTransactionId, updateSelection])

  const deferredSelection = useDeferredValue(selection)
  const selectedTransaction =
    deferredSelection === selection && deferredSelection
      ? transactionMap.get(deferredSelection.transactionId)
      : undefined
  const selectedMessage =
    deferredSelection?.externalMessageIndex === undefined
      ? undefined
      : selectedTransaction?.transaction.outMessages.get(deferredSelection.externalMessageIndex)

  useLayoutEffect(() => {
    const wrapper = treeWrapperRef.current
    const treeGroup = wrapper?.querySelector<SVGGElement>(".rd3t-g")

    if (!wrapper || !treeGroup) {
      return
    }

    const wrapperRect = wrapper.getBoundingClientRect()
    const groupRect = treeGroup.getBoundingClientRect()

    if (groupRect.width === 0 || groupRect.height === 0) {
      return
    }

    const groupLeft = groupRect.left - wrapperRect.left
    const groupTop = groupRect.top - wrapperRect.top
    const nextLayout: TreeLayout = {
      height: Math.max(
        TREE_MIN_SIZE.height,
        Math.ceil(groupRect.height + TREE_PADDING.top + TREE_PADDING.bottom + TREE_DETAILS_GAP),
      ),
      width: Math.max(
        TREE_MIN_SIZE.width,
        Math.ceil(groupRect.width + TREE_PADDING.left + TREE_PADDING.right),
      ),
      translate: {
        x: Math.round(treeLayout.translate.x + TREE_PADDING.left - groupLeft),
        y: Math.round(treeLayout.translate.y + TREE_PADDING.top - groupTop),
      },
    }

    const isSameLayout =
      Math.abs(treeLayout.height - nextLayout.height) <= 1 &&
      Math.abs(treeLayout.width - nextLayout.width) <= 1 &&
      Math.abs(treeLayout.translate.x - nextLayout.translate.x) <= 1 &&
      Math.abs(treeLayout.translate.y - nextLayout.translate.y) <= 1

    if (!isSameLayout) {
      setTreeLayout(nextLayout)
    }
  }, [treeData, treeLayout])

  useLayoutEffect(() => {
    const container = treeContainerRef.current
    const wrapper = treeWrapperRef.current
    const selectedId = selection?.transactionId
    selectedNodeRef.current?.classList.remove(styles.transactionNodeSelected)
    selectedNodeRef.current
      ?.querySelector<SVGCircleElement>('circle[role="button"]')
      ?.setAttribute("aria-pressed", "false")
    selectedNodeRef.current = null

    if (!container || !wrapper || !selectedId) {
      return
    }

    // react-d3-tree invalidates every Node when its data changes. Selection is a visual overlay,
    // so update only the matching SVG group and keep the structural tree data immutable.
    const selectedNodeGroup = wrapper.querySelector<SVGGElement>(
      selection.externalMessageIndex === undefined
        ? `g[data-transaction-id="${CSS.escape(selectedId)}"]`
        : `g[data-external-message-id="${CSS.escape(`${selectedId}:${selection.externalMessageIndex}`)}"]`,
    )
    const selectedNode = selectedNodeGroup?.querySelector<SVGCircleElement>('circle[role="button"]')
    if (!selectedNodeGroup || !selectedNode) {
      return
    }

    selectedNodeGroup.classList.add(styles.transactionNodeSelected)
    selectedNode.setAttribute("aria-pressed", "true")
    selectedNodeRef.current = selectedNodeGroup

    const containerRect = container.getBoundingClientRect()
    const nodeRect = selectedNode.getBoundingClientRect()
    const inlineMargin = Math.min(96, container.clientWidth / 4)
    const nodeLeft = nodeRect.left - containerRect.left
    const nodeRight = nodeRect.right - containerRect.left

    if (nodeLeft >= inlineMargin && nodeRight <= container.clientWidth - inlineMargin) {
      return
    }

    const nodeCenter = container.scrollLeft + nodeLeft + nodeRect.width / 2
    const maxScrollLeft = container.scrollWidth - container.clientWidth
    const nextScrollLeft = Math.max(
      0,
      Math.min(maxScrollLeft, nodeCenter - container.clientWidth / 2),
    )

    if (Math.abs(container.scrollLeft - nextScrollLeft) > 1) {
      container.scrollTo({left: nextScrollLeft})
    }
  }, [selection, renderCustomNodeElement, treeData, treeLayout])

  useLayoutEffect(() => {
    const container = treeContainerRef.current
    const wrapper = treeWrapperRef.current
    if (
      !container ||
      !wrapper ||
      !highlightedTransactionIds ||
      highlightedTransactionIds.size === 0
    ) {
      return
    }

    const highlightedNodes = [
      ...wrapper.querySelectorAll<SVGCircleElement>('circle[aria-label^="Transaction "]'),
    ].filter(node => {
      const label = node.getAttribute("aria-label") ?? ""
      const id = label.slice("Transaction ".length)
      return highlightedTransactionIds.has(id)
    })

    if (highlightedNodes.length === 0) {
      return
    }

    const containerRect = container.getBoundingClientRect()
    const nodeRects = highlightedNodes.map(node => node.getBoundingClientRect())
    const minLeft = Math.min(...nodeRects.map(rect => rect.left)) - containerRect.left
    const maxRight = Math.max(...nodeRects.map(rect => rect.right)) - containerRect.left
    const inlineMargin = Math.min(96, container.clientWidth / 4)
    const visibleLeft = inlineMargin
    const visibleRight = container.clientWidth - inlineMargin

    if (minLeft >= visibleLeft && maxRight <= visibleRight) {
      return
    }

    const timeoutId = globalThis.setTimeout(() => {
      const highlightedCenter = container.scrollLeft + minLeft + (maxRight - minLeft) / 2
      const maxScrollLeft = container.scrollWidth - container.clientWidth
      const nextScrollLeft = Math.max(
        0,
        Math.min(maxScrollLeft, highlightedCenter - container.clientWidth / 2),
      )

      if (Math.abs(container.scrollLeft - nextScrollLeft) > 1) {
        container.scrollTo({left: nextScrollLeft, behavior: "smooth"})
      }
    }, ACTION_HIGHLIGHT_SCROLL_DELAY_MS)

    return () => globalThis.clearTimeout(timeoutId)
  }, [highlightedTransactionIds, treeLayout])

  return (
    <div className={styles.container}>
      <div
        className={styles.treeContainer}
        ref={treeContainerRef}
        style={{height: `${treeLayout.height}px`}}
      >
        <div
          className={styles.treeWrapper}
          ref={treeWrapperRef}
          style={{width: `${treeLayout.width}px`}}
        >
          <TransactionTreeCanvas
            data={treeData}
            translate={treeLayout.translate}
            renderNode={renderCustomNodeElement}
          />
          {tooltip && triggerRectReference.current && (
            <SmartTooltip
              content={tooltip.content}
              triggerRect={triggerRectReference.current}
              onMouseEnter={() => {
                setIsTooltipHovered(true)
              }}
              onMouseLeave={() => {
                setIsTooltipHovered(false)
              }}
              onForceHide={forceHideTooltip}
              calculateOptimalPosition={calculateOptimalPosition}
            />
          )}
        </div>
      </div>

      {selectedTransaction && (
        <div className={styles.transactionDetails}>
          <div className={styles.transactionDetailsCard}>
            {selectedMessage?.info.type === "external-out" ? (
              <ExternalOutMessageDetails
                key={`${selectedTransaction.id}:${deferredSelection?.externalMessageIndex}`}
                message={{...selectedMessage, info: selectedMessage.info}}
                contracts={contracts}
                additionalAbis={additionalAbis}
                onCellInspect={onCellInspect}
                onContractClick={onContractClick}
                renderAddressChip={renderAddressChip}
              />
            ) : (
              <MemoizedTransactionDetails
                tx={selectedTransaction}
                contracts={contracts}
                compilerAbisByCodeHash={compilerAbisByCodeHash}
                verifiedSourcesByCodeHash={verifiedSourcesByCodeHash}
                resolveVerifiedSourceByCodeHash={resolveVerifiedSourceByCodeHash}
                allContracts={allContracts}
                onCellInspect={onCellInspect}
                onContractClick={onContractClick}
                renderSourceLocation={renderSourceLocation}
                loadActions={loadActions}
                renderMessageRouteAction={renderSelectedTransactionMessageRouteAction}
                getBlockPath={getBlockPath}
                onBlockClick={onBlockClick}
              />
            )}
          </div>
          {!selectedMessage && renderSelectedTransactionExtra?.(selectedTransaction)}
        </div>
      )}
    </div>
  )
}

export const TransactionTree = memo(TransactionTreeComponent)

function formatAddress(address: Address | undefined, contracts: Map<string, ContractData>): string {
  if (!address) {
    return "unknown"
  }

  const displayAddress = address.toString({testOnly: true})
  const addressString = address.toString()
  const meta = contracts.get(addressString)
  if (meta) {
    const name = meta.displayName
    if (name !== "Unknown Contract") {
      return name
    }
  }

  return shortenMiddle(displayAddress, {start: 5, end: 5, separator: "..."})
}

function getSharedInternalSource(
  rootTransactions: readonly TransactionInfo[],
): Address | undefined {
  if (rootTransactions.length === 0) {
    return undefined
  }

  const firstInMessage = rootTransactions[0]?.transaction.inMessage
  if (firstInMessage?.info.type !== "internal") {
    return undefined
  }

  const source = firstInMessage.info.src
  const sourceAddress = source.toString()

  const allShareSameInternalSource = rootTransactions.every(tx => {
    const inMessage = tx.transaction.inMessage
    return inMessage?.info.type === "internal" && inMessage.info.src.toString() === sourceAddress
  })

  return allShareSameInternalSource ? source : undefined
}
