use crate::common::{assert_ui, strip_ansi};
use crate::regex;
use snapbox::IntoData;
use snapbox::filter::Filter;
use std::path::Path;

pub(crate) fn normalize_output(stdout: &str, project_path: &Path) -> String {
    normalize_output_internal(stdout, project_path, true)
}

#[allow(dead_code)]
pub(crate) fn normalize_output_keep_ansi(stdout: &str, project_path: &Path) -> String {
    normalize_output_internal(stdout, project_path, false)
}

fn normalize_output_internal(stdout: &str, project_path: &Path, strip: bool) -> String {
    let content = if strip {
        strip_ansi(stdout)
    } else {
        stdout.to_string()
    };
    let content = content.into_data();
    let content = snapbox::filter::FilterPaths.filter(content.into_data());
    let content = snapbox::filter::FilterNewlines.filter(content);
    let content = content.render().expect("came in as a String");

    let assert1 = assert_ui();
    let mut redactions = assert1.redactions().clone();

    let mut tmp_dir = project_path.to_string_lossy().to_string();
    if cfg!(windows) {
        // since Windows uses backslashes `\` as separators,
        // while snapshots use Unix paths and slashes `/`,
        // we will explicitly replace Windows separators with Unix separators in this case
        tmp_dir = tmp_dir.replace("\\", "/");
    }

    let current_version = env!("CARGO_PKG_VERSION");

    let lib_dir = Path::new(tmp_dir.as_str()).parent().unwrap().join("lib");
    redactions.insert("[ROOT]", tmp_dir.clone()).unwrap();
    redactions.insert("[ACTON_LIB]", lib_dir.clone()).unwrap();
    redactions
        .insert(
            "[ACTON_LIB]",
            "/private".to_owned() + lib_dir.to_str().unwrap(),
        )
        .unwrap();
    redactions
        .insert(
            "[DATE]",
            regex!(r"\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}\.\d{3}[+-]\d{2}:\d{2}"),
        )
        .unwrap();
    redactions
        .insert("[DURATION]", regex!(r"duration='\d+'"))
        .unwrap();
    redactions
        .insert("[TIME]", regex!(r#"time="\d+\.\d+""#))
        .unwrap();
    redactions
        .insert("[TIMESTAMP]", regex!(r"Timestamp: \d+"))
        .unwrap();
    redactions
        .insert("[ROOT]", "/private".to_owned() + tmp_dir.as_str())
        .unwrap();
    redactions
        .insert("[BOC_HEX]", regex!("b5ee[\\d\\w]*"))
        .unwrap();
    redactions
        .insert("[MAYBE_UNIX_TIME_VALUE]", regex!(" = 17\\d+"))
        .unwrap();
    redactions
        .insert(
            "[GRAPHVIZ_VERSION]",
            regex!("Generated by graphviz version \\d+\\.\\d+\\.\\d+"),
        )
        .unwrap();
    redactions
        .insert("[WALLET_ADDRESS]", regex!("Wallet address is .*"))
        .unwrap();
    redactions
        .insert("[GLOBAL_WALLET_ADDRESS]", regex!("global-wallet .*"))
        .unwrap();
    redactions
        .insert("[LOCAL_WALLET_ADDRESS]", regex!("local-wallet .*"))
        .unwrap();
    redactions
        .insert("[WALLET_ADDRESS_TESTNET]", regex!("address-testnet = .*"))
        .unwrap();
    redactions
        .insert("[MNEMONIC]", regex!(r#"mnemonic = "[^"]*""#))
        .unwrap();
    redactions
        .insert(
            "[SECURITY_WARNING_MNEMONIC]",
            regex!(r"- The mnemonic is stored in plain text in .*"),
        )
        .unwrap();
    redactions
        .insert(
            "[SYMLINK_CREATED]",
            regex!(r"✓ Created symlink global.wallets.toml -> .*"),
        )
        .unwrap();
    redactions
        .insert(
            "[WALLET_CREATED_ADDED]",
            regex!(r"✓ Wallet successfully created and added to .*"),
        )
        .unwrap();
    redactions
        .insert("[DEPLOYED_AT]", regex!(r"Deployed at: .*"))
        .unwrap();
    redactions
        .insert(
            "[GENERATED_ON]",
            regex!(r"Generated on: \d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2}"),
        )
        .unwrap();
    redactions
        .insert("[ACTON_VERSION]", format!("v{}", current_version))
        .unwrap();
    redactions
        .insert("[ACTON_DOCS_URL]", "https://i582.github.io/acton/docs")
        .unwrap();

    redactions.redact(&content)
}
