[graph]
all-features = true

[licenses]
allow = [
  "Apache-2.0",
  "BSD-2-Clause",
  "BSD-3-Clause",
  "BSL-1.0",
  "ISC",
  "MIT",
  "MIT-0",
  "Unicode-3.0",
  "Zlib",
]
confidence-threshold = 0.8
exceptions = []
unused-allowed-license = "deny"
unused-license-exception = "deny"

[advisories]
ignore = [
  "RUSTSEC-2024-0388", # derivative via ton_liteapi -> ton
]

[bans]
multiple-versions = "allow"
wildcards = "deny"
allow-wildcard-paths = true
highlight = "all"
workspace-default-features = "allow"
external-default-features = "allow"

[bans.workspace-dependencies]
duplicates = "deny"
include-path-dependencies = true
unused = "deny"

[sources]
unknown-registry = "deny"
unknown-git = "deny"
unused-allowed-source = "deny"
