import {generateFiles} from "fumadocs-openapi"
import {openapi} from "../src/lib/openapi"

await generateFiles({
  input: openapi,
  output: "./content/docs",
  per: "tag",
  includeDescription: true,
  addGeneratedComment: "@generated by `bun run generated-source`. Do not edit directly.",
  name: () => "localnet/control-api",
  frontmatter: (title, description) => ({
    title,
    description: description ?? "",
    sidebarTitle: "Control API",
  }),
})
