import {generateFiles} from "fumadocs-openapi"
import {openapi} from "../src/lib/openapi"

await generateFiles({
  input: openapi,
  output: "./content/docs",
  per: "tag",
  includeDescription: true,
  addGeneratedComment: "@generated by `bun run generated-source`. Do not edit directly.",
  name: () => "simulator/control-api",
  frontmatter: (_title, description) => ({
    title: "Simulator Control API",
    description: description ?? "",
    sidebarTitle: "Control API",
  }),
  beforeWrite(files) {
    for (const file of files) {
      file.content = file.content.replace(
        /\n---\n/,
        '\n---\n\n<AvailabilityBadge since="Acton 1.2" />\n',
      )
    }
  },
})
