[package]
name = "acton-lang-macros"
description = "Marker macros for the Acton Rust TON contract DSL"
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
repository.workspace = true
license.workspace = true
publish = false

[lib]
proc-macro = true

[lints]
workspace = true
