import {CopyValueButton, useToast} from "@acton/shared-ui"
import {CircleAlert, Plus, Trash2, Upload} from "lucide-react"
import type {FC, FormEvent, JSX} from "react"
import {useCallback, useEffect, useMemo, useState} from "react"

import type {
  SourceBundle,
  SourceCompiler,
  SourceFile,
  VerificationSourceResponse,
} from "../api/types"
import {Breadcrumbs} from "../components/Breadcrumbs"
import {InlineActionButton, InlineActionGroup} from "../components/InlineActionButton"
import {JsonUploadField} from "../components/JsonUploadField"
import {normalizeCodeHash} from "../metadata/codeHash"
import {useMetadataRegistry} from "../metadata/MetadataRegistryProvider"
import {sourceRegistrationFromResponse} from "../metadata/sourceRegistration"
import type {RegisteredSource} from "../metadata/types"

import styles from "./SourceCatalogPage.module.css"

interface SourceCatalogState {
  readonly loading: boolean
  readonly sources: readonly RegisteredSource[]
}

interface SourceTableEntry {
  readonly codeHash: string
  readonly entrypoint: string
  readonly compiler: string
  readonly files: number
  readonly savedAt: number
}

const SOURCE_UPLOAD_ERROR =
  "Uploaded JSON must be a source artifact generated by acton build --output-sources."

export const SourceCatalogPage: FC = () => {
  const metadataRegistry = useMetadataRegistry()
  const {showToast} = useToast()
  const [state, setState] = useState<SourceCatalogState>({loading: true, sources: []})
  const [sourceJson, setSourceJson] = useState("")
  const [sourceFormExpanded, setSourceFormExpanded] = useState(false)

  const loadSources = useCallback(async () => {
    setState(current => ({...current, loading: true}))
    const sources = await metadataRegistry.listSources()
    setState({loading: false, sources})
  }, [metadataRegistry])

  useEffect(() => {
    let isActive = true
    setState(current => ({...current, loading: true}))
    metadataRegistry
      .listSources()
      .then(sources => {
        if (isActive) {
          setState({loading: false, sources})
        }
      })
      .catch(error => {
        if (isActive) {
          console.debug("Failed to load registered sources", error)
          setState({loading: false, sources: []})
        }
      })

    return () => {
      isActive = false
    }
  }, [metadataRegistry])

  const handleSourceUpload = async (event: FormEvent) => {
    event.preventDefault()

    try {
      const source = parseSourceArtifact(sourceJson)
      const registration = sourceRegistrationFromResponse(source)
      if (!registration) {
        throw new Error(SOURCE_UPLOAD_ERROR)
      }

      await metadataRegistry.registerSources([registration])
      setSourceJson("")
      setSourceFormExpanded(false)
      showToast({
        description: "Source registered",
        variant: "success",
      })
      await loadSources()
    } catch (error) {
      showToast({
        description: error instanceof Error ? error.message : "Failed to register source",
        variant: "error",
      })
    }
  }

  const handleDeleteSource = async (codeHash: string) => {
    try {
      await metadataRegistry.deleteSource(codeHash)
      showToast({
        description: "Source deleted",
        variant: "success",
      })
      await loadSources()
    } catch (error) {
      showToast({
        description: error instanceof Error ? error.message : "Failed to delete source",
        variant: "error",
      })
    }
  }

  const tableEntries = useMemo(() => state.sources.map(sourceToTableEntry), [state.sources])
  const canSubmit = metadataRegistry.canWriteSources && sourceJson.trim().length > 0
  const toggleSourceForm = () => setSourceFormExpanded(expanded => !expanded)

  return (
    <section className={styles.container}>
      <Breadcrumbs items={[{label: "Sources"}]} />
      <div className={styles.hero}>
        <h1 className={styles.title}>Sources</h1>
      </div>

      <section className={styles.tableFrame}>
        <header className={styles.tableTitle}>Registered Sources</header>
        {state.loading ? (
          <SourceCatalogSkeleton />
        ) : (
          <div className={styles.tableScroller}>
            <table className={styles.table}>
              <thead>
                <tr>
                  <th>Entrypoint</th>
                  <th>Code hash</th>
                  <th>Compiler</th>
                  <th>Files</th>
                  <th>Uploaded at</th>
                </tr>
              </thead>
              <tbody>
                <tr className={styles.formButtonRow}>
                  <td colSpan={5}>
                    <button
                      type="button"
                      className={styles.registerSourceButton}
                      aria-expanded={sourceFormExpanded}
                      onClick={toggleSourceForm}
                    >
                      <Plus size={16} />
                      <span>Register source</span>
                    </button>
                  </td>
                </tr>
                {sourceFormExpanded && (
                  <tr className={styles.expandedFormRow}>
                    <td colSpan={5}>
                      <form className={styles.sourceInlineForm} onSubmit={handleSourceUpload}>
                        <JsonUploadField
                          label="Source artifact JSON"
                          value={sourceJson}
                          onChange={setSourceJson}
                        />
                        <p className={styles.localNote}>
                          <CircleAlert size={15} />
                          <span>
                            Source artifacts are stored locally for this explorer and are not
                            uploaded to a remote server.
                          </span>
                        </p>
                        <button
                          type="submit"
                          className={styles.primaryButton}
                          disabled={!canSubmit}
                        >
                          <Upload size={15} />
                          Register source
                        </button>
                      </form>
                    </td>
                  </tr>
                )}
                {tableEntries.length === 0 ? (
                  <tr>
                    <td colSpan={5}>
                      <div className={styles.empty}>No sources registered</div>
                    </td>
                  </tr>
                ) : (
                  tableEntries.map(entry => (
                    <tr key={entry.codeHash} className={styles.tableRow}>
                      <td>
                        <InlineActionGroup className={styles.nameCell} spacing="loose">
                          <div className={styles.entrypointCell}>
                            <span>{entry.entrypoint}</span>
                          </div>
                          {metadataRegistry.canWriteSources && (
                            <InlineActionButton
                              type="button"
                              onClick={() => {
                                void handleDeleteSource(entry.codeHash)
                              }}
                              variant="danger"
                              aria-label="Delete source"
                              title="Delete source"
                            >
                              <Trash2 size={13} />
                            </InlineActionButton>
                          )}
                        </InlineActionGroup>
                      </td>
                      <td>
                        <div className={styles.codeHashCell}>
                          <span className={styles.codeHash} title={entry.codeHash}>
                            {shortCodeHash(entry.codeHash)}
                          </span>
                          <CopyValueButton
                            className={styles.hashCopyButton}
                            value={entry.codeHash}
                            label="code hash"
                          />
                        </div>
                      </td>
                      <td>{entry.compiler}</td>
                      <td>{entry.files}</td>
                      <td>{formatSavedAt(entry.savedAt)}</td>
                    </tr>
                  ))
                )}
              </tbody>
            </table>
          </div>
        )}
      </section>
    </section>
  )
}

function parseSourceArtifact(raw: string): VerificationSourceResponse {
  let parsed: unknown
  try {
    parsed = JSON.parse(raw)
  } catch {
    throw new Error(SOURCE_UPLOAD_ERROR)
  }

  if (!isVerificationSourceResponse(parsed)) {
    throw new Error(SOURCE_UPLOAD_ERROR)
  }

  return parsed
}

function isVerificationSourceResponse(value: unknown): value is VerificationSourceResponse {
  if (!isRecord(value)) {
    return false
  }
  const codeHash =
    typeof value.code_hash === "string" ? normalizeCodeHash(value.code_hash) : undefined
  return (
    Boolean(codeHash) &&
    typeof value.verified === "boolean" &&
    Array.isArray(value.bundles) &&
    value.bundles.length > 0 &&
    value.bundles.every(isSourceBundle)
  )
}

function isSourceBundle(value: unknown): value is SourceBundle {
  return (
    isRecord(value) &&
    typeof value.source_bundle_hash === "string" &&
    typeof value.verified_at === "number" &&
    typeof value.storage_revision === "string" &&
    typeof value.entrypoint === "string" &&
    isSourceCompiler(value.compiler) &&
    Array.isArray(value.files) &&
    value.files.length > 0 &&
    value.files.every(isSourceFile)
  )
}

function isSourceCompiler(value: unknown): value is SourceCompiler {
  return (
    isRecord(value) &&
    typeof value.language === "string" &&
    typeof value.version === "string" &&
    "params" in value
  )
}

function isSourceFile(value: unknown): value is SourceFile {
  return (
    isRecord(value) &&
    typeof value.path === "string" &&
    typeof value.content_hash === "string" &&
    isNullableBool(value.include_in_command) &&
    isNullableBool(value.is_stdlib) &&
    isNullableBool(value.has_include_directives) &&
    typeof value.content === "string"
  )
}

function isRecord(value: unknown): value is Record<string, unknown> {
  return typeof value === "object" && value !== null && !Array.isArray(value)
}

function isNullableBool(value: unknown): value is boolean | null {
  return value === null || typeof value === "boolean"
}

function sourceToTableEntry(source: RegisteredSource): SourceTableEntry {
  const firstBundle = source.source.bundles[0]
  const files = source.source.bundles.reduce((count, bundle) => count + bundle.files.length, 0)
  return {
    codeHash: source.codeHash,
    entrypoint: firstBundle?.entrypoint ?? "unknown",
    compiler: firstBundle ? formatCompiler(firstBundle.compiler) : "unknown",
    files,
    savedAt: source.savedAt,
  }
}

function formatCompiler(compiler: SourceCompiler): string {
  const language = compiler.language || "unknown"
  const version = compiler.version ? ` ${compiler.version}` : ""
  return `${language}${version}`
}

function formatSavedAt(savedAt: number): string {
  if (!Number.isFinite(savedAt) || savedAt <= 0) {
    return "unknown"
  }
  return new Intl.DateTimeFormat(undefined, {
    dateStyle: "medium",
    timeStyle: "short",
  }).format(savedAt)
}

function shortCodeHash(codeHash: string): string {
  return codeHash.length > 18 ? `${codeHash.slice(0, 10)}…${codeHash.slice(-6)}` : codeHash
}

function SourceCatalogSkeleton(): JSX.Element {
  return (
    <div className={styles.skeletonList} aria-label="Loading registered sources">
      {Array.from({length: 5}, (_, index) => (
        <div key={index} className={styles.skeletonRow}>
          <span />
          <span />
          <span />
        </div>
      ))}
    </div>
  )
}
