[package]
name = "counter-contract"
description = "Minimal Counter contract written with the Acton Rust DSL"
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
repository.workspace = true
license.workspace = true
publish = false

[dependencies]
acton-lang.workspace = true

[lints]
workspace = true

[lib]
crate-type = ["rlib"]
