use super::method_model::{
    MethodKind, ReturnKind, classify_method, collect_call_targets, extract_method_dictionary,
    infer_params_for_method, infer_return_kind, render_method_signature,
};
use super::render::format_instruction_line;
use super::stage_patterns::{MethodPatterns, apply_pattern_rewrites};
use super::stage_stack::{LiftContext, LiftResult, LiftState, lift_instructions};
use crate::decompile::Disassembler;
use crate::types::{Code, Instruction, Method};
use anyhow::{Context, anyhow};
use std::fmt::Write as _;
use tycho_types::boc::Boc;
use tycho_types::cell::Cell;

#[derive(Debug, Clone)]
pub struct FuncDecompilerOptions {
    pub include_raw_tasm_fallback: bool,
    pub max_raw_tasm_lines_per_method: usize,
}

fn stdlib_include_path() -> String {
    "stdlib.fc".to_string()
}

fn initial_stack_params_for_method(kind: MethodKind, params: &[String]) -> Vec<String> {
    if kind == MethodKind::RecvInternal {
        return vec![
            "balance".to_string(),
            "msg_value".to_string(),
            "in_msg_full".to_string(),
            "in_msg_body".to_string(),
        ];
    }
    params.to_vec()
}

fn select_recv_internal_params(lines: &[String]) -> Vec<String> {
    if lines.iter().any(|line| contains_ident(line, "balance")) {
        vec![
            "balance".to_string(),
            "msg_value".to_string(),
            "in_msg_full".to_string(),
            "in_msg_body".to_string(),
        ]
    } else {
        vec![
            "msg_value".to_string(),
            "in_msg_full".to_string(),
            "in_msg_body".to_string(),
        ]
    }
}

fn contains_ident(text: &str, ident: &str) -> bool {
    let bytes = text.as_bytes();
    let needle = ident.as_bytes();
    if needle.is_empty() || bytes.len() < needle.len() {
        return false;
    }

    let mut i = 0;
    while i + needle.len() <= bytes.len() {
        if &bytes[i..i + needle.len()] == needle {
            let left_ok = i == 0 || !is_ident_char(bytes[i - 1]);
            let right_idx = i + needle.len();
            let right_ok = right_idx == bytes.len() || !is_ident_char(bytes[right_idx]);
            if left_ok && right_ok {
                return true;
            }
            i = right_idx;
        } else {
            i += 1;
        }
    }
    false
}

fn is_ident_char(ch: u8) -> bool {
    ch.is_ascii_alphanumeric() || ch == b'_'
}

impl Default for FuncDecompilerOptions {
    fn default() -> Self {
        Self {
            include_raw_tasm_fallback: true,
            max_raw_tasm_lines_per_method: 256,
        }
    }
}

#[derive(Debug)]
pub struct FuncDecompiler {
    disassembler: Disassembler,
    options: FuncDecompilerOptions,
}

impl Default for FuncDecompiler {
    fn default() -> Self {
        Self::new()
    }
}

impl FuncDecompiler {
    #[must_use]
    pub fn new() -> Self {
        Self::with_options(FuncDecompilerOptions::default())
    }

    #[must_use]
    pub fn with_options(options: FuncDecompilerOptions) -> Self {
        Self {
            disassembler: Disassembler::new(),
            options,
        }
    }

    pub fn decompile_cell(&self, cell: &Cell) -> anyhow::Result<String> {
        let code = self.disassembler.decompile_cell(cell)?;
        Ok(self.lift_code(&code))
    }

    pub fn decompile_boc(&self, boc: impl AsRef<[u8]>) -> anyhow::Result<String> {
        let cell = Boc::decode(boc.as_ref()).context("Failed to decode BoC bytes")?;
        self.decompile_cell(&cell)
    }

    pub fn decompile_boc_hex(&self, boc_hex: &str) -> anyhow::Result<String> {
        let cell = Boc::decode_hex(boc_hex.trim()).context("Failed to decode hex BoC string")?;
        self.decompile_cell(&cell)
    }

    pub fn decompile_boc_string(&self, boc_data: &str) -> anyhow::Result<String> {
        let data = boc_data.trim();
        if let Ok(cell) = Boc::decode_hex(data) {
            return self.decompile_cell(&cell);
        }
        if let Ok(cell) = Boc::decode_base64(data) {
            return self.decompile_cell(&cell);
        }
        Err(anyhow!("Failed to decode BoC string as hex or base64"))
    }

    #[must_use]
    pub fn lift_code(&self, code: &Code) -> String {
        let mut out = String::new();
        out.push_str(";; Auto-generated by tasm::func_decompile\n");
        out.push_str(";; Pipeline: stack-lift -> structured-flow -> pattern-rewrite -> fallback\n");
        let _ = writeln!(out, "#include \"{}\";", stdlib_include_path());
        out.push_str("#pragma version >=0.4.0;\n\n");

        let Some(dict) = extract_method_dictionary(code) else {
            out.push_str("() decompiled_entry() impure {\n");
            out.push_str(
                "    ;; No DICTPUSHCONST method table found; falling back to linear block\n",
            );
            let mut lift = LiftResult::default();
            let mut state = LiftState::default();
            let lift_ctx = LiftContext::default();
            lift_instructions(&code.instructions, &mut state, &mut lift.lines, 1, &lift_ctx);
            for line in &lift.lines {
                out.push_str(line);
                out.push('\n');
            }
            if self.options.include_raw_tasm_fallback {
                self.render_raw_fallback(&mut out, &code.instructions, 1);
            }
            out.push_str("}\n");
            return out;
        };

        let mut methods = dict.methods.clone();
        methods.sort_by_key(|m| m.id);
        let called_targets = collect_call_targets(&methods);
        let empty_ctx = LiftContext::default();
        let mut calldict_arity = std::collections::BTreeMap::new();
        for method in &methods {
            let patterns = MethodPatterns::analyze(method);
            let kind = classify_method(method, &called_targets, &patterns);
            let mut state = LiftState::default();
            let mut lines = Vec::new();
            lift_instructions(&method.instructions, &mut state, &mut lines, 1, &empty_ctx);
            let params = infer_params_for_method(kind, &state);
            calldict_arity.insert(method.id, params.len());
        }
        let lift_ctx = LiftContext {
            calldict_arity,
            ifjmp_unit_return: false,
        };

        let _ = writeln!(out, ";; recovered_methods: {}", methods.len());
        if !called_targets.is_empty() {
            let joined = called_targets
                .iter()
                .map(ToString::to_string)
                .collect::<Vec<_>>()
                .join(", ");
            let _ = writeln!(out, ";; call_dict_targets: {joined}");
        }
        out.push('\n');

        for method in &methods {
            let patterns = MethodPatterns::analyze(method);
            let kind = classify_method(method, &called_targets, &patterns);

            let mut infer_state = LiftState::default();
            let mut infer_lines = Vec::new();
            let method_lift_ctx = LiftContext {
                calldict_arity: lift_ctx.calldict_arity.clone(),
                ifjmp_unit_return: kind == MethodKind::RecvInternal,
            };

            lift_instructions(
                &method.instructions,
                &mut infer_state,
                &mut infer_lines,
                1,
                &method_lift_ctx,
            );
            let mut params = infer_params_for_method(kind, &infer_state);

            let mut state = LiftState::default();
            let initial_stack = initial_stack_params_for_method(kind, &params);
            state.seed_stack_with_exprs(&initial_stack);
            let mut lines = Vec::new();
            lift_instructions(
                &method.instructions,
                &mut state,
                &mut lines,
                1,
                &method_lift_ctx,
            );

            if kind == MethodKind::RecvInternal {
                params = select_recv_internal_params(&lines);
            }

            let return_kind = infer_return_kind(kind, &state);
            let param_types = params
                .iter()
                .map(|name| state.param_type(name))
                .collect::<Vec<_>>();
            out.push_str(&render_method_signature(
                method,
                kind,
                &params,
                &param_types,
                return_kind,
            ));
            out.push('\n');

            self.render_patterns(&mut out, method, &patterns, kind, &params);

            let mut rewritten = lines;
            apply_pattern_rewrites(&mut rewritten, &patterns);
            for line in &rewritten {
                out.push_str(line);
                out.push('\n');
            }

            if kind != MethodKind::RecvInternal
                && !state.has_explicit_return()
                && let Some(ret) = state.peek_expr_for_return()
            {
                match return_kind {
                    ReturnKind::Tuple => {
                        let _ = writeln!(out, "    return ({ret});");
                    }
                    ReturnKind::Unit => {}
                    _ => {
                        let _ = writeln!(out, "    return {ret};");
                    }
                }
            }

            if self.options.include_raw_tasm_fallback {
                self.render_raw_fallback(&mut out, &method.instructions, 1);
            }

            out.push_str("}\n\n");
        }

        out
    }

    fn render_patterns(
        &self,
        out: &mut String,
        method: &Method,
        patterns: &MethodPatterns,
        kind: MethodKind,
        params: &[String],
    ) {
        let _ = writeln!(out, "    ;; dict_method_id: {}", method.id);

        if kind == MethodKind::RecvInternal {
            out.push_str("    ;; recovered role: recv_internal handler\n");
        } else if kind == MethodKind::Getter {
            out.push_str("    ;; recovered role: get-method\n");
        } else if kind == MethodKind::Helper {
            out.push_str("    ;; recovered role: helper (called via CALLDICT)\n");
        }

        if !params.is_empty() {
            let _ = writeln!(out, "    ;; inferred params: {}", params.join(", "));
        }

        if patterns.has_bounce_guard {
            out.push_str("    ;; pattern: bounced message guard (msg_flags & 1)\n");
        }
        if patterns.has_empty_body_guard {
            out.push_str("    ;; pattern: empty body early return\n");
        }
        if patterns.has_op_and_query_id {
            out.push_str("    ;; pattern: body starts with op:uint32 and query_id:uint64\n");
        }

        if !patterns.opcodes.is_empty() {
            out.push_str("    ;; recovered opcode dispatch candidates:\n");
            for opcode in &patterns.opcodes {
                let _ = writeln!(out, "    ;;   if (op == 0x{opcode:08x}) {{ ... }}");
            }
        }

        if let Some(layout) = &patterns.storage_load_layout {
            let _ = writeln!(out, "    ;; storage load layout: {}", layout.join(" -> "));
        }
        if let Some(layout) = &patterns.storage_save_layout {
            let _ = writeln!(out, "    ;; storage save layout: {}", layout.join(" -> "));
        }

        if !patterns.call_targets.is_empty() {
            let joined = patterns
                .call_targets
                .iter()
                .map(ToString::to_string)
                .collect::<Vec<_>>()
                .join(", ");
            let _ = writeln!(out, "    ;; calls helpers: CALLDICT {joined}");
        }
        if !patterns.getglob_slots.is_empty() {
            let joined = patterns
                .getglob_slots
                .iter()
                .map(ToString::to_string)
                .collect::<Vec<_>>()
                .join(", ");
            let _ = writeln!(out, "    ;; reads globals: {joined}");
        }
        if !patterns.setglob_slots.is_empty() {
            let joined = patterns
                .setglob_slots
                .iter()
                .map(ToString::to_string)
                .collect::<Vec<_>>()
                .join(", ");
            let _ = writeln!(out, "    ;; writes globals: {joined}");
        }
        if patterns.has_raw_reserve {
            out.push_str("    ;; pattern: RAWRESERVE present\n");
        }
        if patterns.has_send_raw_msg {
            out.push_str("    ;; pattern: SENDRAWMSG present\n");
        }
        if patterns.has_set_code {
            out.push_str("    ;; pattern: SETCODE present (upgrade branch)\n");
        }
        if !patterns.throw_codes.is_empty() {
            let joined = patterns
                .throw_codes
                .iter()
                .map(ToString::to_string)
                .collect::<Vec<_>>()
                .join(", ");
            let _ = writeln!(out, "    ;; throw codes: {joined}");
        }
    }

    fn render_raw_fallback(&self, out: &mut String, instructions: &[Instruction], depth: usize) {
        let indent = "    ".repeat(depth);
        out.push_str(&indent);
        out.push_str(";; low-level fallback (TASM)\n");

        let max = if self.options.max_raw_tasm_lines_per_method == 0 {
            usize::MAX
        } else {
            self.options.max_raw_tasm_lines_per_method
        };

        for (idx, instruction) in instructions.iter().enumerate() {
            if idx >= max {
                let _ = writeln!(
                    out,
                    "{indent};; ... truncated {} instructions",
                    instructions.len().saturating_sub(idx)
                );
                break;
            }
            let _ = writeln!(
                out,
                "{indent};; {}",
                format_instruction_line(instruction, depth + 1)
            );
        }
    }
}
