//! Typed model of `validator-engine`'s generated `config.json`.
//!
//! The engine owns the file, while Localton owns a small set of deliberate changes:
//! its outbound port, authenticated control endpoint, and optional liteserver. A
//! complete model prevents those changes from becoming recursive string-key edits
//! over arbitrary JSON and makes an incompatible TON release fail during bootstrap.

use std::{fs, net::SocketAddrV4, path::Path};

use anyhow::{Context, Result};
use serde::{Deserialize, Serialize};

use crate::storage::write_json_atomic;

use super::types::{Ed25519PublicKey, KeyId, TonPublicKey};

const CONTROL_PERMISSIONS: i32 = 15;

/// Complete validator-engine configuration generated by the pinned TON release.
#[derive(Clone, Debug, Eq, PartialEq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub(crate) struct ValidatorEngineConfig {
    #[serde(rename = "@type")]
    constructor: ValidatorConfigConstructor,
    out_port: u16,
    addrs: Vec<EngineAddress>,
    adnl: Vec<EngineAdnl>,
    dht: Vec<EngineDht>,
    validators: Vec<EngineValidator>,
    #[serde(default)]
    collators: Vec<EngineValidator>,
    fullnode: KeyId,
    fullnodeslaves: Vec<FullNodeSlave>,
    fullnodemasters: Vec<FullNodeMaster>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    fullnodeconfig: Option<FullNodeConfig>,
    liteservers: Vec<EngineLiteserver>,
    control: Vec<EngineControlInterface>,
    #[serde(default)]
    shards_to_monitor: Vec<i64>,
    gc: EngineGc,
}

impl ValidatorEngineConfig {
    /// Reads a generated config and rejects missing, unknown, or mistyped fields.
    pub(crate) fn load(path: &Path) -> Result<Self> {
        let bytes = fs::read(path)
            .with_context(|| format!("failed to read validator config {}", path.display()))?;
        serde_json::from_slice(&bytes)
            .with_context(|| format!("invalid validator config {}", path.display()))
    }

    /// Persists one validated config through the state directory's atomic writer.
    pub(crate) fn save(&self, path: &Path) -> Result<()> {
        write_json_atomic(path, self)
            .with_context(|| format!("failed to write validator config {}", path.display()))
    }

    /// Replaces the engine's generated outbound ADNL port with the node-owned port.
    pub(crate) fn set_out_port(&mut self, port: u16) {
        self.out_port = port;
    }

    /// Installs the independent identities used for administration and lite queries.
    ///
    /// TON's JSON schema stores these ports as integers. Keeping construction here
    /// prevents callers from accidentally serializing a CLI-oriented string value.
    pub(crate) fn set_local_services(
        &mut self,
        console_port: u16,
        control_server: KeyId,
        control_client: KeyId,
        liteserver: Option<(u16, KeyId)>,
    ) {
        self.control = vec![EngineControlInterface {
            constructor: ControlInterfaceConstructor::Interface,
            id: control_server,
            port: console_port,
            allowed: vec![EngineControlProcess {
                constructor: ControlProcessConstructor::Process,
                id: control_client,
                permissions: CONTROL_PERMISSIONS,
            }],
        }];
        self.liteservers = liteserver
            .map(|(port, id)| EngineLiteserver {
                constructor: LiteserverConstructor::Liteserver,
                id,
                port,
            })
            .into_iter()
            .collect();
    }

    /// Removes every validator key so the engine runs as a plain full node.
    ///
    /// A hardfork block is only accepted when it sits exactly one block above the
    /// node's top block, and that top block can only be observed while nothing is
    /// producing new ones. Suspending validation freezes the chain without
    /// touching the keyring, and the removed entries are returned so the caller
    /// can put them back.
    pub(crate) fn suspend_validation(&mut self) -> Vec<EngineValidator> {
        std::mem::take(&mut self.validators)
    }

    /// Restores validator keys removed by [`Self::suspend_validation`].
    pub(crate) fn resume_validation(&mut self, validators: Vec<EngineValidator>) {
        self.validators = validators;
    }

    /// Returns whether the engine currently has any validator key.
    pub(crate) fn validates(&self) -> bool {
        !self.validators.is_empty()
    }

    /// Routes the node's block downloads to a local full-node master.
    ///
    /// `FullNodeImpl::get_query_sender` prefers this link over the public
    /// overlays, which is how a hand-built shard block reaches the node: it
    /// arrives as an ordinary download instead of a fork block, which the node
    /// refuses outside the masterchain. The link also silences outbound
    /// broadcasts, so it must be removed again once the block is applied.
    pub(crate) fn set_full_node_master(&mut self, address: SocketAddrV4, key: TonPublicKey) {
        self.fullnodeslaves = vec![FullNodeSlave {
            constructor: FullNodeSlaveConstructor::Slave,
            ip: u32::from(*address.ip()) as i32,
            port: address.port(),
            adnl: Ed25519PublicKey::new(key),
        }];
    }

    pub(crate) fn restore_full_node_master(&mut self, original: &Self) {
        self.fullnodeslaves = original.fullnodeslaves.clone();
    }

    /// Removes the full-node master link and returns the node to overlay mode.
    pub(crate) fn clear_full_node_master(&mut self) {
        self.fullnodeslaves.clear();
    }

    /// Returns keys already registered for an election round, if present.
    pub(crate) fn election_keys(&self, election_id: u32) -> Result<Option<ValidatorElectionKeys>> {
        self.validators
            .iter()
            .find(|validator| validator.election_date == election_id)
            .map(|validator| {
                let adnl = validator
                    .adnl_addrs
                    .first()
                    .context("existing election validator has no ADNL address")?;
                Ok(ValidatorElectionKeys {
                    signing_key: validator.id,
                    adnl: adnl.id,
                    election_end: validator.expire_at,
                })
            })
            .transpose()
    }

    /// Lists identities for which this engine must own private keyring files.
    ///
    /// Control clients and remote full nodes are intentionally excluded: their
    /// IDs authorize peers, while their private keys live outside this engine.
    pub(crate) fn private_key_ids(&self) -> Vec<KeyId> {
        let mut ids = vec![self.fullnode];
        ids.extend(self.adnl.iter().map(|entry| entry.id));
        ids.extend(self.dht.iter().map(|entry| entry.id));
        ids.extend(self.liteservers.iter().map(|entry| entry.id));
        ids.extend(self.control.iter().map(|entry| entry.id));
        for validator in self.validators.iter().chain(&self.collators) {
            ids.push(validator.id);
            ids.extend(validator.temp_keys.iter().map(|key| key.key));
            ids.extend(validator.adnl_addrs.iter().map(|address| address.id));
        }
        ids.sort_unstable();
        ids.dedup();
        ids
    }
}

/// Engine-owned keys that let election automation resume after a restart.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub(crate) struct ValidatorElectionKeys {
    pub(crate) signing_key: KeyId,
    pub(crate) adnl: KeyId,
    pub(crate) election_end: u32,
}

#[derive(Clone, Copy, Debug, Eq, PartialEq, Serialize, Deserialize)]
enum ValidatorConfigConstructor {
    #[serde(rename = "engine.validator.config")]
    Config,
}

#[derive(Clone, Debug, Eq, PartialEq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
struct EngineAddress {
    #[serde(rename = "@type")]
    constructor: AddressConstructor,
    ip: i32,
    port: u16,
    categories: Vec<i32>,
    priority_categories: Vec<i32>,
}

#[derive(Clone, Copy, Debug, Eq, PartialEq, Serialize, Deserialize)]
enum AddressConstructor {
    #[serde(rename = "engine.addr")]
    Address,
}

#[derive(Clone, Debug, Eq, PartialEq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
struct EngineAdnl {
    #[serde(rename = "@type")]
    constructor: AdnlConstructor,
    id: KeyId,
    category: i32,
}

#[derive(Clone, Copy, Debug, Eq, PartialEq, Serialize, Deserialize)]
enum AdnlConstructor {
    #[serde(rename = "engine.adnl")]
    Adnl,
}

#[derive(Clone, Debug, Eq, PartialEq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
struct EngineDht {
    #[serde(rename = "@type")]
    constructor: DhtConstructor,
    id: KeyId,
}

#[derive(Clone, Copy, Debug, Eq, PartialEq, Serialize, Deserialize)]
enum DhtConstructor {
    #[serde(rename = "engine.dht")]
    Dht,
}

#[derive(Clone, Debug, Eq, PartialEq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub(crate) struct EngineValidator {
    #[serde(rename = "@type")]
    constructor: ValidatorConstructor,
    id: KeyId,
    temp_keys: Vec<EngineValidatorTempKey>,
    adnl_addrs: Vec<EngineValidatorAdnlAddress>,
    election_date: u32,
    expire_at: u32,
}

#[derive(Clone, Copy, Debug, Eq, PartialEq, Serialize, Deserialize)]
enum ValidatorConstructor {
    #[serde(rename = "engine.validator")]
    Validator,
}

#[derive(Clone, Debug, Eq, PartialEq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
struct EngineValidatorTempKey {
    #[serde(rename = "@type")]
    constructor: ValidatorTempKeyConstructor,
    key: KeyId,
    expire_at: u32,
}

#[derive(Clone, Copy, Debug, Eq, PartialEq, Serialize, Deserialize)]
enum ValidatorTempKeyConstructor {
    #[serde(rename = "engine.validatorTempKey")]
    TempKey,
}

#[derive(Clone, Debug, Eq, PartialEq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
struct EngineValidatorAdnlAddress {
    #[serde(rename = "@type")]
    constructor: ValidatorAdnlAddressConstructor,
    id: KeyId,
    expire_at: u32,
}

#[derive(Clone, Copy, Debug, Eq, PartialEq, Serialize, Deserialize)]
enum ValidatorAdnlAddressConstructor {
    #[serde(rename = "engine.validatorAdnlAddress")]
    Address,
}

#[derive(Clone, Debug, Eq, PartialEq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
struct EngineLiteserver {
    #[serde(rename = "@type")]
    constructor: LiteserverConstructor,
    id: KeyId,
    port: u16,
}

#[derive(Clone, Copy, Debug, Eq, PartialEq, Serialize, Deserialize)]
enum LiteserverConstructor {
    #[serde(rename = "engine.liteServer")]
    Liteserver,
}

#[derive(Clone, Debug, Eq, PartialEq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
struct EngineControlInterface {
    #[serde(rename = "@type")]
    constructor: ControlInterfaceConstructor,
    id: KeyId,
    port: u16,
    allowed: Vec<EngineControlProcess>,
}

#[derive(Clone, Copy, Debug, Eq, PartialEq, Serialize, Deserialize)]
enum ControlInterfaceConstructor {
    #[serde(rename = "engine.controlInterface")]
    Interface,
}

#[derive(Clone, Debug, Eq, PartialEq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
struct EngineControlProcess {
    #[serde(rename = "@type")]
    constructor: ControlProcessConstructor,
    id: KeyId,
    permissions: i32,
}

#[derive(Clone, Copy, Debug, Eq, PartialEq, Serialize, Deserialize)]
enum ControlProcessConstructor {
    #[serde(rename = "engine.controlProcess")]
    Process,
}

#[derive(Clone, Debug, Eq, PartialEq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
struct FullNodeMaster {
    #[serde(rename = "@type")]
    constructor: FullNodeMasterConstructor,
    port: u16,
    adnl: KeyId,
}

#[derive(Clone, Copy, Debug, Eq, PartialEq, Serialize, Deserialize)]
enum FullNodeMasterConstructor {
    #[serde(rename = "engine.validator.fullNodeMaster")]
    Master,
}

#[derive(Clone, Debug, Eq, PartialEq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
struct FullNodeSlave {
    #[serde(rename = "@type")]
    constructor: FullNodeSlaveConstructor,
    ip: i32,
    port: u16,
    adnl: Ed25519PublicKey,
}

#[derive(Clone, Copy, Debug, Eq, PartialEq, Serialize, Deserialize)]
enum FullNodeSlaveConstructor {
    #[serde(rename = "engine.validator.fullNodeSlave")]
    Slave,
}

#[derive(Clone, Debug, Eq, PartialEq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
struct FullNodeConfig {
    #[serde(rename = "@type")]
    constructor: FullNodeConfigConstructor,
    ext_messages_broadcast_disabled: bool,
}

#[derive(Clone, Copy, Debug, Eq, PartialEq, Serialize, Deserialize)]
enum FullNodeConfigConstructor {
    #[serde(rename = "engine.validator.fullNodeConfig")]
    Config,
}

#[derive(Clone, Debug, Eq, PartialEq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
struct EngineGc {
    #[serde(rename = "@type")]
    constructor: GcConstructor,
    ids: Vec<KeyId>,
}

#[derive(Clone, Copy, Debug, Eq, PartialEq, Serialize, Deserialize)]
enum GcConstructor {
    #[serde(rename = "engine.gc")]
    Gc,
}

/// Converts the advertised IPv4 endpoint into the signed TL integer convention.
#[cfg(test)]
fn ton_ipv4(ip: std::net::Ipv4Addr) -> i32 {
    i32::from_be_bytes(ip.octets())
}

#[cfg(test)]
mod tests {
    use std::net::Ipv4Addr;

    use base64::{Engine, engine::general_purpose::STANDARD as BASE64};
    use expect_test::expect;

    use super::*;

    fn config_json() -> serde_json::Value {
        let id = BASE64.encode([1_u8; 32]);
        serde_json::json!({
            "@type": "engine.validator.config",
            "out_port": 3272,
            "addrs": [{
                "@type": "engine.addr",
                "ip": ton_ipv4(Ipv4Addr::LOCALHOST),
                "port": 4442,
                "categories": [0, 1, 2, 3],
                "priority_categories": [],
            }],
            "adnl": [],
            "dht": [],
            "validators": [],
            "collators": [],
            "fullnode": id,
            "fullnodeslaves": [],
            "fullnodemasters": [],
            "liteservers": [],
            "control": [],
            "shards_to_monitor": [],
            "gc": { "@type": "engine.gc", "ids": [] },
        })
    }

    #[test]
    fn service_configuration_uses_numeric_ports_and_typed_ids() {
        let mut config: ValidatorEngineConfig = serde_json::from_value(config_json()).unwrap();
        config.set_local_services(
            4441,
            KeyId::from_bytes([2; 32]),
            KeyId::from_bytes([3; 32]),
            Some((18_004, KeyId::from_bytes([4; 32]))),
        );
        let private_key_ids = config
            .private_key_ids()
            .into_iter()
            .map(KeyId::to_hex)
            .collect::<Vec<_>>()
            .join("\n");
        let value = serde_json::to_value(config).unwrap();

        assert_eq!(value["control"][0]["port"], 4441);
        assert_eq!(value["control"][0]["allowed"][0]["permissions"], 15);
        assert_eq!(value["liteservers"][0]["port"], 18_004);
        assert!(value["liteservers"][0]["port"].is_number());
        expect![[r#"
            0101010101010101010101010101010101010101010101010101010101010101
            0202020202020202020202020202020202020202020202020202020202020202
            0404040404040404040404040404040404040404040404040404040404040404"#]]
        .assert_eq(&private_key_ids);
    }
}
