[package]
name = "faucet-antifraud"
version = { workspace = true }
publish = { workspace = true }
authors = { workspace = true }
edition = { workspace = true }
rust-version = { workspace = true }
repository = { workspace = true }

[dependencies]
faucet-config = { workspace = true }

[lib]
doctest = false
