name: Attach TON Objs to releases

on:
  workflow_call:
    inputs:
      plan:
        required: false
        type: string

concurrency:
  group: attach-objs-to-releases-${{ github.ref }}
  cancel-in-progress: true

permissions: { }

jobs:
  attach-objs:
    name: Attach TON Objs to releases
    runs-on: ubicloud-standard-2-ubuntu-2204

    permissions:
      contents: read

    steps:
      - name: Download TON objects release archives
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          gh release download release-objs \
            --repo "${GITHUB_REPOSITORY}" \
            --pattern "ton-objs-*.tar.gz*" \
            --dir .

      - name: Upload TON objects archives as artifacts
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: artifacts-ton-objs
          path: |
            ton-objs-*.tar.gz
            ton-objs-*.tar.gz.sha256
          retention-days: 1
          if-no-files-found: error
