name: Build Actonscan backend Docker image

on:
  workflow_dispatch:

concurrency:
  group: build-actonscan-backend-docker-image-${{ github.ref }}
  cancel-in-progress: true

permissions: { }

jobs:
  build-actonscan-backend-docker-image:
    name: Build Actonscan backend Docker image
    runs-on: ubicloud-standard-2-ubuntu-2204

    permissions:
      contents: read
      packages: write

    steps:
      - name: Check out Acton repository
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@d7f5e7f509e45cec5c76c4d5afdd7de93d0b3df5 # v4.1.0
        with:
          cache-binary: false

      - name: Log in to GHCR
        uses: docker/login-action@650006c6eb7dba73a995cc03b0b2d7f5ca915bee # v4.2.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}

      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@030e881283bb7a6894de51c315a6bfe6a94e05cf # v6.0.0
        with:
          images: ghcr.io/ton-blockchain/actonscan-backend
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=ref,event=tag
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=sha,prefix=sha-
            type=raw,value=latest,enable={{is_default_branch}}

      - name: Build and push image
        uses: docker/build-push-action@f9f3042f7e2789586610d6e8b85c8f03e5195baf # v7.2.0
        env:
          DOCKER_BUILD_RECORD_UPLOAD: false
        with:
          context: .
          file: apps/actonscan-backend/Dockerfile
          platforms: linux/amd64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            BUILD_VERSION=${{ github.ref_name }}
            SOURCE_URL=https://github.com/${{ github.repository }}
            VCS_REF=${{ github.sha }}
          cache-from: type=gha,scope=actonscan-backend
          cache-to: type=gha,mode=max,scope=actonscan-backend
