name: Build Source Trace WASM

on:
  pull_request:
    branches:
      - master
    paths:
      - ".github/workflows/build-source-trace-wasm.yml"
      - "crates/acton-source-trace/**"
      - "crates/acton-source-trace-wasm/**"
  push:
    branches:
      - master
    paths:
      - ".github/workflows/build-source-trace-wasm.yml"
      - "crates/acton-source-trace/**"
      - "crates/acton-source-trace-wasm/**"
  workflow_dispatch:

concurrency:
  group: build-source-trace-wasm-${{ github.ref }}
  cancel-in-progress: true

permissions: { }

jobs:
  build:
    name: Build Source Trace WASM
    runs-on: ubicloud-standard-2-ubuntu-2204

    permissions:
      contents: read

    steps:
      - name: Fetch Sources
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: Installing additional Rust components
        uses: taiki-e/install-action@84f5ac3124727fb3d284d4d22ee9ab3654fd09a6 # v2.87.7
        with:
          tool: just@1.58.0,wasm-pack@0.15.0
          fallback: none

      - name: Run WASM
        run: just build-source-trace-wasm
