name: Build release binaries

on:
  workflow_call:
    inputs:
      plan:
        required: false
        type: string

concurrency:
  group: build-release-binaries-${{ github.ref }}
  cancel-in-progress: true

permissions: { }

jobs:
  build-linux:
    name: Build Acton (${{ matrix.arch }}-${{ matrix.vendor }}-${{ matrix.sys }}-${{ matrix.abi }})
    runs-on: ${{ matrix.runner }}
    strategy:
      matrix:
        include:
          - runner: ubicloud-standard-8-ubuntu-2204
            arch: x86_64
            vendor: unknown
            sys: linux
            abi: gnu
          - runner: ubicloud-standard-8-arm-ubuntu-2204
            arch: aarch64
            vendor: unknown
            sys: linux
            abi: gnu
    env:
      TARGET_NAME: ${{ matrix.arch }}-${{ matrix.vendor }}-${{ matrix.sys }}-${{ matrix.abi }}

    permissions:
      contents: read

    steps:
      - name: Check out Acton repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: Cache Cargo
        uses: Swatinem/rust-cache@c19371144df3bb44fab255c43d04cbc2ab54d1c4 # v2.9.1
        with:
          key: ${{ runner.os }}-${{ runner.arch }}
          save-if: false
          lookup-only: true

      - name: Install Rust
        run: rustup target add "${TARGET_NAME}"

      - name: Installing additional Rust components
        uses: taiki-e/install-action@15449e3094499af05d8d964a1c884208e4b8b595 # v2.81.11
        with:
          tool: just@1.49.0
          fallback: none

      - name: Install LLVM and Clang (don't cache)
        timeout-minutes: 10
        # language=Bash
        run: |
          wget https://apt.llvm.org/llvm.sh
          chmod +x llvm.sh
          sudo ./llvm.sh 16 clang
          rm llvm.sh

      - name: Download TON objects archive
        env:
          GH_TOKEN: ${{ github.token }}
        # language=Bash
        run: |
          ARCHIVE_NAME="ton-objs-${TARGET_NAME}.tar.gz"
          mkdir -p objs
          gh release download release-objs \
            --repo "${GITHUB_REPOSITORY}" \
            --pattern "${ARCHIVE_NAME}" \
            --dir "${RUNNER_TEMP}"
          tar -C objs -xzf "${RUNNER_TEMP}/${ARCHIVE_NAME}"

      - name: Setup Bun
        uses: oven-sh/setup-bun@0c5077e51419868618aeaa5fe8019c62421857d6 # v2.2.0
        with:
          no-cache: true

      - name: Build acton binary
        env:
          CC: clang-16
          CXX: clang++-16
        run: |
          just build-ui
          cargo build --profile release-size --locked --target "${TARGET_NAME}" --bin acton

      - name: Test acton binary
        run: |
          "./target/${TARGET_NAME}/release-size/acton" --help

      - name: Prepare Acton archive
        run: |
          cargo xtask dist archive --target "${TARGET_NAME}" --profile release-size

      - name: Upload Acton archive as artifact
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: artifacts-${{ env.TARGET_NAME }}
          path: |
            acton-${{ env.TARGET_NAME }}.tar.gz
            acton-${{ env.TARGET_NAME }}.tar.gz.sha256
          retention-days: 1
          if-no-files-found: error

  build-macos:
    name: Build Acton (${{ matrix.arch }}-${{ matrix.vendor }}-${{ matrix.sys }})
    runs-on: ${{ matrix.runner }}
    strategy:
      matrix:
        include:
          - runner: macos-15-intel
            arch: x86_64
            vendor: apple
            sys: darwin
          - runner: macos-15
            arch: aarch64
            vendor: apple
            sys: darwin
    env:
      TARGET_NAME: ${{ matrix.arch }}-${{ matrix.vendor }}-${{ matrix.sys }}

    permissions:
      contents: read

    steps:
      - name: Check out Acton repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: Cache Cargo
        uses: Swatinem/rust-cache@c19371144df3bb44fab255c43d04cbc2ab54d1c4 # v2.9.1
        with:
          key: ${{ runner.os }}-${{ runner.arch }}
          save-if: false
          lookup-only: true

      - name: Install Rust
        run: rustup target add "${TARGET_NAME}"

      - name: Installing additional Rust components
        uses: taiki-e/install-action@15449e3094499af05d8d964a1c884208e4b8b595 # v2.81.11
        with:
          tool: just@1.49.0
          fallback: none

      - name: Download TON objects archive
        env:
          GH_TOKEN: ${{ github.token }}
        # language=Bash
        run: |
          ARCHIVE_NAME="ton-objs-${TARGET_NAME}.tar.gz"
          mkdir -p objs
          gh release download release-objs \
            --repo "${GITHUB_REPOSITORY}" \
            --pattern "${ARCHIVE_NAME}" \
            --dir "${RUNNER_TEMP}"
          tar -C objs -xzf "${RUNNER_TEMP}/${ARCHIVE_NAME}"

      - name: Setup Bun
        uses: oven-sh/setup-bun@0c5077e51419868618aeaa5fe8019c62421857d6 # v2.2.0
        with:
          no-cache: true

      - name: Build acton binary
        run: |
          just build-ui
          cargo build --profile release-size --locked --target "${TARGET_NAME}" --bin acton

      - name: Test acton binary
        run: |
          "./target/${TARGET_NAME}/release-size/acton" --help

      - name: Prepare Acton archive
        run: |
          cargo xtask dist archive --target "${TARGET_NAME}" --profile release-size

      - name: Upload Acton archive as artifact
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: artifacts-${{ env.TARGET_NAME }}
          path: |
            acton-${{ env.TARGET_NAME }}.tar.gz
            acton-${{ env.TARGET_NAME }}.tar.gz.sha256
          retention-days: 1
          if-no-files-found: error

  generate-dist-manifest:
    name: Generate cargo-dist local manifest
    needs:
      - build-linux
      - build-macos
    runs-on: ubicloud-standard-2-ubuntu-2204
    env:
      DIST_TAG: ${{ fromJson(inputs.plan).announcement_tag }}
      LOCAL_DIST_MANIFEST: local-dist-manifest.json

    permissions:
      contents: read

    steps:
      - name: Check out Acton repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: Install cached dist
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
        with:
          name: cargo-dist-cache
          path: ~/.cargo/bin/

      - name: Fetch Acton archive artifacts
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
        with:
          pattern: artifacts-*
          path: target/distrib/
          merge-multiple: true

      - name: Generate cargo-dist local manifest
        shell: bash
        # language=Bash
        run: |
          chmod +x ~/.cargo/bin/dist

          dist manifest \
            --artifacts=local \
            --tag "${DIST_TAG}" \
            --allow-dirty \
            --output-format=json \
            --no-local-paths > "${LOCAL_DIST_MANIFEST}"

      - name: Generate cargo-dist release binaries manifest
        shell: bash
        # language=Bash
        run: |
          python3 .github/scripts/generate-checksums-dist-manifest.py \
            --manifest "${LOCAL_DIST_MANIFEST}" \
            --artifacts-dir target/distrib \
            --output target/distrib/acton-dist-manifest.json

          echo "manifest checksums generated successfully"
          cat target/distrib/acton-dist-manifest.json

      - name: Upload cargo-dist local manifest
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: artifacts-build-release-binaries-dist-manifest
          path: target/distrib/acton-dist-manifest.json
          retention-days: 1
          if-no-files-found: error
