name: CI

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions: { }

env:
  ENABLE_MIRRORING_RELEASE: 'true'
  PUBLIC_ACTON_REPOSITORY: i582/acton-public

jobs:
  build-linux:
    name: Build (${{ matrix.os }}-${{ matrix.arch }})
    strategy: &runner_linux_strategy
      matrix:
        include:
          - runner: ubicloud-standard-4-ubuntu-2204
            os: linux
            arch: x86_64
    runs-on: ${{ matrix.runner }}
    if: true
    env:
      OBJS_NAME: ton-objs-${{ matrix.os }}-${{ matrix.arch }}
      TARGET_NAME: ${{ matrix.arch }}-unknown-${{ matrix.os }}-gnu

    permissions:
      contents: read

    steps:
      - name: Check out Acton repository
        uses: actions/checkout@v6
        with:
          persist-credentials: false

      - name: Cache Cargo
        uses: Swatinem/rust-cache@779680da715d629ac1d338a641029a2f4372abb5 # v2.8.2
        with:
          key: ${{ matrix.runner }}
          save-if: ${{ github.ref == 'refs/heads/master' }}

      - name: Install Rust
        run: rustup toolchain install

      - name: Installing additional Rust components
        uses: taiki-e/install-action@d6e286fa45544157a02d45a43742857ebbc25d12 # v2.68.16
        with:
          tool: nextest,just

      - name: Download TON objects archive
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          ARCHIVE_NAME="${OBJS_NAME}.tar.gz"
          mkdir -p objs
          gh release download trunk-objs \
            --repo "${GITHUB_REPOSITORY}" \
            --pattern "${ARCHIVE_NAME}" \
            --dir "${RUNNER_TEMP}"
          tar -C objs -xzf "${RUNNER_TEMP}/${ARCHIVE_NAME}"

      - name: Install LLVM and Clang
        run: |
          wget https://apt.llvm.org/llvm.sh
          chmod +x llvm.sh
          sudo ./llvm.sh 16 clang
          rm llvm.sh

      - name: Setup Bun
        uses: oven-sh/setup-bun@ecf28ddc73e819eb6fa29df6b34ef8921c743461 # v2.1.3

      - name: Build acton binary
        env:
          ACTON_RELEASE_CHANNEL: trunk
          CC: clang-16
          CXX: clang++-16
        run: |
          just build-ui
          cargo build --release --locked --target "${TARGET_NAME}" --bin acton

      - name: Add acton to PATH
        run: echo "${GITHUB_WORKSPACE}/target/${TARGET_NAME}/release" >> "$GITHUB_PATH"

      - name: Test acton binary
        run: |
          acton --help

      - name: Run tests
        run: |
          just test

      - name: Run Acton tests
        run: |
          acton test

      - name: Prepare trunk archive
        if: github.ref == 'refs/heads/master' && github.repository == 'ton-blockchain/acton'
        shell: bash
        # language=Bash
        run: |
          set -euo pipefail

          ARTIFACTS_DIR="acton-${TARGET_NAME}"
          ARCHIVE_NAME="${ARTIFACTS_DIR}.tar.gz"

          mkdir -p "${ARTIFACTS_DIR}"
          cp "target/${TARGET_NAME}/release/acton" "${ARTIFACTS_DIR}/acton"
          tar -czvf "${ARCHIVE_NAME}" -C "${ARTIFACTS_DIR}" .
          shasum -a 256 "${ARCHIVE_NAME}" > "${ARCHIVE_NAME}.sha256"

      - name: Upload trunk archive artifact
        if: github.ref == 'refs/heads/master' && github.repository == 'ton-blockchain/acton'
        uses: actions/upload-artifact@v7
        with:
          name: artifacts-${{ env.TARGET_NAME }}
          path: |
            acton-${{ env.TARGET_NAME }}.tar.gz
            acton-${{ env.TARGET_NAME }}.tar.gz.sha256
          retention-days: 1
          if-no-files-found: error

  lint:
    name: Lint (${{ matrix.os }}-${{ matrix.arch }})
    strategy: *runner_linux_strategy
    runs-on: ${{ matrix.runner }}
    if: true

    permissions:
      contents: read

    steps:
      - name: Check out Acton repository
        uses: actions/checkout@v6
        with:
          persist-credentials: false

      - name: Cache Cargo
        uses: Swatinem/rust-cache@779680da715d629ac1d338a641029a2f4372abb5 # v2.8.2
        with:
          key: ${{ matrix.runner }}
          save-if: ${{ github.ref == 'refs/heads/master' }}

      - name: Install Rust
        run: rustup toolchain install

      - name: Installing additional Rust components
        uses: taiki-e/install-action@d6e286fa45544157a02d45a43742857ebbc25d12 # v2.68.16
        with:
          tool: just,cargo-shear,typos-cli

      - name: Download TON objects archive
        env:
          GH_TOKEN: ${{ github.token }}
          OBJS_NAME: ton-objs-${{ matrix.os }}-${{ matrix.arch }}
        run: |
          ARCHIVE_NAME="${OBJS_NAME}.tar.gz"
          mkdir -p objs
          gh release download trunk-objs \
            --repo "${GITHUB_REPOSITORY}" \
            --pattern "${ARCHIVE_NAME}" \
            --dir "${RUNNER_TEMP}"
          tar -C objs -xzf "${RUNNER_TEMP}/${ARCHIVE_NAME}"

      - name: Run formatter and linter
        run: |
          just check-ci

  build-macos:
    name: Build (${{ matrix.os }}-${{ matrix.arch }})
    strategy: &runner_macos_strategy
      matrix:
        include:
          - runner: macos-15
            os: apple-darwin
            arch: aarch64
    runs-on: ${{ matrix.runner }}
    if: true
    env:
      OBJS_NAME: ton-objs-macos-${{ matrix.arch }}
      TARGET_NAME: ${{ matrix.arch }}-${{ matrix.os }}

    permissions:
      contents: read

    steps:
      - name: Check out Acton repository
        uses: actions/checkout@v6
        with:
          persist-credentials: false

      - name: Cache Cargo
        uses: Swatinem/rust-cache@779680da715d629ac1d338a641029a2f4372abb5 # v2.8.2
        with:
          key: ${{ matrix.runner }}
          save-if: ${{ github.ref == 'refs/heads/master' }}

      - name: Install Rust
        run: rustup toolchain install

      - name: Installing additional Rust components
        uses: taiki-e/install-action@d6e286fa45544157a02d45a43742857ebbc25d12 # v2.68.16
        with:
          tool: nextest,just

      - name: Download TON objects archive
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          ARCHIVE_NAME="${OBJS_NAME}.tar.gz"
          mkdir -p objs
          gh release download trunk-objs \
            --repo "${GITHUB_REPOSITORY}" \
            --pattern "${ARCHIVE_NAME}" \
            --dir "${RUNNER_TEMP}"
          tar -C objs -xzf "${RUNNER_TEMP}/${ARCHIVE_NAME}"

      - name: Setup Bun
        uses: oven-sh/setup-bun@ecf28ddc73e819eb6fa29df6b34ef8921c743461 # v2.1.3

      - name: Build acton binary
        env:
          ACTON_RELEASE_CHANNEL: trunk
        run: |
          just build-ui
          cargo build --release --locked --target "${TARGET_NAME}" --bin acton

      - name: Add acton to PATH
        run: echo "${GITHUB_WORKSPACE}/target/${TARGET_NAME}/release" >> "$GITHUB_PATH"

      - name: Test acton binary
        run: |
          acton --help

      - name: Run tests
        run: |
          just test

      - name: Run Acton tests
        run: |
          acton test

      - name: Prepare trunk archive
        if: github.ref == 'refs/heads/master' && github.repository == 'ton-blockchain/acton'
        shell: bash
        # language=Bash
        run: |
          set -euo pipefail

          ARTIFACTS_DIR="acton-${TARGET_NAME}"
          ARCHIVE_NAME="${ARTIFACTS_DIR}.tar.gz"

          mkdir -p "${ARTIFACTS_DIR}"
          cp "target/${TARGET_NAME}/release/acton" "${ARTIFACTS_DIR}/acton"
          tar -czvf "${ARCHIVE_NAME}" -C "${ARTIFACTS_DIR}" .
          shasum -a 256 "${ARCHIVE_NAME}" > "${ARCHIVE_NAME}.sha256"

      - name: Upload trunk archive artifact
        if: github.ref == 'refs/heads/master' && github.repository == 'ton-blockchain/acton'
        uses: actions/upload-artifact@v7
        with:
          name: artifacts-${{ env.TARGET_NAME }}
          path: |
            acton-${{ env.TARGET_NAME }}.tar.gz
            acton-${{ env.TARGET_NAME }}.tar.gz.sha256
          retention-days: 1
          if-no-files-found: error

  create-trunk-release:
    name: Create Trunk Release
    needs: [ build-linux, build-macos ]
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master' && github.repository == 'ton-blockchain/acton'

    permissions:
      actions: write
      contents: write

    steps:
      - name: Download trunk archives
        uses: actions/download-artifact@v8
        with:
          pattern: artifacts-*
          path: artifacts/
          merge-multiple: true

      - name: Delete download artifacts
        uses: actions/github-script@v8
        with:
          github-token: ${{ github.token }}
          # language=JavaScript
          script: |
            const {
              data: artifacts
            } = await github.rest.actions.listWorkflowRunArtifacts({
              owner: context.repo.owner,
              repo: context.repo.repo,
              run_id: context.runId,
            });

            if (artifacts.total_count === 0) {
              core.warning('No downloadable artifacts to delete');
              return;
            } else {
              core.info(`Found ${artifacts.total_count} artifacts to delete`);
            }

            for (const artifact of artifacts.artifacts) {
              core.info(`Deleting artifact ${artifact.name} (${artifact.id})`);
              await github.rest.actions.deleteArtifact({
                owner: context.repo.owner,
                repo: context.repo.repo,
                artifact_id: artifact.id,
              });
            }

      - name: Display structure of downloaded files
        run: ls -lhR artifacts

      - name: Delete previous trunk release and tag
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          gh release delete trunk --repo "${GITHUB_REPOSITORY}" -y || true

          gh api \
            repos/${GITHUB_REPOSITORY}/git/refs/tags/trunk \
            -X DELETE || true

      - name: Create trunk release
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          release_notes=$(cat <<EOF
          Automated trunk build of Acton.

          Built from source commit: https://github.com/${GITHUB_REPOSITORY}/commit/${GITHUB_SHA}
          EOF
          )

          gh release create trunk \
            --repo "${GITHUB_REPOSITORY}" \
            artifacts/* \
            --title "Trunk" \
            --notes "${release_notes}" \
            --target "${GITHUB_SHA}" \
            --prerelease

      - name: Delete previous trunk release and tag (mirror)
        if: env.ENABLE_MIRRORING_RELEASE == 'true'
        env:
          GH_TOKEN: ${{ secrets.ACTON_PUBLIC }}
        run: |
          gh release delete trunk --repo "${PUBLIC_ACTON_REPOSITORY}" -y || true

          gh api \
            repos/${PUBLIC_ACTON_REPOSITORY}/git/refs/tags/trunk \
            -X DELETE || true

      - name: Create trunk release (mirror)
        if: env.ENABLE_MIRRORING_RELEASE == 'true'
        env:
          GH_TOKEN: ${{ secrets.ACTON_PUBLIC }}
        run: |
          release_notes=$(cat <<EOF
          Automated trunk build of Acton.

          Built from source commit: https://github.com/${GITHUB_REPOSITORY}/commit/${GITHUB_SHA}
          EOF
          )

          gh release create trunk \
            --repo "${PUBLIC_ACTON_REPOSITORY}" \
            artifacts/* \
            --title "Trunk" \
            --notes "${release_notes}" \
            --prerelease
