name: Check tycho-types

on:
  pull_request:
    branches:
      - master
    paths:
      - ".github/workflows/check-tycho-types.yml"
      - "libs/tycho-types/**"
      - "rust-toolchain.toml"
  push:
    branches:
      - master
    paths:
      - ".github/workflows/check-tycho-types.yml"
      - "libs/tycho-types/**"
      - "rust-toolchain.toml"
  workflow_dispatch:

concurrency:
  group: check-tycho-types-${{ github.ref }}
  cancel-in-progress: true

permissions: { }

jobs:
  check:
    name: Check tycho-types
    runs-on: ubicloud-standard-2-ubuntu-2204
    permissions:
      contents: read
    defaults:
      run:
        working-directory: libs/tycho-types
    steps:
      - name: Check out Acton repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: Cache Cargo
        uses: Swatinem/rust-cache@6323deb102c322ba6fcbdcafc7e3dddab59af2b6 # v2.9.2
        with:
          key: libs-tycho-types-${{ runner.os }}-${{ runner.arch }}
          save-if: ${{ github.ref == 'refs/heads/master' }}
          workspaces: libs/tycho-types -> target

      - name: Install Rust
        run: rustup toolchain install

      - name: Install nightly rustfmt
        run: rustup toolchain install nightly --profile minimal --component rustfmt

      - name: Check formatting
        run: cargo +nightly fmt --all -- --check

      - name: Test library
        run: cargo test --workspace --all-features

      - name: Check library
        run: cargo clippy --workspace --all-features -- -D warnings

      - name: Check minimal features
        run: cargo check --lib --no-default-features
