name: Check Rust Dependencies

on:
  workflow_call:
  pull_request:
    branches:
      - master
    paths:
      - ".github/workflows/check-rust-deps.yml"
      - "Cargo.toml"
      - "Cargo.lock"
      - "**/Cargo.toml"
      - "**/Cargo.lock"
      - "deny.toml"
  push:
    branches:
      - master
    paths:
      - ".github/workflows/check-rust-deps.yml"
      - "Cargo.toml"
      - "Cargo.lock"
      - "**/Cargo.toml"
      - "**/Cargo.lock"
      - "deny.toml"
  workflow_dispatch:

concurrency:
  group: check-deps-${{ github.ref }}
  cancel-in-progress: true

permissions: { }

jobs:
  rust-audit:
    name: Rust audit
    runs-on: ubicloud-standard-2-ubuntu-2204

    permissions:
      contents: read

    steps:
      - name: Check out Acton repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: Install cargo-deny
        uses: taiki-e/install-action@4bc351f7f2614e48088386e2a0ad917ca3a7e4ba # v2.81.5
        with:
          tool: just@1.49.0,cargo-deny@0.19.6,cargo-audit@0.22.1
          fallback: none

      - name: Run cargo-deny
        run: just check-deny

      - name: Run cargo-audit
        run: just check-audit
