name: Check faucet

on:
  pull_request:
    branches:
      - master
    paths:
      - ".github/workflows/check-faucet.yml"
      - "apps/faucet/**"
  push:
    branches:
      - master
    paths:
      - ".github/workflows/check-faucet.yml"
      - "apps/faucet/**"
  workflow_dispatch:

concurrency:
  group: check-faucet-${{ github.ref }}
  cancel-in-progress: true

permissions: { }

jobs:
  build:
    name: Build faucet
    if: github.event_name != 'pull_request' || github.event.pull_request.draft == false
    runs-on: ubicloud-standard-2-ubuntu-2204

    permissions:
      contents: read

    defaults:
      run:
        working-directory: apps/faucet

    steps:
      - name: Check out Acton repository
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false

      - name: Cache Cargo
        uses: Swatinem/rust-cache@c19371144df3bb44fab255c43d04cbc2ab54d1c4 # v2.9.1
        with:
          key: apps-faucet-${{ runner.os }}-${{ runner.arch }}
          save-if: ${{ github.ref == 'refs/heads/master' }}
          workspaces: apps/faucet -> target

      - name: Install Rust
        run: rustup toolchain install

      - name: Install just
        uses: taiki-e/install-action@15449e3094499af05d8d964a1c884208e4b8b595 # v2.81.11
        with:
          tool: just@1.52.0
          fallback: none

      - name: Build faucet
        run: just build-ci

  check:
    name: Check faucet
    if: github.event_name != 'pull_request' || github.event.pull_request.draft == false
    runs-on: ubicloud-standard-2-ubuntu-2204

    services:
      valkey:
        image: valkey/valkey:8.1-alpine@sha256:a038175878d66b9d274fbf8be73c0305e93798b83917647f167e18cef3c71eec
        ports:
          - 6379:6379
        options: >-
          --health-cmd "valkey-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    env:
      VALKEY_TEST_URI: redis://127.0.0.1:6379

    permissions:
      contents: read

    defaults:
      run:
        working-directory: apps/faucet

    steps:
      - name: Check out Acton repository
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false

      - name: Cache Cargo
        uses: Swatinem/rust-cache@c19371144df3bb44fab255c43d04cbc2ab54d1c4 # v2.9.1
        with:
          key: apps-faucet-${{ runner.os }}-${{ runner.arch }}
          save-if: ${{ github.ref == 'refs/heads/master' }}
          workspaces: apps/faucet -> target

      - name: Install Rust
        run: rustup toolchain install

      - name: Install check tools
        uses: taiki-e/install-action@15449e3094499af05d8d964a1c884208e4b8b595 # v2.81.11
        with:
          tool: just@1.52.0,cargo-shear@1.13.1,cargo-deny@0.19.8
          fallback: none

      - name: Test faucet
        run: just test

      - name: Check faucet
        run: just check-ci
