name: Check UI Dependencies

on:
  pull_request:
    branches:
      - master
    paths:
      - ".github/workflows/check-bun-deps.yml"
      - "bun.lock"
      - "package.json"
      - "crates/acton-litenode-ui"
      - "crates/acton-shared-ui"
      - "crates/acton-test-ui"
  push:
    branches:
      - master
  workflow_dispatch:

concurrency:
  group: check-js-deps-${{ github.ref }}
  cancel-in-progress: true

permissions: { }

jobs:
  bun-audit:
    name: Bun audit
    runs-on: ubicloud-standard-2-ubuntu-2204

    permissions:
      contents: read

    steps:
      - name: Check out Acton repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: Setup Bun
        uses: oven-sh/setup-bun@0c5077e51419868618aeaa5fe8019c62421857d6 # v2.2.0

      - name: Run Bun audit
        run: bun audit --audit-level=moderate
