name: Check UI Dependencies

on:
  workflow_call:
  pull_request:
    branches:
      - master
    paths:
      - ".github/workflows/check-ui-deps.yml"
      - ".npmrc"
      - "bun.lock"
      - "bunfig.toml"
      - "package.json"
      - "crates/acton-**-ui/package.json"
  push:
    branches:
      - master
    paths:
      - ".github/workflows/check-ui-deps.yml"
      - ".npmrc"
      - "bun.lock"
      - "bunfig.toml"
      - "package.json"
      - "crates/acton-**-ui/package.json"
  workflow_dispatch:

concurrency:
  group: check-ui-deps-${{ github.ref }}
  cancel-in-progress: true

permissions: { }

jobs:
  bun-audit:
    name: Bun audit
    runs-on: ubicloud-standard-2-ubuntu-2204

    permissions:
      contents: read

    steps:
      - name: Fetch Sources
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false

      - name: Installing additional Rust components
        uses: taiki-e/install-action@15449e3094499af05d8d964a1c884208e4b8b595 # v2.81.11
        with:
          tool: just@1.52.0
          fallback: none

      - name: Setup Bun
        uses: oven-sh/setup-bun@0c5077e51419868618aeaa5fe8019c62421857d6 # v2.2.0

      - name: Run Bun audit
        run: just check-ui-security
