name: Check Zizmor

on:
  pull_request:
    branches:
      - master
    paths:
      - ".github/**"
  push:
    branches:
      - master
    paths:
      - ".github/**"
  workflow_dispatch:

concurrency:
  group: check-zizmor-${{ github.ref }}
  cancel-in-progress: true

permissions: { }

jobs:
  zizmor:
    name: Check Zizmor
    runs-on: ubicloud-standard-2-ubuntu-2204

    permissions:
      contents: read
      security-events: write # upload SARIF report

    steps:
      - name: Checkout repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: Run zizmor
        uses: zizmorcore/zizmor-action@70fb788f84895a7701f5643d103d587e460b5c99 # v0.6.3
        with:
          min-severity: 'high'
          persona: 'auditor'
