name: Check Release Security

on:
  workflow_call:
  workflow_dispatch:

concurrency:
  group: check-release-security-${{ github.ref }}
  cancel-in-progress: true

permissions: { }

jobs:
  rust-deps:
    uses: ./.github/workflows/check-rust-deps.yml
    secrets: inherit

  ui-deps:
    uses: ./.github/workflows/check-ui-deps.yml
    secrets: inherit

  grammar-deps:
    uses: ./.github/workflows/check-grammar-deps.yml
    secrets: inherit
