name: Check localton

on:
  pull_request:
    branches:
      - master
    paths:
      - ".github/workflows/check-localton.yml"
      - "apps/localton/**"
  push:
    branches:
      - master
    paths:
      - ".github/workflows/check-localton.yml"
      - "apps/localton/**"
  workflow_dispatch:

concurrency:
  group: check-localton-${{ github.ref }}
  cancel-in-progress: true

permissions: { }

jobs:
  build:
    name: Build localton
    if: github.event_name != 'pull_request' || github.event.pull_request.draft == false
    runs-on: ubicloud-standard-2-ubuntu-2204

    permissions:
      contents: read

    defaults:
      run:
        working-directory: apps/localton

    steps:
      - name: Check out Acton repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: Cache Cargo
        uses: Swatinem/rust-cache@6323deb102c322ba6fcbdcafc7e3dddab59af2b6 # v2.9.2
        with:
          key: apps-localton-${{ runner.os }}-${{ runner.arch }}
          save-if: ${{ github.ref == 'refs/heads/master' }}
          workspaces: apps/localton -> target

      - name: Install Rust
        run: rustup toolchain install

      - name: Setup Bun
        uses: oven-sh/setup-bun@0c5077e51419868618aeaa5fe8019c62421857d6 # v2.2.0

      - name: Install UI dependencies
        working-directory: ${{ github.workspace }}
        run: bun ci

      - name: Install just
        uses: taiki-e/install-action@84f5ac3124727fb3d284d4d22ee9ab3654fd09a6 # v2.87.7
        with:
          tool: just@1.58.0
          fallback: none

      - name: Build localton
        run: just build-ci

  check:
    name: Check localton
    if: github.event_name != 'pull_request' || github.event.pull_request.draft == false
    runs-on: ubicloud-standard-2-ubuntu-2204

    permissions:
      contents: read

    defaults:
      run:
        working-directory: apps/localton

    steps:
      - name: Check out Acton repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: Cache Cargo
        uses: Swatinem/rust-cache@6323deb102c322ba6fcbdcafc7e3dddab59af2b6 # v2.9.2
        with:
          key: apps-localton-${{ runner.os }}-${{ runner.arch }}
          save-if: ${{ github.ref == 'refs/heads/master' }}
          workspaces: apps/localton -> target

      - name: Install Rust
        run: rustup toolchain install

      - name: Install check tools
        uses: taiki-e/install-action@84f5ac3124727fb3d284d4d22ee9ab3654fd09a6 # v2.87.7
        with:
          tool: just@1.58.0,cargo-shear@1.13.4,cargo-deny@0.20.2
          fallback: none

      - name: Test localton
        run: just test

      - name: Check localton
        run: just check-ci
