name: Create Trunk Release

on:
  workflow_call:

permissions: { }

env:
  ENABLE_MIRRORING_RELEASE: 'true'
  PUBLIC_ACTON_REPOSITORY: i582/acton-public

jobs:
  create-trunk-release:
    name: Create Trunk Release
    runs-on: ubicloud-standard-2-ubuntu-2204
    env:
      TARGET_SHA: ${{ github.sha }}

    permissions:
      actions: write
      contents: write

    steps:
      - name: Download trunk archives
        uses: actions/download-artifact@v8
        with:
          pattern: artifacts-*
          path: artifacts
          merge-multiple: true

      - name: Delete downloaded artifacts
        uses: actions/github-script@v8
        with:
          github-token: ${{ github.token }}
          # language=JavaScript
          script: |
            const runId = context.runId;
            const {
              data: artifacts
            } = await github.rest.actions.listWorkflowRunArtifacts({
              owner: context.repo.owner,
              repo: context.repo.repo,
              run_id: runId,
            });

            if (artifacts.total_count === 0) {
              core.warning(`No downloadable artifacts to delete for run ${runId}`);
              return;
            } else {
              core.info(`Found ${artifacts.total_count} artifacts to delete for run ${runId}`);
            }

            for (const artifact of artifacts.artifacts) {
              core.info(`Deleting artifact ${artifact.name} (${artifact.id})`);
              await github.rest.actions.deleteArtifact({
                owner: context.repo.owner,
                repo: context.repo.repo,
                artifact_id: artifact.id,
              });
            }

      - name: Display structure of downloaded files
        run: ls -lhR artifacts

      - name: Delete previous trunk release and tag
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          gh release delete trunk --repo "${GITHUB_REPOSITORY}" -y || true

          gh api \
            repos/${GITHUB_REPOSITORY}/git/refs/tags/trunk \
            -X DELETE || true

      - name: Create trunk release
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          release_notes=$(cat <<EOF
          Automated trunk build of Acton.

          Built from source commit: https://github.com/${GITHUB_REPOSITORY}/commit/${TARGET_SHA}
          EOF
          )

          gh release create trunk \
            --repo "${GITHUB_REPOSITORY}" \
            artifacts/* \
            --title "Trunk" \
            --notes "${release_notes}" \
            --target "${TARGET_SHA}" \
            --prerelease

      - name: Delete previous trunk release and tag (mirror)
        if: env.ENABLE_MIRRORING_RELEASE == 'true'
        env:
          GH_TOKEN: ${{ secrets.ACTON_PUBLIC }}
        run: |
          gh release delete trunk --repo "${PUBLIC_ACTON_REPOSITORY}" -y || true

          gh api \
            repos/${PUBLIC_ACTON_REPOSITORY}/git/refs/tags/trunk \
            -X DELETE || true

      - name: Create trunk release (mirror)
        if: env.ENABLE_MIRRORING_RELEASE == 'true'
        env:
          GH_TOKEN: ${{ secrets.ACTON_PUBLIC }}
        run: |
          release_notes=$(cat <<EOF
          Automated trunk build of Acton.

          Built from source commit: https://github.com/${GITHUB_REPOSITORY}/commit/${TARGET_SHA}
          EOF
          )

          gh release create trunk \
            --repo "${PUBLIC_ACTON_REPOSITORY}" \
            artifacts/* \
            --title "Trunk" \
            --notes "${release_notes}" \
            --prerelease
