name: Cargo Deny

on:
  pull_request:
    branches:
      - master
    paths:
      - "Cargo.toml"
      - "Cargo.lock"
      - "**/Cargo.toml"
      - "**/Cargo.lock"
      - "deny.toml"
  push:
    branches:
      - master
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  cargo-deny:
    name: Deny Checks
    strategy:
      matrix:
        os: [ ubicloud-standard-4-ubuntu-2204 ]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Check out Acton repository
        uses: actions/checkout@v6

      - name: Cache Cargo
        uses: Swatinem/rust-cache@v2
        with:
          key: ${{ matrix.os }}
          save-if: false

      - name: Install Rust
        run: rustup toolchain install

      - name: Install cargo-deny
        uses: taiki-e/install-action@v2
        with:
          tool: cargo-deny

      - name: Run cargo-deny
        run: cargo deny check
