name: Building tree-sitter grammar

on:
  pull_request:
    branches:
      - master
    paths:
      - ".github/workflows/grammars.yml"
      - "crates/tree-sitter-**/**"
  push:
    branches:
      - master
    paths:
      - ".github/workflows/grammars.yml"
      - "crates/tree-sitter-**/**"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions: { }

jobs:
  tree-sitter-grammars:
    name: Test tree-sitter-${{ matrix.language }} grammar
    runs-on: ubicloud-standard-4-ubuntu-2204
    strategy:
      fail-fast: false
      matrix:
        language:
          - fift
          - tasm
          - tlb
          - tolk
    if: true

    permissions:
      contents: read

    steps:
      - name: Fetch Sources
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: Enable Corepack
        run: corepack enable

      - name: Setup Node.js 22.x
        uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6.3.0
        with:
          node-version: 22.x
          cache-dependency-path: crates/tree-sitter-${{ matrix.language }}/yarn.lock
          cache: "yarn"

      - name: Install dependencies
        working-directory: crates/tree-sitter-${{ matrix.language }}
        run: yarn install --immutable --check-cache --check-resolutions

      - name: Build
        working-directory: crates/tree-sitter-${{ matrix.language }}
        run: yarn tree-sitter generate

      - name: Test parsers
        working-directory: crates/tree-sitter-${{ matrix.language }}
        run: yarn tree-sitter test
