name: Building Tolk tree-sitter grammar

on:
  pull_request:
    branches:
      - master
    paths:
      - crates/tree-sitter-tolk/**
  push:
    branches:
      - master
    paths:
      - crates/tree-sitter-tolk/**

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  tree-sitter-grammars:
    name: Test tree-sitter
    runs-on: ubicloud-standard-4
    if: true

    steps:
      - name: Fetch Sources
        uses: actions/checkout@v6

      - name: Enable Corepack
        run: corepack enable

      - name: Setup Node.js 22.x
        uses: actions/setup-node@v6
        with:
          node-version: 22.x
          cache-dependency-path: crates/tree-sitter-tolk/yarn.lock
          cache: "yarn"

      - name: Install dependencies
        working-directory: crates/tree-sitter-tolk
        run: yarn install --immutable --check-cache --check-resolutions

      - name: Build
        working-directory: crates/tree-sitter-tolk
        run: yarn tree-sitter generate

      - name: Test parsers
        working-directory: crates/tree-sitter-tolk
        run: yarn tree-sitter test -u
