build:
    cargo build --release

build-dev:
    cargo build

build-ci:
    cargo build --release --locked --bin faucet-backend

fmt:
    cargo fmt --all

fmt-check:
    cargo fmt --all --check

check-deps:
    cargo shear --deny-warnings

clippy:
    cargo clippy --workspace --all-targets --all-features --locked -- -D warnings

check-deny:
    cargo deny check

test:
    cargo test --workspace --locked

check-ci: fmt-check check-deps clippy check-deny

check: check-ci test
