all: precommit

build:
    cargo build --release --locked

build-dev:
    cargo build --locked

build-ci: build

fmt:
    cargo fmt --all

fmt-check:
    cargo fmt --all --check

check-deps:
    cargo shear --deny-warnings

clippy:
    cargo clippy --workspace --all-targets --all-features --locked -- -D warnings

check-deny:
    cargo deny check

test:
    cargo test --workspace --locked

check-ci: fmt-check check-deps clippy check-deny

check: check-ci test

precommit: fmt build check

run:
    cargo run --locked

clean:
    cargo clean
