[package]
name = "faucet-config"
version = { workspace = true }
publish = false
authors = { workspace = true }
edition = { workspace = true }
rust-version = { workspace = true }
repository = { workspace = true }
license = { workspace = true }

[lib]
doctest = false

[dependencies]
anyhow = { workspace = true }
http = { workspace = true }
ipnet = { workspace = true }
