import {useCallback, useEffect, useMemo, useRef, useState} from "react"
import type {ChangeEvent, DragEvent, FC, FormEvent, JSX} from "react"
import {
  DateTime,
  formatCompilerLabel,
  InlineAction,
  InlineActions,
  Pagination,
  TechnicalValue,
  useToast,
} from "@acton/ui"
import {CircleAlert, FolderUp, Plus, Trash2, Upload} from "lucide-react"

import type {TonClient} from "../api/client"
import type {VerificationSourceResponse} from "../api/types"
import {
  buildSourceImportPlan,
  collectDroppedImportFiles,
  collectPickedImportFiles,
  sourceArtifactFromJson,
  type AbiImportFile,
} from "./buildImport"
import {JsonUploadField} from "./JsonUploadField"
import {useSearchParamPagination} from "../hooks/useSearchParamPagination"
import {useMetadataRegistry} from "../metadata/MetadataRegistryProvider"
import {sourceRegistrationFromResponse} from "../metadata/sourceRegistration"
import type {RegisteredSource} from "../metadata/types"

import styles from "./SourceCatalog.module.css"

interface SourceCatalogState {
  readonly loading: boolean
  readonly sources: readonly RegisteredSource[]
}

interface SourceTableEntry {
  readonly artifactId: string
  // Set only for sources the backend registered (localnet/studio); sources
  // registered into the browser environment have no backend artifact.
  readonly backendArtifactId?: string
  readonly codeHash: string
  readonly entrypoint: string
  readonly compiler: string
  readonly files: number
  readonly savedAt: number
}

const SOURCE_UPLOAD_ERROR =
  "Uploaded JSON must be a source artifact generated by acton build --output-sources."

export const SourceCatalog: FC<{readonly client: TonClient}> = ({client}) => {
  const metadataRegistry = useMetadataRegistry()
  const {showToast} = useToast()
  const [state, setState] = useState<SourceCatalogState>({loading: true, sources: []})
  const [sourceJson, setSourceJson] = useState("")
  const [sourceFormExpanded, setSourceFormExpanded] = useState(false)
  const [dropActive, setDropActive] = useState(false)
  const [importing, setImporting] = useState(false)
  const dragDepth = useRef(0)
  const directoryInputRef = useRef<HTMLInputElement>(null)

  const loadSources = useCallback(async () => {
    setState(current => ({...current, loading: true}))
    const sources = await metadataRegistry.listSources()
    setState({loading: false, sources})
  }, [metadataRegistry])

  useEffect(() => {
    let isActive = true
    setState(current => ({...current, loading: true}))
    metadataRegistry
      .listSources()
      .then(sources => {
        if (isActive) {
          setState({loading: false, sources})
        }
      })
      .catch(error => {
        if (isActive) {
          console.debug("Failed to load registered sources", error)
          setState({loading: false, sources: []})
        }
      })

    return () => {
      isActive = false
    }
  }, [metadataRegistry])

  const handleSourceUpload = async (event: FormEvent) => {
    event.preventDefault()

    try {
      const source = parseSourceArtifact(sourceJson)
      const registration = sourceRegistrationFromResponse(source)
      if (!registration) {
        throw new Error(SOURCE_UPLOAD_ERROR)
      }

      await metadataRegistry.registerSources([registration])
      setSourceJson("")
      setSourceFormExpanded(false)
      showToast({
        title: "Source registered",
        variant: "success",
      })
      await loadSources()
    } catch (error) {
      showToast({
        title: "Source not registered",
        description: error instanceof Error ? error.message : "Failed to register source.",
        variant: "error",
      })
    }
  }

  const importSourceFiles = useCallback(
    async (files: readonly AbiImportFile[]) => {
      if (importing) {
        return
      }
      setImporting(true)
      try {
        if (!metadataRegistry.canWriteSources) {
          throw new Error("This environment does not accept source registrations.")
        }
        const plan = buildSourceImportPlan(files)
        if (plan.registrations.length === 0) {
          throw new Error(plan.warnings[0] ?? "No source artifacts found in the drop.")
        }
        await metadataRegistry.registerSources(plan.registrations)
        showToast({
          title: `Registered ${plan.registrations.length} source${plan.registrations.length === 1 ? "" : "s"}`,
          description: plan.registeredNames.join(", "),
          variant: "success",
        })
        await loadSources()
      } catch (error) {
        showToast({
          title: "Sources not registered",
          description: error instanceof Error ? error.message : "Failed to import sources.",
          variant: "error",
        })
      } finally {
        setImporting(false)
      }
    },
    [importing, loadSources, metadataRegistry, showToast],
  )

  const handleDragEnter = (event: DragEvent) => {
    if (!event.dataTransfer.types.includes("Files")) {
      return
    }
    event.preventDefault()
    dragDepth.current += 1
    setDropActive(true)
  }

  const handleDragOver = (event: DragEvent) => {
    if (event.dataTransfer.types.includes("Files")) {
      event.preventDefault()
    }
  }

  const handleDragLeave = (event: DragEvent) => {
    if (!event.dataTransfer.types.includes("Files")) {
      return
    }
    dragDepth.current = Math.max(0, dragDepth.current - 1)
    if (dragDepth.current === 0) {
      setDropActive(false)
    }
  }

  const handleDrop = async (event: DragEvent) => {
    if (!event.dataTransfer.types.includes("Files")) {
      return
    }
    event.preventDefault()
    dragDepth.current = 0
    setDropActive(false)
    await importSourceFiles(await collectDroppedImportFiles(event.dataTransfer))
  }

  const handleDirectoryPick = async (event: ChangeEvent<HTMLInputElement>) => {
    const files = await collectPickedImportFiles(event.target.files)
    event.target.value = ""
    await importSourceFiles(files)
  }

  const handleDeleteSource = async (entry: SourceTableEntry) => {
    try {
      // Backend-registered artifacts (localnet/studio) delete through the
      // control API; browser-environment registrations live in the metadata
      // registry, which the control endpoint knows nothing about.
      if (entry.backendArtifactId) {
        await client.deleteRegisteredVerifiedSourceArtifact(entry.backendArtifactId)
      } else {
        await metadataRegistry.deleteSource(entry.codeHash)
      }
      showToast({
        title: "Source deleted",
        variant: "success",
      })
      await loadSources()
    } catch (error) {
      showToast({
        title: "Source not deleted",
        description: error instanceof Error ? error.message : "Failed to delete source.",
        variant: "error",
      })
    }
  }

  const tableEntries = useMemo(() => state.sources.map(sourceToTableEntry), [state.sources])
  const pagination = useSearchParamPagination(tableEntries, {ready: !state.loading})
  const canSubmit = metadataRegistry.canWriteSources && sourceJson.trim().length > 0
  const toggleSourceForm = () => setSourceFormExpanded(expanded => !expanded)

  return (
    // biome-ignore lint/a11y/noStaticElementInteractions: Drag-and-drop is a pointer-only shortcut; the "Import project folder" button is the accessible path.
    <section
      className={styles.tableFrame}
      onDragEnter={handleDragEnter}
      onDragOver={handleDragOver}
      onDragLeave={handleDragLeave}
      onDrop={event => {
        void handleDrop(event)
      }}
    >
      {dropActive && (
        <div className={styles.dropOverlay}>
          <FolderUp size={28} />
          <span>Drop your acton project folder to register its source artifacts</span>
        </div>
      )}
      {state.loading ? (
        <SourceCatalogSkeleton />
      ) : (
        <>
          <div className={styles.tableScroller}>
            <table className={styles.table}>
              <thead>
                <tr>
                  <th>Entrypoint</th>
                  <th>Artifact</th>
                  <th>Code hash</th>
                  <th>Compiler</th>
                  <th>Files</th>
                  <th>Uploaded at</th>
                </tr>
              </thead>
              <tbody>
                <tr className={styles.formButtonRow}>
                  <td colSpan={6}>
                    <div className={styles.actionButtonsRow}>
                      <button
                        type="button"
                        className={styles.registerSourceButton}
                        aria-expanded={sourceFormExpanded}
                        onClick={toggleSourceForm}
                      >
                        <Plus size={16} />
                        <span>Register source</span>
                      </button>
                      <button
                        type="button"
                        className={styles.importProjectButton}
                        disabled={importing || !metadataRegistry.canWriteSources}
                        onClick={() => directoryInputRef.current?.click()}
                        title="Register every source artifact found in an acton project folder (or drop the folder anywhere on this table). Artifacts come from `acton build --output-sources build/sources`."
                      >
                        <FolderUp size={16} />
                        <span>{importing ? "Importing…" : "Import project folder"}</span>
                      </button>
                      <input
                        ref={directoryInputRef}
                        className={styles.hiddenFileInput}
                        type="file"
                        multiple
                        {...directoryInputProps}
                        onChange={event => {
                          void handleDirectoryPick(event)
                        }}
                      />
                    </div>
                  </td>
                </tr>
                {sourceFormExpanded && (
                  <tr className={styles.expandedFormRow}>
                    <td colSpan={6}>
                      <form className={styles.sourceInlineForm} onSubmit={handleSourceUpload}>
                        <JsonUploadField
                          label="Source artifact JSON"
                          value={sourceJson}
                          onChange={setSourceJson}
                        />
                        <p className={styles.localNote}>
                          <CircleAlert size={15} />
                          <span>Source artifacts remain in this virtual environment</span>
                        </p>
                        <button
                          type="submit"
                          className={styles.primaryButton}
                          disabled={!canSubmit}
                        >
                          <Upload size={15} />
                          Register source
                        </button>
                      </form>
                    </td>
                  </tr>
                )}
                {tableEntries.length === 0 ? (
                  <tr>
                    <td colSpan={6}>
                      <div className={styles.empty}>No sources registered</div>
                    </td>
                  </tr>
                ) : (
                  pagination.currentItems.map(entry => (
                    <tr key={entry.artifactId} className={styles.tableRow}>
                      <td>
                        <InlineActions
                          className={styles.nameCell}
                          visibility="always"
                          actions={
                            metadataRegistry.canWriteSources ? (
                              <InlineAction
                                label="Delete source"
                                icon={<Trash2 />}
                                onClick={() => void handleDeleteSource(entry)}
                              />
                            ) : undefined
                          }
                        >
                          <span className={styles.entrypointCell}>
                            <span>{entry.entrypoint}</span>
                          </span>
                        </InlineActions>
                      </td>
                      <td>
                        <div className={styles.codeHashCell}>
                          <TechnicalValue
                            className={styles.codeHash}
                            value={entry.artifactId}
                            copyLabel="artifact ID"
                            startLength={10}
                            endLength={6}
                            copyVisibility="always"
                          />
                        </div>
                      </td>
                      <td>
                        <div className={styles.codeHashCell}>
                          <TechnicalValue
                            className={styles.codeHash}
                            value={entry.codeHash}
                            copyLabel="code hash"
                            startLength={10}
                            endLength={6}
                            copyVisibility="always"
                          />
                        </div>
                      </td>
                      <td>{entry.compiler}</td>
                      <td>{entry.files}</td>
                      <td>
                        <DateTime
                          fallback="unknown"
                          value={
                            Number.isFinite(entry.savedAt) && entry.savedAt > 0
                              ? entry.savedAt
                              : undefined
                          }
                        />
                      </td>
                    </tr>
                  ))
                )}
              </tbody>
            </table>
          </div>
          <Pagination
            currentPage={pagination.currentPage}
            totalItems={pagination.totalItems}
            pageSize={pagination.pageSize}
            onPageChange={pagination.setCurrentPage}
            label="Source catalog pagination"
          />
        </>
      )}
    </section>
  )
}

// `webkitdirectory` enables directory picking but is missing from React's input
// prop types, so it goes in via a spread.
const directoryInputProps = {webkitdirectory: ""} as Record<string, string>

function parseSourceArtifact(raw: string): VerificationSourceResponse {
  let parsed: unknown
  try {
    parsed = JSON.parse(raw)
  } catch {
    throw new Error(SOURCE_UPLOAD_ERROR)
  }

  const source = sourceArtifactFromJson(parsed)
  if (!source) {
    throw new Error(SOURCE_UPLOAD_ERROR)
  }

  return source
}

function sourceToTableEntry(source: RegisteredSource): SourceTableEntry {
  const bundle = source.source.bundle
  return {
    artifactId: source.artifactId ?? bundle?.source_bundle_hash ?? source.codeHash,
    backendArtifactId: source.artifactId,
    codeHash: source.codeHash,
    entrypoint: bundle?.entrypoint ?? "unknown",
    compiler: formatCompilerLabel(bundle?.compiler, "unknown"),
    files: bundle?.files.length ?? 0,
    savedAt: source.savedAt,
  }
}

function SourceCatalogSkeleton(): JSX.Element {
  return (
    <div className={styles.skeletonList} aria-label="Loading registered sources">
      {Array.from({length: 5}, (_, index) => (
        <div key={index} className={styles.skeletonRow}>
          <span />
          <span />
          <span />
        </div>
      ))}
    </div>
  )
}
