[package]
name = "ton-node-db"
description = "Lazy TON state queries and persistent updates from validator snapshots"
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
repository.workspace = true
license.workspace = true
publish = false

[lib]
test = false
doctest = false

[dependencies]
anyhow.workspace = true
base64.workspace = true
dunce.workspace = true
quick_cache = { version = "0.7", default-features = false }
rayon = "1.11"
rocksdb = "0.25.0"
serde.workspace = true
serde_json.workspace = true
sha2.workspace = true
tl-proto.workspace = true
tracing.workspace = true
rston = { workspace = true, features = ["serde", "rayon"] }

[dev-dependencies]
clap.workspace = true
expect-test.workspace = true
tempfile.workspace = true
tokio.workspace = true
ton-indexer-core = { path = "../ton-indexer-core" }
ton-indexer-p2p = { path = "../ton-indexer-p2p" }
ton-p2p = { path = "../ton-p2p" }
tracing-subscriber = { version = "0.3", features = ["env-filter"] }

[lints]
workspace = true
